<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Population Statistics | Data Science for Agricultural Professionals</title>
  <meta name="description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Population Statistics | Data Science for Agricultural Professionals" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://mharbur.github.io/data-science-for-agricultural-professionals/" />
  
  <meta property="og:description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  <meta name="github-repo" content="https://github.com/mharbur/data-science-for-agricultural-professionals" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Population Statistics | Data Science for Agricultural Professionals" />
  
  <meta name="twitter:description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  

<meta name="author" content="Marin L. Harbur" />


<meta name="date" content="2021-08-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="distributions-and-probability.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>
<script src="libs/stars-1/data_stars_stars256de7.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/joda-0.0.1/addImageQuery-bindings.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science for Agricultural Professionals</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#welcome"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-language"><i class="fa fa-check"></i>R-language</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="population-statistics.html"><a href="population-statistics.html"><i class="fa fa-check"></i><b>1</b> Population Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="population-statistics.html"><a href="population-statistics.html#populations"><i class="fa fa-check"></i><b>1.1</b> Populations</a></li>
<li class="chapter" data-level="1.2" data-path="population-statistics.html"><a href="population-statistics.html#case-study-yield-map"><i class="fa fa-check"></i><b>1.2</b> Case Study: Yield Map</a></li>
<li class="chapter" data-level="1.3" data-path="population-statistics.html"><a href="population-statistics.html#distributions"><i class="fa fa-check"></i><b>1.3</b> Distributions</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="population-statistics.html"><a href="population-statistics.html#histograms"><i class="fa fa-check"></i><b>1.3.1</b> Histograms</a></li>
<li class="chapter" data-level="1.3.2" data-path="population-statistics.html"><a href="population-statistics.html#percentiles"><i class="fa fa-check"></i><b>1.3.2</b> Percentiles</a></li>
<li class="chapter" data-level="1.3.3" data-path="population-statistics.html"><a href="population-statistics.html#normal-distribution-model"><i class="fa fa-check"></i><b>1.3.3</b> Normal Distribution Model</a></li>
<li class="chapter" data-level="1.3.4" data-path="population-statistics.html"><a href="population-statistics.html#measures-of-center"><i class="fa fa-check"></i><b>1.3.4</b> Measures of Center</a></li>
<li class="chapter" data-level="1.3.5" data-path="population-statistics.html"><a href="population-statistics.html#measures-of-dispersion"><i class="fa fa-check"></i><b>1.3.5</b> Measures of Dispersion</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="population-statistics.html"><a href="population-statistics.html#exercise-introduction-to-r"><i class="fa fa-check"></i><b>1.4</b> Exercise: Introduction to R</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="population-statistics.html"><a href="population-statistics.html#your-very-first-code"><i class="fa fa-check"></i><b>1.4.1</b> Your Very First Code</a></li>
<li class="chapter" data-level="1.4.2" data-path="population-statistics.html"><a href="population-statistics.html#reading-and-working-with-data-frames"><i class="fa fa-check"></i><b>1.4.2</b> Reading and Working with Data Frames</a></li>
<li class="chapter" data-level="1.4.3" data-path="population-statistics.html"><a href="population-statistics.html#basic-operations-on-columns"><i class="fa fa-check"></i><b>1.4.3</b> Basic Operations on Columns</a></li>
<li class="chapter" data-level="1.4.4" data-path="population-statistics.html"><a href="population-statistics.html#knitting-your-results-into-a-document"><i class="fa fa-check"></i><b>1.4.4</b> Knitting Your Results into a Document</a></li>
<li class="chapter" data-level="1.4.5" data-path="population-statistics.html"><a href="population-statistics.html#practice"><i class="fa fa-check"></i><b>1.4.5</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="population-statistics.html"><a href="population-statistics.html#exercise-introduction-to-shapefiles"><i class="fa fa-check"></i><b>1.5</b> Exercise: Introduction to Shapefiles</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="population-statistics.html"><a href="population-statistics.html#r-packages"><i class="fa fa-check"></i><b>1.5.1</b> R Packages</a></li>
<li class="chapter" data-level="1.5.2" data-path="population-statistics.html"><a href="population-statistics.html#reading-shapefiles"><i class="fa fa-check"></i><b>1.5.2</b> Reading Shapefiles</a></li>
<li class="chapter" data-level="1.5.3" data-path="population-statistics.html"><a href="population-statistics.html#examining-spatial-feature-data-frames"><i class="fa fa-check"></i><b>1.5.3</b> Examining Spatial Feature Data Frames</a></li>
<li class="chapter" data-level="1.5.4" data-path="population-statistics.html"><a href="population-statistics.html#visualizing-data"><i class="fa fa-check"></i><b>1.5.4</b> Visualizing Data</a></li>
<li class="chapter" data-level="1.5.5" data-path="population-statistics.html"><a href="population-statistics.html#create-your-own-maps"><i class="fa fa-check"></i><b>1.5.5</b> Create Your Own Maps</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="population-statistics.html"><a href="population-statistics.html#exercise-histograms"><i class="fa fa-check"></i><b>1.6</b> Exercise: Histograms</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="population-statistics.html"><a href="population-statistics.html#case-study"><i class="fa fa-check"></i><b>1.6.1</b> Case Study</a></li>
<li class="chapter" data-level="1.6.2" data-path="population-statistics.html"><a href="population-statistics.html#basic-histogram"><i class="fa fa-check"></i><b>1.6.2</b> Basic Histogram</a></li>
<li class="chapter" data-level="1.6.3" data-path="population-statistics.html"><a href="population-statistics.html#histograms-with-ggplot"><i class="fa fa-check"></i><b>1.6.3</b> Histograms with ggplot</a></li>
<li class="chapter" data-level="1.6.4" data-path="population-statistics.html"><a href="population-statistics.html#practice-1"><i class="fa fa-check"></i><b>1.6.4</b> Practice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html"><i class="fa fa-check"></i><b>2</b> Distributions and Probability</a>
<ul>
<li class="chapter" data-level="2.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#case-study-1"><i class="fa fa-check"></i><b>2.1</b> Case Study</a></li>
<li class="chapter" data-level="2.2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-normal-distribution-model"><i class="fa fa-check"></i><b>2.2</b> The Normal Distribution Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-bell-curve"><i class="fa fa-check"></i><b>2.2.1</b> The Bell Curve</a></li>
<li class="chapter" data-level="2.2.2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#distribution-and-probability"><i class="fa fa-check"></i><b>2.2.2</b> Distribution and Probability</a></li>
<li class="chapter" data-level="2.2.3" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#probability-and-the-normal-distribution-curve"><i class="fa fa-check"></i><b>2.2.3</b> Probability and the Normal Distribution Curve</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-z-distribution"><i class="fa fa-check"></i><b>2.3</b> The Z-Distribution</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#important-numbers-95-and-5"><i class="fa fa-check"></i><b>2.3.1</b> Important Numbers: 95% and 5%</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-statistics.html"><a href="sample-statistics.html"><i class="fa fa-check"></i><b>3</b> Sample Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-statistics.html"><a href="sample-statistics.html#samples"><i class="fa fa-check"></i><b>3.1</b> Samples</a></li>
<li class="chapter" data-level="3.2" data-path="sample-statistics.html"><a href="sample-statistics.html#case-study-2"><i class="fa fa-check"></i><b>3.2</b> Case Study</a></li>
<li class="chapter" data-level="3.3" data-path="sample-statistics.html"><a href="sample-statistics.html#distribution-of-sample-means"><i class="fa fa-check"></i><b>3.3</b> Distribution of Sample Means</a></li>
<li class="chapter" data-level="3.4" data-path="sample-statistics.html"><a href="sample-statistics.html#central-limit-theorem"><i class="fa fa-check"></i><b>3.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="3.5" data-path="sample-statistics.html"><a href="sample-statistics.html#standard-error"><i class="fa fa-check"></i><b>3.5</b> Standard Error</a></li>
<li class="chapter" data-level="3.6" data-path="sample-statistics.html"><a href="sample-statistics.html#degrees-of-freedom"><i class="fa fa-check"></i><b>3.6</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="3.7" data-path="sample-statistics.html"><a href="sample-statistics.html#the-t-distribution"><i class="fa fa-check"></i><b>3.7</b> The t-Distribution</a></li>
<li class="chapter" data-level="3.8" data-path="sample-statistics.html"><a href="sample-statistics.html#confidence-interval"><i class="fa fa-check"></i><b>3.8</b> Confidence Interval</a></li>
<li class="chapter" data-level="3.9" data-path="sample-statistics.html"><a href="sample-statistics.html#confidence-interval-and-probability"><i class="fa fa-check"></i><b>3.9</b> Confidence Interval and Probability</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two-Treatment Comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#side-by-side-trials"><i class="fa fa-check"></i><b>4.1</b> Side-by-Side Trials</a></li>
<li class="chapter" data-level="4.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#blocked-design"><i class="fa fa-check"></i><b>4.2</b> Blocked Design</a></li>
<li class="chapter" data-level="4.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-3"><i class="fa fa-check"></i><b>4.3</b> Case Study</a></li>
<li class="chapter" data-level="4.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#confidence-interval-1"><i class="fa fa-check"></i><b>4.4</b> Confidence Interval</a></li>
<li class="chapter" data-level="4.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#t-test"><i class="fa fa-check"></i><b>4.5</b> T-Test</a></li>
<li class="chapter" data-level="4.6" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-randomizing-plots"><i class="fa fa-check"></i><b>4.6</b> Exercise: Randomizing Plots</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-1"><i class="fa fa-check"></i><b>4.6.1</b> Example 1</a></li>
<li class="chapter" data-level="4.6.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#the-agricolae-package"><i class="fa fa-check"></i><b>4.6.2</b> The Agricolae Package</a></li>
<li class="chapter" data-level="4.6.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#randomizing-the-plot"><i class="fa fa-check"></i><b>4.6.3</b> Randomizing the Plot</a></li>
<li class="chapter" data-level="4.6.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#working-with-lists"><i class="fa fa-check"></i><b>4.6.4</b> Working with Lists</a></li>
<li class="chapter" data-level="4.6.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-2"><i class="fa fa-check"></i><b>4.6.5</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-restructuring-columns-and-rows"><i class="fa fa-check"></i><b>4.7</b> Exercise: Restructuring Columns and Rows</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#operations-on-data"><i class="fa fa-check"></i><b>4.7.1</b> Operations on Data</a></li>
<li class="chapter" data-level="4.7.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-soybean-fungicide"><i class="fa fa-check"></i><b>4.7.2</b> Case Study: Soybean Fungicide</a></li>
<li class="chapter" data-level="4.7.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-1-1"><i class="fa fa-check"></i><b>4.7.3</b> Practice 1</a></li>
<li class="chapter" data-level="4.7.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-2"><i class="fa fa-check"></i><b>4.7.4</b> Practice 2</a></li>
<li class="chapter" data-level="4.7.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-3"><i class="fa fa-check"></i><b>4.7.5</b> Practice 3</a></li>
<li class="chapter" data-level="4.7.6" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-4"><i class="fa fa-check"></i><b>4.7.6</b> Practice 4</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-confidence-interval-of-difference"><i class="fa fa-check"></i><b>4.8</b> Exercise: Confidence Interval of Difference"</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-1-1"><i class="fa fa-check"></i><b>4.8.1</b> Example 1</a></li>
<li class="chapter" data-level="4.8.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-2-1"><i class="fa fa-check"></i><b>4.8.2</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-t-test"><i class="fa fa-check"></i><b>4.9</b> Exercise: T-Test</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-1-wheat-fungicide"><i class="fa fa-check"></i><b>4.9.1</b> Case Study 1: Wheat Fungicide</a></li>
<li class="chapter" data-level="4.9.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#t-test-1"><i class="fa fa-check"></i><b>4.9.2</b> T-Test</a></li>
<li class="chapter" data-level="4.9.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-2-apple-variety"><i class="fa fa-check"></i><b>4.9.3</b> Case Study 2: Apple Variety</a></li>
<li class="chapter" data-level="4.9.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-5"><i class="fa fa-check"></i><b>4.9.4</b> Practice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html"><i class="fa fa-check"></i><b>5</b> Understanding Statistical Tests</a>
<ul>
<li class="chapter" data-level="5.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#research-question"><i class="fa fa-check"></i><b>5.1</b> Research Question</a></li>
<li class="chapter" data-level="5.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#the-model"><i class="fa fa-check"></i><b>5.2</b> The Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#treatment-effect"><i class="fa fa-check"></i><b>5.2.1</b> Treatment Effect</a></li>
<li class="chapter" data-level="5.2.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#error-effect"><i class="fa fa-check"></i><b>5.2.2</b> Error Effect</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#hypotheses"><i class="fa fa-check"></i><b>5.3</b> Hypotheses</a></li>
<li class="chapter" data-level="5.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#p-value"><i class="fa fa-check"></i><b>5.4</b> P-Value</a></li>
<li class="chapter" data-level="5.5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#the-p-value-and-errors"><i class="fa fa-check"></i><b>5.5</b> The P-Value and Errors</a></li>
<li class="chapter" data-level="5.6" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#one-sided-vs-two-sided-hypotheses"><i class="fa fa-check"></i><b>5.6</b> One-Sided vs Two-Sided Hypotheses</a></li>
<li class="chapter" data-level="5.7" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#exercise-linear-additive-model"><i class="fa fa-check"></i><b>5.7</b> Exercise: Linear Additive Model</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#case-study-barley-effects"><i class="fa fa-check"></i><b>5.7.1</b> Case Study: Barley Effects</a></li>
<li class="chapter" data-level="5.7.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#plotting-the-effects"><i class="fa fa-check"></i><b>5.7.2</b> Plotting the Effects</a></li>
<li class="chapter" data-level="5.7.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#examining-individual-plots"><i class="fa fa-check"></i><b>5.7.3</b> Examining Individual Plots</a></li>
<li class="chapter" data-level="5.7.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#practice-groudnut"><i class="fa fa-check"></i><b>5.7.4</b> Practice: Groudnut</a></li>
<li class="chapter" data-level="5.7.5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#plotting-the-effects-1"><i class="fa fa-check"></i><b>5.7.5</b> Plotting the Effects</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#exercise-one-sided-hypotheses"><i class="fa fa-check"></i><b>5.8</b> Exercise: One-Sided Hypotheses</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#case-study-groundnut"><i class="fa fa-check"></i><b>5.8.1</b> Case Study: Groundnut</a></li>
<li class="chapter" data-level="5.8.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#one-sided-t-test"><i class="fa fa-check"></i><b>5.8.2</b> One-Sided T-Test</a></li>
<li class="chapter" data-level="5.8.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#practice-barley"><i class="fa fa-check"></i><b>5.8.3</b> Practice: Barley</a></li>
<li class="chapter" data-level="5.8.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#practice-strawberry"><i class="fa fa-check"></i><b>5.8.4</b> Practice: Strawberry</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#exercise-type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>5.9</b> Exercise: Type I and Type II Errors</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html"><i class="fa fa-check"></i><b>6</b> Multiple Treatment Trials</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-4"><i class="fa fa-check"></i><b>6.1</b> Case Study</a></li>
<li class="chapter" data-level="6.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-linear-additive-model"><i class="fa fa-check"></i><b>6.2</b> The Linear Additive Model</a></li>
<li class="chapter" data-level="6.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#analysis-of-variance"><i class="fa fa-check"></i><b>6.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="6.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-f-statistic"><i class="fa fa-check"></i><b>6.4</b> The F statistic</a></li>
<li class="chapter" data-level="6.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-anova-table"><i class="fa fa-check"></i><b>6.5</b> The ANOVA Table</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#source-of-variation"><i class="fa fa-check"></i><b>6.5.1</b> Source of Variation</a></li>
<li class="chapter" data-level="6.5.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#sum-of-squares-1"><i class="fa fa-check"></i><b>6.5.2</b> Sum of Squares</a></li>
<li class="chapter" data-level="6.5.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#degrees-of-freedom-1"><i class="fa fa-check"></i><b>6.5.3</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="6.5.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#mean-square"><i class="fa fa-check"></i><b>6.5.4</b> Mean Square</a></li>
<li class="chapter" data-level="6.5.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#f-value"><i class="fa fa-check"></i><b>6.5.5</b> F-Value</a></li>
<li class="chapter" data-level="6.5.6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#p-value-1"><i class="fa fa-check"></i><b>6.5.6</b> P-value</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#visualizing-how-the-anova-table-relates-to-variance"><i class="fa fa-check"></i><b>6.6</b> Visualizing How the Anova Table Relates to Variance</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-barley"><i class="fa fa-check"></i><b>6.6.1</b> Case Study: Barley</a></li>
<li class="chapter" data-level="6.6.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#anova"><i class="fa fa-check"></i><b>6.6.2</b> ANOVA</a></li>
<li class="chapter" data-level="6.6.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#calculating-the-coefficient-of-variation"><i class="fa fa-check"></i><b>6.6.3</b> Calculating the Coefficient of Variation</a></li>
<li class="chapter" data-level="6.6.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-beet-data"><i class="fa fa-check"></i><b>6.6.4</b> Practice: Beet Data</a></li>
<li class="chapter" data-level="6.6.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-potato-data"><i class="fa fa-check"></i><b>6.6.5</b> Practice: Potato Data</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#exercise-treatment-means"><i class="fa fa-check"></i><b>6.7</b> Exercise: “Treatment Means”</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-barley-1"><i class="fa fa-check"></i><b>6.7.1</b> Case Study: Barley</a></li>
<li class="chapter" data-level="6.7.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#calculating-treatment-means"><i class="fa fa-check"></i><b>6.7.2</b> Calculating Treatment Means</a></li>
<li class="chapter" data-level="6.7.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#plotting-the-means"><i class="fa fa-check"></i><b>6.7.3</b> Plotting the Means</a></li>
<li class="chapter" data-level="6.7.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-beet-data-1"><i class="fa fa-check"></i><b>6.7.4</b> Practice: Beet Data</a></li>
<li class="chapter" data-level="6.7.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-potato-data-1"><i class="fa fa-check"></i><b>6.7.5</b> Practice: Potato Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html"><i class="fa fa-check"></i><b>7</b> Multiple Treatment Designs</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#randomized-complete-block-design"><i class="fa fa-check"></i><b>7.1</b> Randomized Complete Block Design</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-randomized-complete-block-design"><i class="fa fa-check"></i><b>7.1.1</b> Case Study: Randomized Complete Block Design</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#factorial-design"><i class="fa fa-check"></i><b>7.2</b> Factorial Design</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-1-1"><i class="fa fa-check"></i><b>7.2.1</b> Case Study 1</a></li>
<li class="chapter" data-level="7.2.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-2-1"><i class="fa fa-check"></i><b>7.2.2</b> Case Study 2</a></li>
<li class="chapter" data-level="7.2.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#discussing-interactions"><i class="fa fa-check"></i><b>7.2.3</b> Discussing Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#split-plot-design"><i class="fa fa-check"></i><b>7.3</b> Split-Plot Design</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#linear-additive-model-3"><i class="fa fa-check"></i><b>7.4</b> Linear Additive Model</a></li>
<li class="chapter" data-level="7.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#conclusion"><i class="fa fa-check"></i><b>7.5</b> Conclusion</a></li>
<li class="chapter" data-level="7.6" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-randomized-complete-block-design"><i class="fa fa-check"></i><b>7.6</b> Exercise: Randomized Complete Block Design</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-5"><i class="fa fa-check"></i><b>7.6.1</b> Case Study</a></li>
<li class="chapter" data-level="7.6.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#anova-1"><i class="fa fa-check"></i><b>7.6.2</b> ANOVA</a></li>
<li class="chapter" data-level="7.6.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#plotting-the-results"><i class="fa fa-check"></i><b>7.6.3</b> Plotting the Results</a></li>
<li class="chapter" data-level="7.6.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-6"><i class="fa fa-check"></i><b>7.6.4</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-factorial-anova"><i class="fa fa-check"></i><b>7.7</b> Exercise: Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-biochar"><i class="fa fa-check"></i><b>7.7.1</b> Case Study: Biochar</a></li>
<li class="chapter" data-level="7.7.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#anova-2"><i class="fa fa-check"></i><b>7.7.2</b> ANOVA</a></li>
<li class="chapter" data-level="7.7.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#interaction-plots"><i class="fa fa-check"></i><b>7.7.3</b> Interaction Plots</a></li>
<li class="chapter" data-level="7.7.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#testing-factors-individually"><i class="fa fa-check"></i><b>7.7.4</b> Testing Factors Individually</a></li>
<li class="chapter" data-level="7.7.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#bar-plots"><i class="fa fa-check"></i><b>7.7.5</b> Bar Plots</a></li>
<li class="chapter" data-level="7.7.6" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-7"><i class="fa fa-check"></i><b>7.7.6</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-split-plot-design"><i class="fa fa-check"></i><b>7.8</b> Exercise: Split-Plot Design</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-corn-soybean-systems-trial"><i class="fa fa-check"></i><b>7.8.1</b> Case Study: Corn-Soybean Systems Trial</a></li>
<li class="chapter" data-level="7.8.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#anova-4"><i class="fa fa-check"></i><b>7.8.2</b> ANOVA</a></li>
<li class="chapter" data-level="7.8.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#interaction-plot"><i class="fa fa-check"></i><b>7.8.3</b> Interaction Plot</a></li>
<li class="chapter" data-level="7.8.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#bar-plot"><i class="fa fa-check"></i><b>7.8.4</b> Bar plot</a></li>
<li class="chapter" data-level="7.8.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-8"><i class="fa fa-check"></i><b>7.8.5</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-experimental-design"><i class="fa fa-check"></i><b>7.9</b> Exercise: Experimental Design</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#completely-randomized-design"><i class="fa fa-check"></i><b>7.9.1</b> Completely Randomized Design</a></li>
<li class="chapter" data-level="7.9.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#randomized-complete-block-design-1"><i class="fa fa-check"></i><b>7.9.2</b> Randomized Complete Block Design</a></li>
<li class="chapter" data-level="7.9.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#factorial-design-1"><i class="fa fa-check"></i><b>7.9.3</b> Factorial Design</a></li>
<li class="chapter" data-level="7.9.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#split-plot-design-1"><i class="fa fa-check"></i><b>7.9.4</b> Split-Plot Design</a></li>
<li class="chapter" data-level="7.9.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-9"><i class="fa fa-check"></i><b>7.9.5</b> Practice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html"><i class="fa fa-check"></i><b>8</b> Means Separation and Data Presentation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-6"><i class="fa fa-check"></i><b>8.1</b> Case Study</a></li>
<li class="chapter" data-level="8.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#least-significant-difference"><i class="fa fa-check"></i><b>8.2</b> Least Significant Difference</a></li>
<li class="chapter" data-level="8.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#lsd-output-in-r"><i class="fa fa-check"></i><b>8.3</b> LSD Output in R</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#statistics-table"><i class="fa fa-check"></i><b>8.3.1</b> Statistics Table</a></li>
<li class="chapter" data-level="8.3.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-table"><i class="fa fa-check"></i><b>8.3.2</b> Means Table</a></li>
<li class="chapter" data-level="8.3.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#groups-table"><i class="fa fa-check"></i><b>8.3.3</b> Groups Table</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#comparisonwise-versus-experimentwise-error"><i class="fa fa-check"></i><b>8.4</b> Comparisonwise versus Experimentwise Error</a></li>
<li class="chapter" data-level="8.5" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#tukeys-honest-significant-difference"><i class="fa fa-check"></i><b>8.5</b> Tukey’s Honest Significant Difference</a></li>
<li class="chapter" data-level="8.6" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#linear-contrast"><i class="fa fa-check"></i><b>8.6</b> Linear Contrast</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#coefficients"><i class="fa fa-check"></i><b>8.6.1</b> Coefficients</a></li>
<li class="chapter" data-level="8.6.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#linear-contrasts-with-r"><i class="fa fa-check"></i><b>8.6.2</b> Linear Contrasts with R</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-presentation"><i class="fa fa-check"></i><b>8.7</b> Means Presentation</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-tables"><i class="fa fa-check"></i><b>8.7.1</b> Means Tables</a></li>
<li class="chapter" data-level="8.7.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#plotting-means"><i class="fa fa-check"></i><b>8.7.2</b> Plotting Means</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#exercise-lsd-and-tukeys-hsd"><i class="fa fa-check"></i><b>8.8</b> Exercise: LSD and Tukey’s HSD</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-common-bean"><i class="fa fa-check"></i><b>8.8.1</b> Case Study: Common Bean</a></li>
<li class="chapter" data-level="8.8.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#least-significant-difference-1"><i class="fa fa-check"></i><b>8.8.2</b> Least Significant Difference</a></li>
<li class="chapter" data-level="8.8.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#tukey-hsd"><i class="fa fa-check"></i><b>8.8.3</b> Tukey HSD</a></li>
<li class="chapter" data-level="8.8.4" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-apple"><i class="fa fa-check"></i><b>8.8.4</b> Practice: Apple</a></li>
<li class="chapter" data-level="8.8.5" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-wheat-treatment-with-mildew"><i class="fa fa-check"></i><b>8.8.5</b> Practice: Wheat Treatment with Mildew</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#exercise-linear-contrasts"><i class="fa fa-check"></i><b>8.9</b> Exercise: Linear Contrasts</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-winter-canola-cultivar-trial."><i class="fa fa-check"></i><b>8.9.1</b> Case Study: Winter Canola Cultivar Trial.</a></li>
<li class="chapter" data-level="8.9.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#running-the-contrast"><i class="fa fa-check"></i><b>8.9.2</b> Running the Contrast</a></li>
<li class="chapter" data-level="8.9.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-corn-nitrogen-source-and-timing"><i class="fa fa-check"></i><b>8.9.3</b> Practice: Corn Nitrogen Source and Timing</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#exercise-means-tables"><i class="fa fa-check"></i><b>8.10</b> Exercise: Means Tables</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-corn-nitrogen-source-and-timing"><i class="fa fa-check"></i><b>8.10.1</b> Case Study: Corn Nitrogen Source and Timing</a></li>
<li class="chapter" data-level="8.10.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-canola"><i class="fa fa-check"></i><b>8.10.2</b> Practice: Canola</a></li>
<li class="chapter" data-level="8.10.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-broccoli-lsd"><i class="fa fa-check"></i><b>8.10.3</b> Practice: Broccoli LSD</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html"><i class="fa fa-check"></i><b>9</b> Messy and Missing Data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#inspecting-data-for-normal-distributions"><i class="fa fa-check"></i><b>9.1</b> Inspecting data for Normal Distributions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#histograms-1"><i class="fa fa-check"></i><b>9.1.1</b> Histograms</a></li>
<li class="chapter" data-level="9.1.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#rank-percentile-plots"><i class="fa fa-check"></i><b>9.1.2</b> Rank Percentile Plots</a></li>
<li class="chapter" data-level="9.1.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#box-plots"><i class="fa fa-check"></i><b>9.1.3</b> Box Plots</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#inspecting-data-for-equal-variances"><i class="fa fa-check"></i><b>9.2</b> Inspecting Data for Equal Variances</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#mean-variance-plot"><i class="fa fa-check"></i><b>9.2.1</b> Mean-Variance Plot</a></li>
<li class="chapter" data-level="9.2.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#homogeneity-of-variance-tests"><i class="fa fa-check"></i><b>9.2.2</b> Homogeneity of Variance Tests</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#dealing-with-messy-data"><i class="fa fa-check"></i><b>9.3</b> Dealing with Messy Data</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#outliers"><i class="fa fa-check"></i><b>9.3.1</b> Outliers</a></li>
<li class="chapter" data-level="9.3.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#non-normal-data-and-unequal-variances"><i class="fa fa-check"></i><b>9.3.2</b> Non-normal Data and Unequal Variances</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>9.4</b> Dealing with Missing Data</a></li>
<li class="chapter" data-level="9.5" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#summary"><i class="fa fa-check"></i><b>9.5</b> Summary</a></li>
<li class="chapter" data-level="9.6" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-visual-data-inspection"><i class="fa fa-check"></i><b>9.6</b> Exercise: Visual Data Inspection</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-1-2"><i class="fa fa-check"></i><b>9.6.1</b> Case Study 1</a></li>
<li class="chapter" data-level="9.6.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#histogram"><i class="fa fa-check"></i><b>9.6.2</b> Histogram</a></li>
<li class="chapter" data-level="9.6.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#rank-percentile"><i class="fa fa-check"></i><b>9.6.3</b> Rank-Percentile</a></li>
<li class="chapter" data-level="9.6.4" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-2-2"><i class="fa fa-check"></i><b>9.6.4</b> Case Study 2</a></li>
<li class="chapter" data-level="9.6.5" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#box-plot"><i class="fa fa-check"></i><b>9.6.5</b> Box Plot</a></li>
<li class="chapter" data-level="9.6.6" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-10"><i class="fa fa-check"></i><b>9.6.6</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-identifying-unequal-variances"><i class="fa fa-check"></i><b>9.7</b> Exercise: Identifying Unequal Variances"</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-grape-colapsis-in-seed-corn"><i class="fa fa-check"></i><b>9.7.1</b> Case Study: Grape Colapsis in Seed Corn</a></li>
<li class="chapter" data-level="9.7.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-pigweed-height"><i class="fa fa-check"></i><b>9.7.2</b> Practice: Pigweed Height</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-transforming-and-analyzing-data"><i class="fa fa-check"></i><b>9.8</b> Exercise: Transforming and Analyzing Data</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-grape-colapsis-in-seed-corn-1"><i class="fa fa-check"></i><b>9.8.1</b> Case Study: Grape Colapsis in Seed Corn</a></li>
<li class="chapter" data-level="9.8.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-pigweed-height-1"><i class="fa fa-check"></i><b>9.8.2</b> Practice: Pigweed Height</a></li>
<li class="chapter" data-level="9.8.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-pigweed-biomass"><i class="fa fa-check"></i><b>9.8.3</b> Practice: Pigweed Biomass</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-imputing-missing-data"><i class="fa fa-check"></i><b>9.9</b> Exercise: Imputing Missing Data</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-wheat-genotype-trial"><i class="fa fa-check"></i><b>9.9.1</b> Case Study: Wheat Genotype Trial</a></li>
<li class="chapter" data-level="9.9.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-1-2"><i class="fa fa-check"></i><b>9.9.2</b> Practice 1</a></li>
<li class="chapter" data-level="9.9.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-2-1"><i class="fa fa-check"></i><b>9.9.3</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html"><i class="fa fa-check"></i><b>10</b> Correlation and Simple Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#correlation"><i class="fa fa-check"></i><b>10.1</b> Correlation</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-cucumber"><i class="fa fa-check"></i><b>10.1.1</b> Case Study: Cucumber</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#correlation-1"><i class="fa fa-check"></i><b>10.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#how-is-r-calcuated-optional-reading"><i class="fa fa-check"></i><b>10.2.1</b> How Is r Calcuated (optional reading)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#regression"><i class="fa fa-check"></i><b>10.3</b> Regression</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-7"><i class="fa fa-check"></i><b>10.3.1</b> Case Study</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#linear-equation"><i class="fa fa-check"></i><b>10.3.2</b> Linear Equation</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#calculating-the-regression-equation"><i class="fa fa-check"></i><b>10.3.3</b> Calculating the Regression Equation</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#least-squares-estimate"><i class="fa fa-check"></i><b>10.3.4</b> Least-Squares Estimate</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#significance-of-coefficients"><i class="fa fa-check"></i><b>10.3.5</b> Significance of Coefficients</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#analysis-of-variance-6"><i class="fa fa-check"></i><b>10.3.6</b> Analysis of Variance</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#measuring-model-fit-with-r-square"><i class="fa fa-check"></i><b>10.3.7</b> Measuring Model Fit with R-Square</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#checking-whether-the-linear-model-is-appropriate"><i class="fa fa-check"></i><b>10.3.8</b> Checking whether the Linear Model is Appropriate</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#extrapolation"><i class="fa fa-check"></i><b>10.4</b> Extrapolation</a></li>
<li class="chapter" data-level="10.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#exercise-sccatterplots-and-regression"><i class="fa fa-check"></i><b>10.5</b> Exercise: Sccatterplots and Regression</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-corn-data"><i class="fa fa-check"></i><b>10.5.1</b> Case Study: Corn Data</a></li>
<li class="chapter" data-level="10.5.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-1-3"><i class="fa fa-check"></i><b>10.5.2</b> Practice 1</a></li>
<li class="chapter" data-level="10.5.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-2-2"><i class="fa fa-check"></i><b>10.5.3</b> Practice 2</a></li>
<li class="chapter" data-level="10.5.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-3-1"><i class="fa fa-check"></i><b>10.5.4</b> Practice 3</a></li>
<li class="chapter" data-level="10.5.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-4-1"><i class="fa fa-check"></i><b>10.5.5</b> Practice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#exercise-simple-linear-regression"><i class="fa fa-check"></i><b>10.6</b> Exercise: Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-corn-allometry"><i class="fa fa-check"></i><b>10.6.1</b> Case Study: Corn Allometry</a></li>
<li class="chapter" data-level="10.6.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#fitting-the-regression-model"><i class="fa fa-check"></i><b>10.6.2</b> Fitting the regression model</a></li>
<li class="chapter" data-level="10.6.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#examining-the-residuals"><i class="fa fa-check"></i><b>10.6.3</b> Examining the residuals</a></li>
<li class="chapter" data-level="10.6.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#viewing-the-model-coefficients"><i class="fa fa-check"></i><b>10.6.4</b> Viewing the Model Coefficients</a></li>
<li class="chapter" data-level="10.6.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#more-measures-of-model-fit"><i class="fa fa-check"></i><b>10.6.5</b> More measures of model fit</a></li>
<li class="chapter" data-level="10.6.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-1-4"><i class="fa fa-check"></i><b>10.6.6</b> Practice 1</a></li>
<li class="chapter" data-level="10.6.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-2-3"><i class="fa fa-check"></i><b>10.6.7</b> Practice 2</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#exercise-making-predictions-from-regression-models."><i class="fa fa-check"></i><b>10.7</b> Exercise: Making Predictions from Regression Models.</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-8"><i class="fa fa-check"></i><b>10.7.1</b> Case Study</a></li>
<li class="chapter" data-level="10.7.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#creating-and-testing-our-model"><i class="fa fa-check"></i><b>10.7.2</b> Creating and Testing our Model</a></li>
<li class="chapter" data-level="10.7.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#visualizing-the-regression-model"><i class="fa fa-check"></i><b>10.7.3</b> Visualizing the Regression Model</a></li>
<li class="chapter" data-level="10.7.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#making-predictions-with-the-regression-model"><i class="fa fa-check"></i><b>10.7.4</b> Making Predictions with the Regression Model</a></li>
<li class="chapter" data-level="10.7.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-1-5"><i class="fa fa-check"></i><b>10.7.5</b> Practice 1</a></li>
<li class="chapter" data-level="10.7.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-2-4"><i class="fa fa-check"></i><b>10.7.6</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html"><i class="fa fa-check"></i><b>11</b> Nonlinear Relationships and Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#multiplie-linear-regression"><i class="fa fa-check"></i><b>11.1</b> Multiplie Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-modelling-yield-by-county"><i class="fa fa-check"></i><b>11.1.1</b> Case Study: Modelling Yield by County</a></li>
<li class="chapter" data-level="11.1.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#beware-of-bloated-models"><i class="fa fa-check"></i><b>11.1.2</b> Beware of Bloated Models</a></li>
<li class="chapter" data-level="11.1.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#methods-for-avoiding-bloated-models"><i class="fa fa-check"></i><b>11.1.3</b> Methods for Avoiding Bloated Models</a></li>
<li class="chapter" data-level="11.1.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#tunning-and-comparing-models"><i class="fa fa-check"></i><b>11.1.4</b> Tunning and Comparing Models</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#nonlinear-relationships"><i class="fa fa-check"></i><b>11.2</b> Nonlinear Relationships</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-nonlinear-responses-with-linear-regression"><i class="fa fa-check"></i><b>11.2.1</b> Fitting Nonlinear Responses with Linear Regression</a></li>
<li class="chapter" data-level="11.2.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-nonlinear-responses-with-nonlinear-regression"><i class="fa fa-check"></i><b>11.2.2</b> Fitting Nonlinear Responses with Nonlinear Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#summary-1"><i class="fa fa-check"></i><b>11.3</b> Summary</a></li>
<li class="chapter" data-level="11.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-multiple-linear-regression"><i class="fa fa-check"></i><b>11.4</b> Exercise: Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-country-corn-yields"><i class="fa fa-check"></i><b>11.4.1</b> Case Study: Country Corn Yields</a></li>
<li class="chapter" data-level="11.4.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-the-model"><i class="fa fa-check"></i><b>11.4.2</b> Fitting the Model</a></li>
<li class="chapter" data-level="11.4.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#inspecting-the-model"><i class="fa fa-check"></i><b>11.4.3</b> Inspecting the Model</a></li>
<li class="chapter" data-level="11.4.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-thompson-corn-data"><i class="fa fa-check"></i><b>11.4.4</b> Practice: Thompson Corn Data</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-avoiding-bloated-models"><i class="fa fa-check"></i><b>11.5</b> Exercise: Avoiding Bloated Models</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-9"><i class="fa fa-check"></i><b>11.5.1</b> Case Study</a></li>
<li class="chapter" data-level="11.5.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#covariance-matrix"><i class="fa fa-check"></i><b>11.5.2</b> Covariance Matrix</a></li>
<li class="chapter" data-level="11.5.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#partial-correlation-1"><i class="fa fa-check"></i><b>11.5.3</b> Partial Correlation</a></li>
<li class="chapter" data-level="11.5.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cross-validation-1"><i class="fa fa-check"></i><b>11.5.4</b> Cross-Validation</a></li>
<li class="chapter" data-level="11.5.5" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-thompson-corn-data-1"><i class="fa fa-check"></i><b>11.5.5</b> Practice: Thompson Corn Data</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-tuning-the-model"><i class="fa fa-check"></i><b>11.6</b> Exercise: Tuning the Model</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-10"><i class="fa fa-check"></i><b>11.6.1</b> Case Study</a></li>
<li class="chapter" data-level="11.6.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#tuning-the-model"><i class="fa fa-check"></i><b>11.6.2</b> Tuning the Model</a></li>
<li class="chapter" data-level="11.6.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-11"><i class="fa fa-check"></i><b>11.6.3</b> Practice</a></li>
<li class="chapter" data-level="11.6.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-12"><i class="fa fa-check"></i><b>11.6.4</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-nonlinear-regression"><i class="fa fa-check"></i><b>11.7</b> Exercise: Nonlinear Regression</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-1-monomolecular-data"><i class="fa fa-check"></i><b>11.7.1</b> Case Study 1: Monomolecular Data</a></li>
<li class="chapter" data-level="11.7.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-2-logistic-data"><i class="fa fa-check"></i><b>11.7.2</b> Case Study 2: Logistic Data</a></li>
<li class="chapter" data-level="11.7.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-1-6"><i class="fa fa-check"></i><b>11.7.3</b> Practice 1</a></li>
<li class="chapter" data-level="11.7.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-2-5"><i class="fa fa-check"></i><b>11.7.4</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="spatial-statistics.html"><a href="spatial-statistics.html"><i class="fa fa-check"></i><b>12</b> Spatial Statistics</a>
<ul>
<li class="chapter" data-level="12.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#projection-general"><i class="fa fa-check"></i><b>12.1</b> Projection (General)</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#wgs-84-epsg-4236"><i class="fa fa-check"></i><b>12.1.1</b> WGS 84 (EPSG: 4236)</a></li>
<li class="chapter" data-level="12.1.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#mercator-epsg-3857"><i class="fa fa-check"></i><b>12.1.2</b> Mercator (EPSG: 3857)</a></li>
<li class="chapter" data-level="12.1.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#us-national-atlas-equal-area-epsg-2163"><i class="fa fa-check"></i><b>12.1.3</b> US National Atlas Equal Area (EPSG: 2163)</a></li>
<li class="chapter" data-level="12.1.4" data-path="spatial-statistics.html"><a href="spatial-statistics.html#utm-zone-11n-epsg-2955"><i class="fa fa-check"></i><b>12.1.4</b> UTM Zone 11N (EPSG: 2955)</a></li>
<li class="chapter" data-level="12.1.5" data-path="spatial-statistics.html"><a href="spatial-statistics.html#projection-summary"><i class="fa fa-check"></i><b>12.1.5</b> Projection Summary</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#shape-files"><i class="fa fa-check"></i><b>12.2</b> Shape Files</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-soybean-yield-in-iowa"><i class="fa fa-check"></i><b>12.2.1</b> Case Study: Soybean Yield in Iowa</a></li>
<li class="chapter" data-level="12.2.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#ssurgo"><i class="fa fa-check"></i><b>12.2.2</b> SSURGO</a></li>
<li class="chapter" data-level="12.2.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#operations-with-shapes"><i class="fa fa-check"></i><b>12.2.3</b> Operations with Shapes</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#rasters"><i class="fa fa-check"></i><b>12.3</b> Rasters</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#interpolation"><i class="fa fa-check"></i><b>12.3.1</b> Interpolation</a></li>
<li class="chapter" data-level="12.3.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#kriging"><i class="fa fa-check"></i><b>12.3.2</b> Kriging</a></li>
<li class="chapter" data-level="12.3.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#operations-on-kriged-data"><i class="fa fa-check"></i><b>12.3.3</b> Operations on Kriged Data</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="spatial-statistics.html"><a href="spatial-statistics.html#exercise-shape-files"><i class="fa fa-check"></i><b>12.4</b> Exercise: Shape Files</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-11"><i class="fa fa-check"></i><b>12.4.1</b> Case Study</a></li>
<li class="chapter" data-level="12.4.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#practice-13"><i class="fa fa-check"></i><b>12.4.2</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="spatial-statistics.html"><a href="spatial-statistics.html#exercise-ssurgo"><i class="fa fa-check"></i><b>12.5</b> Exercise: SSURGO</a></li>
<li class="chapter" data-level="12.6" data-path="spatial-statistics.html"><a href="spatial-statistics.html#exercise-rasters"><i class="fa fa-check"></i><b>12.6</b> Exercise: Rasters</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-soil-test-data"><i class="fa fa-check"></i><b>12.6.1</b> Case Study: Soil Test Data</a></li>
<li class="chapter" data-level="12.6.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#practice-1-7"><i class="fa fa-check"></i><b>12.6.2</b> Practice 1</a></li>
<li class="chapter" data-level="12.6.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#practice-2-6"><i class="fa fa-check"></i><b>12.6.3</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>13</b> Machine Learning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="machine-learning.html"><a href="machine-learning.html#machine-learning-1"><i class="fa fa-check"></i><b>13.1</b> Machine Learning</a></li>
<li class="chapter" data-level="13.2" data-path="machine-learning.html"><a href="machine-learning.html#cluster-analyses"><i class="fa fa-check"></i><b>13.2</b> Cluster Analyses</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="machine-learning.html"><a href="machine-learning.html#case-study-grouping-midwestern-environments"><i class="fa fa-check"></i><b>13.2.1</b> Case Study: Grouping Midwestern Environments</a></li>
<li class="chapter" data-level="13.2.2" data-path="machine-learning.html"><a href="machine-learning.html#scaling"><i class="fa fa-check"></i><b>13.2.2</b> Scaling</a></li>
<li class="chapter" data-level="13.2.3" data-path="machine-learning.html"><a href="machine-learning.html#clustering-animation"><i class="fa fa-check"></i><b>13.2.3</b> Clustering Animation</a></li>
<li class="chapter" data-level="13.2.4" data-path="machine-learning.html"><a href="machine-learning.html#county-cluster-analysis"><i class="fa fa-check"></i><b>13.2.4</b> County Cluster Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="machine-learning.html"><a href="machine-learning.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>13.3</b> k-Nearest-Neighbors</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="machine-learning.html"><a href="machine-learning.html#case-study-guessing-county-yields-based-on-environmental-similarity"><i class="fa fa-check"></i><b>13.3.1</b> Case Study: Guessing County Yields based on Environmental Similarity</a></li>
<li class="chapter" data-level="13.3.2" data-path="machine-learning.html"><a href="machine-learning.html#scaling-1"><i class="fa fa-check"></i><b>13.3.2</b> Scaling</a></li>
<li class="chapter" data-level="13.3.3" data-path="machine-learning.html"><a href="machine-learning.html#k-nearest-neighbor-animation"><i class="fa fa-check"></i><b>13.3.3</b> k-Nearest-Neighbor Animation</a></li>
<li class="chapter" data-level="13.3.4" data-path="machine-learning.html"><a href="machine-learning.html#choosing-k"><i class="fa fa-check"></i><b>13.3.4</b> Choosing <span class="math inline">\(k\)</span></a></li>
<li class="chapter" data-level="13.3.5" data-path="machine-learning.html"><a href="machine-learning.html#model-cross-validation"><i class="fa fa-check"></i><b>13.3.5</b> Model Cross-Validation</a></li>
<li class="chapter" data-level="13.3.6" data-path="machine-learning.html"><a href="machine-learning.html#yield-prediction-with-nearest-neighbor-analysis"><i class="fa fa-check"></i><b>13.3.6</b> Yield Prediction with Nearest Neighbor Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="machine-learning.html"><a href="machine-learning.html#classification-trees"><i class="fa fa-check"></i><b>13.4</b> Classification Trees</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="machine-learning.html"><a href="machine-learning.html#features"><i class="fa fa-check"></i><b>13.4.1</b> Features</a></li>
<li class="chapter" data-level="13.4.2" data-path="machine-learning.html"><a href="machine-learning.html#quantitative-categorical-data"><i class="fa fa-check"></i><b>13.4.2</b> Quantitative (Categorical) Data</a></li>
<li class="chapter" data-level="13.4.3" data-path="machine-learning.html"><a href="machine-learning.html#quanatitiative-continuous-data"><i class="fa fa-check"></i><b>13.4.3</b> Quanatitiative (Continuous) Data</a></li>
<li class="chapter" data-level="13.4.4" data-path="machine-learning.html"><a href="machine-learning.html#overfitting-1"><i class="fa fa-check"></i><b>13.4.4</b> Overfitting</a></li>
<li class="chapter" data-level="13.4.5" data-path="machine-learning.html"><a href="machine-learning.html#cross-validation-2"><i class="fa fa-check"></i><b>13.4.5</b> Cross Validation</a></li>
<li class="chapter" data-level="13.4.6" data-path="machine-learning.html"><a href="machine-learning.html#random-forest"><i class="fa fa-check"></i><b>13.4.6</b> Random Forest</a></li>
<li class="chapter" data-level="13.4.7" data-path="machine-learning.html"><a href="machine-learning.html#feature-importance"><i class="fa fa-check"></i><b>13.4.7</b> Feature Importance</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="machine-learning.html"><a href="machine-learning.html#summary-2"><i class="fa fa-check"></i><b>13.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html"><i class="fa fa-check"></i><b>14</b> Putting it all Together</a>
<ul>
<li class="chapter" data-level="14.1" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-1-yield-map-population-summary-and-z-distribution"><i class="fa fa-check"></i><b>14.1</b> Scenario 1: Yield Map (Population Summary and Z-Distribution)</a></li>
<li class="chapter" data-level="14.2" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-2-yield-estimate-sampling-t-distribution"><i class="fa fa-check"></i><b>14.2</b> Scenario 2: Yield Estimate (Sampling t-Distribution)</a></li>
<li class="chapter" data-level="14.3" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-3-side-by-side-t-test"><i class="fa fa-check"></i><b>14.3</b> Scenario 3: Side-By-Side (t-Test)</a></li>
<li class="chapter" data-level="14.4" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-4-fungicide-trial-anova-crd-or-rcbd"><i class="fa fa-check"></i><b>14.4</b> Scenario 4: Fungicide Trial (ANOVA CRD or RCBD)</a></li>
<li class="chapter" data-level="14.5" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-5-hybrid-response-to-fungicide-trial-anova-factorial-or-split-plot"><i class="fa fa-check"></i><b>14.5</b> Scenario 5: Hybrid Response to Fungicide Trial (ANOVA Factorial or Split Plot)</a></li>
<li class="chapter" data-level="14.6" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-6-foliar-rate-response-trial-linear-or-non-linear-regression"><i class="fa fa-check"></i><b>14.6</b> Scenario 6: Foliar Rate-Response Trial (Linear or Non-Linear Regression)</a></li>
<li class="chapter" data-level="14.7" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-7-application-map-shapefiles-and-rasters"><i class="fa fa-check"></i><b>14.7</b> Scenario 7: Application Map (Shapefiles and Rasters)</a></li>
<li class="chapter" data-level="14.8" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-8-yield-prediction-multiple-linear-regression-and-other-predictive-models"><i class="fa fa-check"></i><b>14.8</b> Scenario 8: Yield Prediction (Multiple Linear Regression and other Predictive Models)</a></li>
<li class="chapter" data-level="14.9" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#summary-3"><i class="fa fa-check"></i><b>14.9</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for Agricultural Professionals</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="population-statistics" class="section level1" number="1">
<h1><span class="header-section-number">Chapter 1</span> Population Statistics</h1>
<div id="populations" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Populations</h2>
<p>Almost every statistics text begins with the concept of a
<strong>population</strong>. A population is the complete set of individuals to which
you want to predict values. Let’s dwell on this concept, as it is
something that did not hit home for me right away in my career. Again,
the population is all of the individuals for which you are interested in
making a prediction. What do we mean by individuals? Not just people –
individuals can plants, insects, disease, livestock or, indeed, farmers.</p>
<p>Just as important as what individuals are in a population is its extent.
What do you want the individuals to represent? If you are a farmer, do
you want to apply the data from these individuals directly to
themselves, or will you use them to make management decisions for the
entire field, or all the fields in your farm? Will you use the results
this season or to make predictions for future seasons? If you are an
animal nutritionist, will you use rations data to support dairy
Herefords, or beef Angus?</p>
<p>If you are a sales agronomist, will you use the data to support sales on
one farm, a group of farms in one area, or across your entire sales
territory? If you are in Extension, will the individuals you measure be
applicable to your entire county, group of counties, or state? If you
are in industry like me, will your results be applicable to several
states?</p>
<p>This is a very, very critical question, as you design experiments – or
as you read research conducted by others. To what do or will the results
apply? Obviously, an Iowa farmer should not follow the optimum planting
date determined for a grower in North Carolina, nor should an Ohio
farmer assume our pale clays will be as forgiving as the dark, mellow
loam of southern Minnesota.</p>
<p>Drilling down, you might further consider whether research was conducted
in areas that have similar temperature or rainfall, how different the
soil texture might be to the areas to which you want to apply results.
At the farm level, you might ask how similar the crop rotation, tillage,
or planting methods were to that operation. At the field level, you
might wonder about planting date or the hybrid that was sown.</p>
<p>When you use the results from set of individuals to make predictions
about other individuals, you are making inferences – you are using
those data to make predictions, whether it be for that same field next
month or next year, or for other locations (areas in a field, fields in
a farm, counties, or states). When we speak of an inference space, then,
that is the total group of individuals to which you will apply your
results. Or, in another word, your population.</p>
<p>In summary, one of the most critical skills you can apply with data
science has no formula and, indeed, little to do with math (at least in
our application). It is to ask yourself, will my experiment represent
the entire population in which I am interested? Indeed, one field trial
likely will not address the entire population in which you are
interested – it is up to you to determine the population to which you
are comfortable applying those results.</p>
<p>In fact, statistics or data science done without this “domain” knowledge
whether a dataset is useful or experimental results are reasonable can
be disastrous. Just because a model fits one dataset very well or
treatments are significantly different does not mean they should be used
to make decisions. Your competency as an agronomic data scientist
depends on everything you learn in your program of study. Soil science,
crop physiology, and integrated pest management, to name just a few
subjects, are as much a prerequisite as any math course you have taken.</p>
<p>In some cases all of the individuals in a population can be measured –
in such case, we will use the basic statistics described in this unit.
The yield map we will analyze in this unit is a loose example of a case
where we can measure</p>
<p>In most cases, however, it is not physically or financially feasible to
measure all individuals in a population. In that case, subsets of the
population, called samples, are used to estimate the range of
individuals in a population.</p>
</div>
<div id="case-study-yield-map" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Case Study: Yield Map</h2>
<p>For our first case study, we will use a situation where every individual
in our population can be measured: a single soybean field in central
Iowa. In this case, yield data were gathered using a combine monitor. In
case you don’t live and breathe field crops like me, combines (the
machines that harvest grain) are usually equipped with a scale that
repeatedly weighs grain as the combine moves across the field. The
moisture of the grain is also recorded. These data are combined with
measures of the combine speed and knowledge of the number of rows
harvested at once to calculate the yield per area of grain, adjusted to
the market standard for grain moisture.</p>
<p>Almost all of you have seen a yield map somewhat like the one below. In
this map, blue circles represent lower yields, while yellow and orange
circles represent higher yields.</p>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>We will learn in the Exercises portion of this lesson how to create a
map like this using just a few lines of code.</p>
<p>Each dataset has a structure – the way data are organized in columns
and rows. To get a sense of the structure of our soybean dataset, we can
examine the first 6 rows of the dataset using R.</p>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
DISTANCE
</th>
<th style="text-align:right;">
SWATHWIDTH
</th>
<th style="text-align:right;">
VRYIELDVOL
</th>
<th style="text-align:right;">
Crop
</th>
<th style="text-align:right;">
WetMass
</th>
<th style="text-align:right;">
Moisture
</th>
<th style="text-align:left;">
Time
</th>
<th style="text-align:right;">
Heading
</th>
<th style="text-align:left;">
VARIETY
</th>
<th style="text-align:right;">
Elevation
</th>
<th style="text-align:left;">
IsoTime
</th>
<th style="text-align:right;">
yield_bu
</th>
<th style="text-align:left;">
geometry
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.9202733
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
57.38461
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
3443.652
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:left;">
9/19/2016 4:45:46 PM
</td>
<td style="text-align:right;">
300.1584
</td>
<td style="text-align:left;">
23A42
</td>
<td style="text-align:right;">
786.8470
</td>
<td style="text-align:left;">
2016-09-19T16:45:46.001Z
</td>
<td style="text-align:right;">
65.97034
</td>
<td style="text-align:left;">
POINT (-93.15026 41.66641)
</td>
</tr>
<tr>
<td style="text-align:right;">
2.6919269
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
55.88097
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
3353.411
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:left;">
9/19/2016 4:45:48 PM
</td>
<td style="text-align:right;">
303.6084
</td>
<td style="text-align:left;">
23A42
</td>
<td style="text-align:right;">
786.6140
</td>
<td style="text-align:left;">
2016-09-19T16:45:48.004Z
</td>
<td style="text-align:right;">
64.24158
</td>
<td style="text-align:left;">
POINT (-93.15028 41.66641)
</td>
</tr>
<tr>
<td style="text-align:right;">
2.6263101
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
80.83788
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
4851.075
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:left;">
9/19/2016 4:45:49 PM
</td>
<td style="text-align:right;">
304.3084
</td>
<td style="text-align:left;">
23A42
</td>
<td style="text-align:right;">
786.1416
</td>
<td style="text-align:left;">
2016-09-19T16:45:49.007Z
</td>
<td style="text-align:right;">
92.93246
</td>
<td style="text-align:left;">
POINT (-93.15028 41.66642)
</td>
</tr>
<tr>
<td style="text-align:right;">
2.7575437
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
71.76773
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
4306.777
</td>
<td style="text-align:right;">
6.22
</td>
<td style="text-align:left;">
9/19/2016 4:45:51 PM
</td>
<td style="text-align:right;">
306.2084
</td>
<td style="text-align:left;">
23A42
</td>
<td style="text-align:right;">
785.7381
</td>
<td style="text-align:left;">
2016-09-19T16:45:51.002Z
</td>
<td style="text-align:right;">
77.37348
</td>
<td style="text-align:left;">
POINT (-93.1503 41.66642)
</td>
</tr>
<tr>
<td style="text-align:right;">
2.3966513
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
91.03274
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
5462.851
</td>
<td style="text-align:right;">
12.22
</td>
<td style="text-align:left;">
9/19/2016 4:45:54 PM
</td>
<td style="text-align:right;">
309.2284
</td>
<td style="text-align:left;">
23A42
</td>
<td style="text-align:right;">
785.5937
</td>
<td style="text-align:left;">
2016-09-19T16:45:54.002Z
</td>
<td style="text-align:right;">
91.86380
</td>
<td style="text-align:left;">
POINT (-93.15032 41.66644)
</td>
</tr>
<tr>
<td style="text-align:right;">
3.1840529
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
65.59037
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
3951.056
</td>
<td style="text-align:right;">
13.33
</td>
<td style="text-align:left;">
9/19/2016 4:45:55 PM
</td>
<td style="text-align:right;">
309.7584
</td>
<td style="text-align:left;">
23A42
</td>
<td style="text-align:right;">
785.7512
</td>
<td style="text-align:left;">
2016-09-19T16:45:55.005Z
</td>
<td style="text-align:right;">
65.60115
</td>
<td style="text-align:left;">
POINT (-93.15033 41.66644)
</td>
</tr>
</tbody>
</table>
<p>Each row in the above dataset is a <strong>case</strong>, sometimes called an
<strong>instance</strong>. It is an single observation taken within a soybean field.
That case may contain one or more <strong>variables</strong>: specific measurements
or observations recorded for each case. In the dataset above, variables
include <em>DISTANCE</em>, <em>SWATHWIDTH</em>, <em>VRYIELDVOL</em>, <em>Crop</em>, <em>WetMass</em>, and
many others.</p>
<p>The two most important to us in this lesson are <em>yield_bu</em> and
<em>geometry</em>. That this dataset has a column named geometry indicates it
is a special kind of dataset called a <strong>shape file</strong> – a dataset in
which the measures are geo-referenced. That is, we know where on Earth
these measurements were taken. The geometry column in this case
identifies a point with each observation.</p>
</div>
<div id="distributions" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Distributions</h2>
<p>At this point, we have two options any time we want to know about
soybean yield in this field. We can pull out this map or the complete
dataset (which has over 6,500 observations) and look at try to
intuitively understand the data. Or we can use statistics which, in a
sense, provide us a formula for approximating the values in our dataset
with just a few numbers.</p>
<p>A <strong>distribution</strong> describes the range of values that occur within a
given variable. What is the range of values in our measured values? In
this example, what are the highest and lowest yields we observed? What
ranges of values occur more frequently? Many times, we want to see
whether the distribution of one</p>
<div id="histograms" class="section level3" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Histograms</h3>
<p>Before we get into the math required to generate these statistics,
however, we should look at the shape of our data. What is the range of
values in our measured values? In this example, what are the highest and
lowest yields we observed? What ranges of values occur more frequently?
Do the observed values make general sense?</p>
<p>One of the easiest and most informative things for us to do is to create
a particular bar chart known as a <strong>histogram</strong>.</p>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>In the histogram above, each bar represents range of values. This range
is often referred to as a <em>bin</em>. The lowest bin includes values from 50
to 59.0000. The next bin includes values from 60 to 69.9999. And so on.
The height of each bar represents the <strong>frequency</strong> within each range:
the number of individuals in that population that have values within
that range.</p>
<p>Each bin can also be defined by its <strong>midpoint</strong>. The midpoint is the
middle value in each range. For the bin that includes values from 50 to
50.9999, the midpoint is 55. For the bin that includes values from 60 to
60.9999, the midpoint is 65.</p>
<p>In the plot above, the midpoint for each bar is indicated by the orange
bar beneath it.</p>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>There are many ways in which we can draw a histogram – and other
visualizations – in R. We will learn more in this course about an R
package called <code>ggplot2</code>, which can create just about any plot you might
imagine. Here is a simple taste:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="population-statistics.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>yield, <span class="fu">aes</span>(<span class="at">x=</span>yield_bu)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="population-statistics.html#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">50</span>, <span class="dv">110</span>, <span class="dv">10</span>), <span class="at">fill=</span><span class="st">&quot;tomato&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Varying the <em>bin width</em> provides us with different perspectives on our
distribution. Wide bins, which each include a greater range of values,
will provide more gross representations of the data, while narrower bins
will provide greater detail. When bins are too narrow, however, there
may be gaps in our histogram where no values occur within particular
bins.</p>
<p>Throughout this course, I have created interactive exercises to help you
better visualize statistical concepts. Often, they will allow you to
observe how changing the variables or the number of observations can
affect a statistical test or visualization.</p>
<p>These exercises are located outside of this textbook. To access them,
please follow links like that below. The exercises may take several
seconds to launch and run in your browser. I apologize for their
slowness – this is the best platform I have found to date.</p>
<p>Please click on the link below to open an application where you can vary
the bin width and see how it changes your perspective:</p>
<p><a href="https://marin-harbur.shinyapps.io/01-app-histogram/" class="uri">https://marin-harbur.shinyapps.io/01-app-histogram/</a></p>
</div>
<div id="percentiles" class="section level3" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Percentiles</h3>
<p>We can also use <strong>percentiles</strong> to describe the values of a variable
more numerically. Percentiles describe how values the proportional
spread of values, from lowest to highest, within a distribution. To
identify percentiles, the data are numerically ordered (ranked) from
lowest to highest. Each percentile is associated with a number; the
percentile is the percentage of all data equal to or less than that
number. We can quickly generate the 0th, 25th, 50th, and 75th, and 100th
percentile in R:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="population-statistics.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(yield<span class="sc">$</span>yield_bu)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   55.12   74.96   80.62   80.09   85.44  104.95</code></pre>
<p>This returns six numbers. The 0th percentile (alternatively referred to
as the minimum) is 55.12 – this is the lowest yield measured in the
field. The 25th percentile (also called the 1st Quartile) is 74.96. This
means that 25% of all observations were equal to 74.96 bushels or less.
The 50th percentile (also known as the median) was 80.62, meaning half
of all observations were equal to 80.62 bushels or less. 75% of
observations were less than 85.44, the 75th percentile (or 3rd
quartile). Finally, the 100th percentile (or maximum yield) recorded for
this field was 104.95.</p>
<p>We are now gaining a better sense of the range of observations that were
most common. But we can describe this distribution with even fewer
numbers.</p>
</div>
<div id="normal-distribution-model" class="section level3" number="1.3.3">
<h3><span class="header-section-number">1.3.3</span> Normal Distribution Model</h3>
<p>Let’s overlay a curve, representing the <strong>normal distribution</strong>, on our
histogram. You have probably seen or heard of this curve before. Often
it is called a <em>bell curve</em>; in school, it is the <em>Curve</em> that many
students count on to bring up their grades. We will learn more about
this distribution in <em>Lesson 2</em>.</p>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>In a perfect scenario, our curve would pass through the midpoint of each
bar. This rarely happens with real-world data, and especially in
agriculture. The data may be slightly <strong>skewed</strong>, meaning there are more
individuals that measure above the mean than below, or vice versa.</p>
<p>In this example, our data do not appear skewed. Our curve seems a little
too short and wide to exactly fit the data. This is a condition called
<strong>kurtosis</strong>. No, kurtosis doesn’t mean that our data stink; they are
just more spread out or compressed than in a “perfect” situation.</p>
<p>No problem. We can – and should – conclude it is appropriate to fit
these data with a normal distribution. If we had even more data, the
curve would likely fit them even better.</p>
<p>Many populations can be handily summarized with the normal distribution
curve, but we need to know a couple of statistics about the data. First,
we need to know where the center of the curve should be. Second, we need
to know the width or dispersion of the curve.</p>
</div>
<div id="measures-of-center" class="section level3" number="1.3.4">
<h3><span class="header-section-number">1.3.4</span> Measures of Center</h3>
<p>To mathamatically describe our distribution, we first need a <strong>measure
of center</strong>. The two most common measures of center are the arithmetic
mean and median. The <strong>mean</strong> is the sum of all observations divided by
the number of observations.</p>
<p><span class="math display">\[\displaystyle \mu = \frac{\sum x_i}{n}\]</span> The <span class="math inline">\(\mu\)</span> symbol (a u with a
tail) signifies the true mean of a population. The <span class="math inline">\(\sum\)</span> symbol (the
character next to <span class="math inline">\(x_i\)</span> which looks like the angry insect alien from <em>A
Quiet Place</em>) means “sum.” Thus, anytime you see the <span class="math inline">\(\sum\)</span> symbol, we
are summing the variable(s) to its right. <span class="math inline">\(x_i\)</span> is the value <span class="math inline">\(x\)</span> of the
ith individual in the population. Finally, n is the number of
individuals in the population.</p>
<p>For example, if we have a set of number from 1:5, their mean can be
calculated as:</p>
<p><span class="math display">\[
\frac{1+2+3+4+5}{5} = 3
\]</span> The mean yield for our field is about 80.09 bushels per acre. This
isrepresented by the red line in the histogram below.</p>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Earlier, you were introduced to the median. As discussed, the <strong>median</strong>
is a number such that half of the individuals in the population are
greater and half are less. If we have an odd number of individuals, the
median is the “middle” number as the individuals are ranked from
greatest to least.</p>
<p><span class="math display">\[ \{1,2,3,4,5\} \\ median = 3 \]</span></p>
<p>If we have an even number of measures, the median is the average of the
middle two individuals in the ranking:</p>
<p><span class="math display">\[\{1,2,3,4,5,6\} \\ median = 3.5 \]</span></p>
<p>Let’s add a blue line to our histogram to represent the median.</p>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>As you can see, they are practically identical. When the mean and median
are similar, the number of individuals measuring greater and less than
the mean are roughly equivalent. In this case, our data can be
represented using the normal distribution.</p>
<p>We also need a statistic that tells us how wide to draw the curve. That
statistic is called a measure of dispersion, and we will learn about it
next.</p>
</div>
<div id="measures-of-dispersion" class="section level3" number="1.3.5">
<h3><span class="header-section-number">1.3.5</span> Measures of Dispersion</h3>
<p>To describe the spread of a population, we use one of three related
<strong>measures of disperson</strong>: sum of squares, variance, and standard
deviation. Although there is a little math involved in these three
statistics, please make yourself comfortable with their concepts because
they are <em>very</em> important in this course. Almost every statistical test
we will learn during this course is rooted in these measures of
population width.</p>
<div id="sum-of-squares" class="section level4" number="1.3.5.1">
<h4><span class="header-section-number">1.3.5.1</span> Sum of Squares</h4>
<p>The first measure of population width is the <strong>sum of squares</strong>. This is
the sum of the squared differences between each observation and the
mean. The sum of squares of a measurement x is:</p>
<p><span class="math display">\[\displaystyle S_{xx} = (x_i - \mu)^2\]</span></p>
<p>Where again <span class="math inline">\(x_i\)</span> is the value <span class="math inline">\(x\)</span> of the <span class="math inline">\(ith\)</span> individual in the
population and <span class="math inline">\(\mu\)</span> is the true mean of a population.</p>
<p>Why do we square the differences between the observations and means?
Simply, if we were to add the unsquared differences they would add to
exactly zero. Let’s prove this to ourselves. Let’s again use the set of
numbers (1, 2, 3, 4, 5). We can measure the distance of each individual
from the mean by subtracting the mean from it. This difference is called
the residual.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="population-statistics.html#cb6-1" aria-hidden="true" tabindex="-1"></a>sample_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">individuals =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>))</span>
<span id="cb6-2"><a href="population-statistics.html#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="population-statistics.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;janitor&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="population-statistics.html#cb9-1" aria-hidden="true" tabindex="-1"></a>first_resid_table <span class="ot">=</span> sample_data <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="population-statistics.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mean =</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="population-statistics.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">residual =</span> individuals <span class="sc">-</span> mean) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="population-statistics.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mean =</span> <span class="fu">as.character</span>(mean)) </span>
<span id="cb9-5"><a href="population-statistics.html#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="population-statistics.html#cb9-6" aria-hidden="true" tabindex="-1"></a>first_resid_totals <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">individuals =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb9-7"><a href="population-statistics.html#cb9-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">mean =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb9-8"><a href="population-statistics.html#cb9-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">residual =</span> <span class="fu">sum</span>(first_resid_table<span class="sc">$</span>residual))</span>
<span id="cb9-9"><a href="population-statistics.html#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="population-statistics.html#cb9-10" aria-hidden="true" tabindex="-1"></a>first_resid_table <span class="sc">%&gt;%</span></span>
<span id="cb9-11"><a href="population-statistics.html#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(first_resid_totals) <span class="sc">%&gt;%</span></span>
<span id="cb9-12"><a href="population-statistics.html#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
individuals
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:right;">
residual
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
-2
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
-1
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>The first column of the above dataset contains the individual
observations. The second column contains the population mean, repeated
for each observation. The third column is the residuals, which are
calculated by subtracting each observed value from the population mean.</p>
<p>And if we sum these residuals we get zero.</p>
<p><span class="math display">\[ (-2) + (-1) + (0) + (+1) + (+2) = 0 \]</span></p>
<p>Let’s now do this with our field data. The number of residuals (almost
6800) is too many to visualize at once, so we will pick 20 at random.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="population-statistics.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">080921</span>)</span>
<span id="cb10-2"><a href="population-statistics.html#cb10-2" aria-hidden="true" tabindex="-1"></a>yield_sample <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">yield =</span> <span class="fu">sample</span>(yield<span class="sc">$</span>yield_bu, <span class="dv">10</span>))</span>
<span id="cb10-3"><a href="population-statistics.html#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="population-statistics.html#cb10-4" aria-hidden="true" tabindex="-1"></a>second_resid_table <span class="ot">=</span> yield_sample <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="population-statistics.html#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">yield =</span> <span class="fu">round</span>(yield,<span class="dv">2</span>),</span>
<span id="cb10-6"><a href="population-statistics.html#cb10-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(yield),<span class="dv">2</span>),</span>
<span id="cb10-7"><a href="population-statistics.html#cb10-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">residual =</span> yield<span class="sc">-</span>mean) </span>
<span id="cb10-8"><a href="population-statistics.html#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="population-statistics.html#cb10-9" aria-hidden="true" tabindex="-1"></a>second_resid_totals <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">yield =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb10-10"><a href="population-statistics.html#cb10-10" aria-hidden="true" tabindex="-1"></a>                                <span class="at">mean =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb10-11"><a href="population-statistics.html#cb10-11" aria-hidden="true" tabindex="-1"></a>                                <span class="at">residual =</span> <span class="fu">sum</span>(second_resid_table<span class="sc">$</span>residual))</span>
<span id="cb10-12"><a href="population-statistics.html#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="population-statistics.html#cb10-13" aria-hidden="true" tabindex="-1"></a>second_resid_table <span class="sc">%&gt;%</span></span>
<span id="cb10-14"><a href="population-statistics.html#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(second_resid_totals) <span class="sc">%&gt;%</span></span>
<span id="cb10-15"><a href="population-statistics.html#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
yield
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:right;">
residual
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
83.61
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
7.09
</td>
</tr>
<tr>
<td style="text-align:left;">
86.82
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
10.30
</td>
</tr>
<tr>
<td style="text-align:left;">
68.39
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
-8.13
</td>
</tr>
<tr>
<td style="text-align:left;">
81.91
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
5.39
</td>
</tr>
<tr>
<td style="text-align:left;">
80.75
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
4.23
</td>
</tr>
<tr>
<td style="text-align:left;">
57.06
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
-19.46
</td>
</tr>
<tr>
<td style="text-align:left;">
62.58
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
-13.94
</td>
</tr>
<tr>
<td style="text-align:left;">
86.6
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
10.08
</td>
</tr>
<tr>
<td style="text-align:left;">
80.05
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
3.53
</td>
</tr>
<tr>
<td style="text-align:left;">
77.42
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:right;">
0.90
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
-0.01
</td>
</tr>
</tbody>
</table>
<p>If we sum up all the yield residuals, we get -0.04. Not exactly zero,
but close. The difference from zero is the result of rounding errors
during the calculation.</p>
<p>The sum of squares is calculated by squaring each residual and then
summing the residuals. For our example using the set (1, 2, 3, 4, 5):</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="population-statistics.html#cb11-1" aria-hidden="true" tabindex="-1"></a>first_squares_table <span class="ot">=</span> first_resid_table <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="population-statistics.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">square =</span> residual<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-3"><a href="population-statistics.html#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="population-statistics.html#cb11-4" aria-hidden="true" tabindex="-1"></a>first_squares_totals <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">individuals =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb11-5"><a href="population-statistics.html#cb11-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">mean =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb11-6"><a href="population-statistics.html#cb11-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">residual =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb11-7"><a href="population-statistics.html#cb11-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">square =</span> <span class="fu">sum</span>(first_squares_table<span class="sc">$</span>square))</span>
<span id="cb11-8"><a href="population-statistics.html#cb11-8" aria-hidden="true" tabindex="-1"></a>first_squares_table <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="population-statistics.html#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(first_squares_totals) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="population-statistics.html#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
individuals
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:left;">
residual
</th>
<th style="text-align:right;">
square
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
-2
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
-1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
10
</td>
</tr>
</tbody>
</table>
<p>And for our yield data:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="population-statistics.html#cb12-1" aria-hidden="true" tabindex="-1"></a>second_squares_table <span class="ot">=</span> second_resid_table <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="population-statistics.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">square =</span> <span class="fu">round</span>(residual<span class="sc">^</span><span class="dv">2</span>,<span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="population-statistics.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">residual =</span> <span class="fu">round</span>(residual, <span class="dv">2</span>))</span>
<span id="cb12-4"><a href="population-statistics.html#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="population-statistics.html#cb12-5" aria-hidden="true" tabindex="-1"></a>second_squares_totals <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">yield =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb12-6"><a href="population-statistics.html#cb12-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">mean =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb12-7"><a href="population-statistics.html#cb12-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">residual =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb12-8"><a href="population-statistics.html#cb12-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">square =</span> <span class="fu">sum</span>(second_squares_table<span class="sc">$</span>square))</span>
<span id="cb12-9"><a href="population-statistics.html#cb12-9" aria-hidden="true" tabindex="-1"></a>second_squares_table <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="population-statistics.html#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(second_squares_totals) <span class="sc">%&gt;%</span></span>
<span id="cb12-11"><a href="population-statistics.html#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
yield
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:left;">
residual
</th>
<th style="text-align:right;">
square
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
83.61
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
7.09
</td>
<td style="text-align:right;">
50.27
</td>
</tr>
<tr>
<td style="text-align:left;">
86.82
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
10.3
</td>
<td style="text-align:right;">
106.09
</td>
</tr>
<tr>
<td style="text-align:left;">
68.39
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
-8.13
</td>
<td style="text-align:right;">
66.10
</td>
</tr>
<tr>
<td style="text-align:left;">
81.91
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
5.39
</td>
<td style="text-align:right;">
29.05
</td>
</tr>
<tr>
<td style="text-align:left;">
80.75
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
4.23
</td>
<td style="text-align:right;">
17.89
</td>
</tr>
<tr>
<td style="text-align:left;">
57.06
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
-19.46
</td>
<td style="text-align:right;">
378.69
</td>
</tr>
<tr>
<td style="text-align:left;">
62.58
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
-13.94
</td>
<td style="text-align:right;">
194.32
</td>
</tr>
<tr>
<td style="text-align:left;">
86.6
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
10.08
</td>
<td style="text-align:right;">
101.61
</td>
</tr>
<tr>
<td style="text-align:left;">
80.05
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
3.53
</td>
<td style="text-align:right;">
12.46
</td>
</tr>
<tr>
<td style="text-align:left;">
77.42
</td>
<td style="text-align:left;">
76.52
</td>
<td style="text-align:left;">
0.9
</td>
<td style="text-align:right;">
0.81
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
957.29
</td>
</tr>
</tbody>
</table>
</div>
<div id="variance" class="section level4" number="1.3.5.2">
<h4><span class="header-section-number">1.3.5.2</span> Variance</h4>
<p>The sum of squares helps quantify spread: the larger the sum of squares,
the greater the spread of observations around the population mean. There
is one issue with the sum of squares, though: since the sum of square is
derived from the differences between each observation and the mean, it
is also related to the number of individuals overall in our population.
In our example above, the sum of squares was 10.</p>
<p>Now, let’s generate a dataset with two 1s, two 2s, two 3s, two 4s, and
two 5s:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="population-statistics.html#cb13-1" aria-hidden="true" tabindex="-1"></a>first_squares_table <span class="ot">=</span> first_resid_table <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="population-statistics.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">square =</span> residual<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-3"><a href="population-statistics.html#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="population-statistics.html#cb13-4" aria-hidden="true" tabindex="-1"></a>double_squares_table <span class="ot">=</span> first_squares_table <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="population-statistics.html#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(first_squares_table)</span>
<span id="cb13-6"><a href="population-statistics.html#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="population-statistics.html#cb13-7" aria-hidden="true" tabindex="-1"></a>double_squares_totals <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">individuals =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb13-8"><a href="population-statistics.html#cb13-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">mean =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb13-9"><a href="population-statistics.html#cb13-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">residual =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb13-10"><a href="population-statistics.html#cb13-10" aria-hidden="true" tabindex="-1"></a>                                <span class="at">square =</span> <span class="fu">sum</span>(double_squares_table<span class="sc">$</span>square))</span>
<span id="cb13-11"><a href="population-statistics.html#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="population-statistics.html#cb13-12" aria-hidden="true" tabindex="-1"></a>double_squares_table <span class="sc">%&gt;%</span></span>
<span id="cb13-13"><a href="population-statistics.html#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbind</span>(double_squares_totals) <span class="sc">%&gt;%</span></span>
<span id="cb13-14"><a href="population-statistics.html#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
individuals
</th>
<th style="text-align:left;">
mean
</th>
<th style="text-align:left;">
residual
</th>
<th style="text-align:right;">
square
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
-2
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
-1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
-2
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
-1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
20
</td>
</tr>
</tbody>
</table>
<p>You will notice the sum of squares increases to 20. The spread of the
data did not change: we recorded the same five values. The only
difference is that we observed each value twice.</p>
<p>The moral of this story is this: given any distribution, the sum of
squares will always increase with the number of observations. Thus, if
we want to compare the spread of two different populations with
different numbers of individuals, we need to adjust our interpretation
to allow for the number of observations.</p>
<p>We do this by dividing the sum of squares, <span class="math inline">\(S_{xx}\)</span> by the number of
observations, <span class="math inline">\(n\)</span>. In essence, we are calculating an “average” of the
sum of squares. This value is the variance, <span class="math inline">\(\sigma^2\)</span>.</p>
<p><span class="math display">\[\sigma^2 = \frac{S_{xx}}{n}\]</span> We can calculate the variance as
follows.</p>
<p>In our first example, the set {1,2,3,4,5} had a sum of squares of 10. in
that case, the variance would be:</p>
<p><span class="math display">\[\frac{10}{5} = 2
\]</span></p>
<p>In our second example, the set {1,2,3,4,5,1,2,3,4,5} had a sum of
squares of 20. In that example, the variance would be</p>
<p><span class="math display">\[
\frac{20}{10} = 2
\]</span></p>
<p>As you can see, the variance is not affected by the size of the dataset,
only by the distribution of its values.</p>
<p>Later on in this course, we will calculate the variance a little
differently:</p>
<p><span class="math display">\[\sigma^2 = \frac{S_{xx}}{n-1}\]</span> <em>n-1</em> is referred to as the <strong>degrees
of freedom</strong>. We use degrees of freedom when we work with samples
(subsets) of a population. In this unit, however, we are working with
populations, so we will not worry about those.</p>
</div>
<div id="standard-deviation" class="section level4" number="1.3.5.3">
<h4><span class="header-section-number">1.3.5.3</span> Standard Deviation</h4>
<p>Our challenge in using the variance to describe population spread is
it’s units are not intuitive. When we square the measure we also square
the units of measure. For example the variance of our yield is measured
in units of bushels<sup>2</sup>. Wrap your head around that one. Our solution is
to report our final estimate of population spread in the original units
of measure. To do this, we calculate the square root of the variance.
This statistic is called the standard deviation, <span class="math inline">\(\sigma\)</span>.</p>
<p><span class="math display">\[\sigma = \sqrt{(\sigma^2)}\]</span></p>
<p>For the dataset {1,2,3,4,5}, the sum of squares is 10, the variance 2,
and the standard deviation is:</p>
<p><span class="math display">\[\sigma = \sqrt{2} = 1.4 \]</span></p>
<p>For our yield dataset, the sum of squares is 957.29, and based on 10
observations. Our variance is therefore:</p>
<p><span class="math display">\[\sigma^2 = \frac{957.29}{10} = 9.57 \text{ bushels}^2 \text{ / acre}^2\]</span></p>
<p>Our sum of squares is :</p>
<p><span class="math display">\[ \sqrt{9.57 \text{ bushels}^2 \text{ / acre}^2} = 3.09 \text{ bushels / acre }\]</span></p>
<p>That is enough theory for this first week of class. The remainder of
this lesson will focus on introducing you to RStudioCloud.</p>
</div>
</div>
</div>
<div id="exercise-introduction-to-r" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Exercise: Introduction to R</h2>
<p>In this course, we program with R using a Integrated Development
Environment (IDE) called <strong>RStudio</strong>. If you are taking Agronomy 513 as
part of the Masters of Agronomy distance learning program at Iowa State
University – as opposed to reading it in GitBook format, then you are
working with this document in RStudio This document you have just opened
is in a format known as an <strong>R Notebook</strong>. This document allows you to
combine code and commentary into a seamless document.</p>
<p>This sentence is an example of <strong>commentary</strong>. Commentary is anything
you would type in a Word document. If you are writing a report in
RStudio, commentary might include the objective of your research, the
data you collected, how you analyzed the data, etc.</p>
<p>Immediately below is what in R Studio is called a chunk. You can create
a chunk anywhere in a document by typing CTRL+ALT+I. Note that a chunk
always begins with three apostrophes, followed by <code>{r}</code>, and always ends
with three more apostrophes, on the last line, by themselves . This
tells the notebook that anything between those two markings is R code to
be run.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb14-1"><a href="population-statistics.html#cb14-1" aria-hidden="true" tabindex="-1"></a>sample_data = c(1,2,3,4,5) # this creates a vector (a single column of data) and names it &quot;sample_data&quot;</span>
<span id="cb14-2"><a href="population-statistics.html#cb14-2" aria-hidden="true" tabindex="-1"></a>calculation = mean(sample_data) # this calculates the mean for the vector and names it &quot;calculation&quot;</span>
<span id="cb14-3"><a href="population-statistics.html#cb14-3" aria-hidden="true" tabindex="-1"></a>calculation # this tells R to print the value of calculation</span></code></pre></div>
<p>The code chunk above can be run by clicking on the green arrow in its
upper-right corner. R will run and, if there are no errors, display the
output of the code immediately below the chunk. If you click on the
chunk above, it will create the “sample_data” vector, calculate the mean
of that vector and name it “calculation,” and print the value of
calculation, which is 3.</p>
<p>There is nothing magical about the names we have selected. They are just
placeholders for the data.</p>
<div id="your-very-first-code" class="section level3" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Your Very First Code</h3>
<p>Now you try it: - create a chunk by pressing CTRL_ALT_I - create a
vector named “my sample data” that containes the numbers 6, 7, 8, 9, and
10. - calculate the mean and assign it to a variable named
“my_calculation” - display the results</p>
<p>[delete this line and create your chunk right here]</p>
<p>Were you successful?</p>
</div>
<div id="reading-and-working-with-data-frames" class="section level3" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Reading and Working with Data Frames</h3>
<p>Of course, you will soon want to work with your own data, and it is
likely to consist of multiple vectors (columns). That is, you have a
table of data. In R, this is commonly referred to as a “data frame.”</p>
<p>To read in data frame, use the read.csv command. In the chunk below, we
will use read.csv to read in a .csv file and assign it to a data frame
named “yield.”</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="population-statistics.html#cb15-1" aria-hidden="true" tabindex="-1"></a>yield <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-1/exercise_data/sample_dataset_1.csv&quot;</span>)</span></code></pre></div>
<p>The text in quotes is the path to the table of interest. “data/” tells R
the file is in a directory named “data” that is in the same folder as
this file. The rest of the text is simply the file name.</p>
<p>We can view this data frame in two ways. We can simply type its name:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="population-statistics.html#cb16-1" aria-hidden="true" tabindex="-1"></a>yield</span></code></pre></div>
<pre><code>##    observation    yield
## 1            1 227.2262
## 2            2 218.4626
## 3            3 219.8543
## 4            4 209.2137
## 5            5 218.3676
## 6            6 219.5215
## 7            7 224.6843
## 8            8 221.5054
## 9            9 222.6487
## 10          10 226.4952</code></pre>
<p>Or we can view it in more of a spreadsheet enviornment by double
clicking on it in the window to the right, or by typing “view(yield)” in
the console window below.</p>
<p>Once the data frame is created, we can use it in any subsequent chunk.
We can look at the data frame as a whole by typing its name. We can use
a particular column by typing the name of the data frame, followed by
“$” and the name of the column.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="population-statistics.html#cb18-1" aria-hidden="true" tabindex="-1"></a>single_column <span class="ot">=</span> yield<span class="sc">$</span>yield</span>
<span id="cb18-2"><a href="population-statistics.html#cb18-2" aria-hidden="true" tabindex="-1"></a>single_column</span></code></pre></div>
<pre><code>##  [1] 227.2262 218.4626 219.8543 209.2137 218.3676 219.5215 224.6843 221.5054
##  [9] 222.6487 226.4952</code></pre>
<p>If you pause after typing “$,” R will display a list of the available
columns. Just click on the one in which you are interested.</p>
</div>
<div id="basic-operations-on-columns" class="section level3" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> Basic Operations on Columns</h3>
<p>We can easily perform statistical summaries now that we have defined
“single_column.” As above, we can calculate it’s mean:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="population-statistics.html#cb20-1" aria-hidden="true" tabindex="-1"></a>single_column_mean <span class="ot">=</span> <span class="fu">mean</span>(single_column)</span>
<span id="cb20-2"><a href="population-statistics.html#cb20-2" aria-hidden="true" tabindex="-1"></a>single_column_mean</span></code></pre></div>
<pre><code>## [1] 220.798</code></pre>
<p>Or its median:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="population-statistics.html#cb22-1" aria-hidden="true" tabindex="-1"></a>single_column_median <span class="ot">=</span> <span class="fu">median</span>(single_column)</span>
<span id="cb22-2"><a href="population-statistics.html#cb22-2" aria-hidden="true" tabindex="-1"></a>single_column_median</span></code></pre></div>
<pre><code>## [1] 220.6798</code></pre>
<p>Its maximum value:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="population-statistics.html#cb24-1" aria-hidden="true" tabindex="-1"></a>single_column_max <span class="ot">=</span> <span class="fu">max</span>(single_column)</span>
<span id="cb24-2"><a href="population-statistics.html#cb24-2" aria-hidden="true" tabindex="-1"></a>single_column_max</span></code></pre></div>
<pre><code>## [1] 227.2262</code></pre>
<p>Or its minimum value:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="population-statistics.html#cb26-1" aria-hidden="true" tabindex="-1"></a>single_column_min <span class="ot">=</span> <span class="fu">min</span>(single_column)</span>
<span id="cb26-2"><a href="population-statistics.html#cb26-2" aria-hidden="true" tabindex="-1"></a>single_column_min</span></code></pre></div>
<pre><code>## [1] 209.2137</code></pre>
</div>
<div id="knitting-your-results-into-a-document" class="section level3" number="1.4.4">
<h3><span class="header-section-number">1.4.4</span> Knitting Your Results into a Document</h3>
<p>When you are done creating your R notebook, you can knit it into a final
document by clicking on the “Preview” button in the menu bar above:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="population-statistics.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb28-2"><a href="population-statistics.html#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="population-statistics.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">include_graphics</span>(<span class="st">&quot;data-unit-1/exercise_data/images/knitting.png&quot;</span>)</span></code></pre></div>
<p><img src="data-unit-1/exercise_data/images/knitting.png" width="937" /></p>
<p>If you look in the exercise folder, you will find an .html printout of
this notebook. You can email this file to collaborators, publish it to
the internet, or incorporate it into your creative component.</p>
</div>
<div id="practice" class="section level3" number="1.4.5">
<h3><span class="header-section-number">1.4.5</span> Practice</h3>
<p>Now you try. There are four practice sets, labelled
intro_to_r_practice_set_1.csv through intro_to_r_practice_set_4.csv.
Practice reading in the .csv file and calculating summary statistics as
shown above.</p>
</div>
</div>
<div id="exercise-introduction-to-shapefiles" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Exercise: Introduction to Shapefiles</h2>
<p>One of my more recent areas of growth as a data scientist has been
learning to work with spatial data. If you have worked with yield
monitor data, used ArcGIS, or used an application map to variable-rate
your fertilizer, you have worked with spatial data. Although we won’t
return to spatial data until later in the course, here is a brief
introduction to inporting and inspecting spatial data.</p>
<div id="r-packages" class="section level3" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> R Packages</h3>
<p>R programming consists of base software plus an ever increasing number
of plug-ins called “packages.” These packages provide additional
functions (programs) in R that cover everything from agricultural plot
design, interactive maps, and advanced plotting techniques, to app
development, access to census data, and even modules to teach statistics
and generate quizes.</p>
<p>If R tells us that a package is not installed, we can install it using
the “install.packages(’’) command,” where the package name is included
between the quotes. This code is shown below, but it is preceded by a
hashtag, so that line of code will not be executed by R. The hashtag can
be used to “comment” code or coding notes/explanations to that they can
remain inline with the code we want to run, but not be run themselves.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="population-statistics.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&#39;sf&#39;, repos=&#39;http://cran.us.r-project.org&#39;)</span></span>
<span id="cb29-2"><a href="population-statistics.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div>
</div>
<div id="reading-shapefiles" class="section level3" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Reading Shapefiles</h3>
<p>To read in a shapefile, we use the “st_read” command. Reading in a
shapefile is identical to how we read in a .csv file in the previous
exercise. We simply follow st_read with the path to the shapefile, which
has a .shp suffix. We will read in a shapefile from Indiana that
includes county summaries for a couple of dozen agricultural statistics.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="population-statistics.html#cb30-1" aria-hidden="true" tabindex="-1"></a>indiana <span class="ot">=</span> <span class="fu">st_read</span>(<span class="st">&quot;data-unit-1/exercise_data/Agriculture_Census-shp/Agriculture_Census.shp&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `Agriculture_Census&#39; from data source `C:\Users\559069\Documents\data-science-for-agricultural-professionals_3\data-unit-1\exercise_data\Agriculture_Census-shp\Agriculture_Census.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 92 features and 31 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -88.08975 ymin: 37.77306 xmax: -84.78768 ymax: 41.76233
## Geodetic CRS:  WGS 84</code></pre>
</div>
<div id="examining-spatial-feature-data-frames" class="section level3" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Examining Spatial Feature Data Frames</h3>
<p>Let’s inspect the first six rows of the spatial feature data frame using
the “head()” command, where the name of the data frame is given between
the parentheses.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="population-statistics.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(indiana)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 31 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -87.52704 ymin: 41.16195 xmax: -84.80631 ymax: 41.76233
## Geodetic CRS:  WGS 84
##   OBJECTID AGCENSP020              COUNTY N_FARM TOTCROP_AC HAVCROP_AC DOL_FARM
## 1        1       2515      Elkhart County   1335     160160     143324    92912
## 2        2       2516 Saint Joseph County    666     139661     131004    82849
## 3        3       2517     La Porte County    749     226816     212940   127922
## 4        4       2518      Steuben County    581      99218      71944    44133
## 5        5       2519     Lagrange County   1392     156233     127875    74194
## 6        6       2539         Lake County    442     138929     132551   108206
##   NURS_DOL LVSTOK_DOL SALE_2500 SALE_5000 EXPEN_1000 NURSY_1000 N_CHICKENS
## 1    34688      89350       251       100      96862        514    3005354
## 2    40051      15127       144        71      40479        583        852
## 3    68041      27773       136        60      71666        742      -9999
## 4    16776       8865       236        44      20288          0      -9999
## 5    37364      65915       223       105      83668          0    1870836
## 6    42747       5080       101        30      34712         66          0
##   N_CATTLE N_PIGS CORN_AC WHEAT_AC COTTON_AC SOYBEAN_AC VEGTABL_AC ORCHARD_AC
## 1    42719  73951   64955     3861         0      42251       1338          0
## 2     6440  27430   69251     4073         0      45696        480          0
## 3    24980  27110  113242     4186         0      76809       1125          0
## 4     9257   6859   32152     4483         0      25120        304          0
## 5    39275  69338   61262     3993         0      32666       1182          0
## 6     3204   9435   68344     3101         0      55698       1256          0
##   PECAN_AC IRRGTD_AC N_MACHINE FEMALE_OP MINORTY_OP FAM_FARM igs_DBO_Ag
## 1        0     23524       495        32          0     1164          0
## 2        0     12941       444        44          3      584          0
## 3        0     27090       631        44          0      626          0
## 4        0      1225     -9999        42          0      505          0
## 5        0     23478       315        26          0     1232          0
## 6        0      6211       327        42          3      356          0
##   SHAPE_Leng SHAPE_Area                       geometry
## 1   139058.4 1210349270 POLYGON ((-86.06246 41.7619...
## 2   155098.8 1196846667 POLYGON ((-86.22555 41.7614...
## 3   175216.0 1563031845 POLYGON ((-86.82619 41.7608...
## 4   116305.4  835438144 POLYGON ((-85.19779 41.7605...
## 5   128976.5 1000327995 POLYGON ((-85.29134 41.7606...
## 6   167477.6 1300778609 POLYGON ((-87.52401 41.7135...</code></pre>
<p>Spatial feature data frames are very similar to the data frames that
were introduced to in the last exercise. There are a few differences,
however. First, every spatial feature data frame consists of rows of
observations that are linked, in the geometry column, with a
georeference. That georeference may be a simple point on the map, or it
may be a polygon that defines an area, such as a field, a county, or a
state.</p>
<p>Spatial feature data frames also include some metadata about the
geometry of the file, including geometry type (POLYGON in this case,
since we are working with county outlines) and – this is critical –
CRS. CRS stands for “coordinate reference system.” Coordinate reference
system refers to the “projection” we use to draw a map, and the
georeferences used to define a place or area.</p>
<p>Maps are flat representations of a round object, and there are different
ways to draw these maps. We need not go into a deep review of those
projects at this point; suffice it to know that each projection
represents tradeoffs in how accurately it portrays areas in the center
and periphery of the map and how much it represents the curvature. For
most of my work, I use the CRS of 4326. You know this system more
commonly as the latitude/longitude system.</p>
<p>The bounding box defines where the map is centered. Latitude/longitude
maps are more accurate in portraying areas near the center of the map
than the periphery, so it is important the map be centered on the area
of interest.</p>
</div>
<div id="visualizing-data" class="section level3" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Visualizing Data</h3>
<p>To visualize the data, we can use the “plot” function from the sf
package. You might assume we could map a column of data the same way we
visualized its contents earlier, by indicating the data frame and column
name, separated by the dollar sign. We will try that with TOTCROP_AC,
the total number of acres per county in crop production.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="population-statistics.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(indiana<span class="sc">$</span>TOTCROP_AC)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Instead of a map, however, this shows us the range of values for
TOTCROP_AC in the dataset. To view a map, we need to first subset the
data so it only has two columns: the TOTCROP_AC data and geometry
columns. We can then map these data:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="population-statistics.html#cb35-1" aria-hidden="true" tabindex="-1"></a>tot_crop <span class="ot">=</span> indiana[<span class="st">&quot;TOTCROP_AC&quot;</span>]</span>
<span id="cb35-2"><a href="population-statistics.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tot_crop)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>No one can resist a pretty map. The technical name for a map like this,
where you color-code political shapes like counties, is “chloropleth.”
We are seeing plenty of these in 2020, between the pandemic and the
election year.</p>
<p>Back to happier thoughts. Let’s look at the mean farm income per county.
This is indicated by the “DOL_FARM” column. Again, we first subset the
data and then plot it.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="population-statistics.html#cb36-1" aria-hidden="true" tabindex="-1"></a>farm_income <span class="ot">=</span> indiana[<span class="st">&quot;DOL_FARM&quot;</span>]</span>
<span id="cb36-2"><a href="population-statistics.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(farm_income)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Where are the chickens in Indiana? Let’s find out:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="population-statistics.html#cb37-1" aria-hidden="true" tabindex="-1"></a>chickens <span class="ot">=</span> indiana[<span class="st">&quot;N_CHICKENS&quot;</span>]</span>
<span id="cb37-2"><a href="population-statistics.html#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(chickens)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>It would appear the most finger-lickin’ good county is Elkart County, in
the far north. Appropriately, there are also a couple of counties near
Kentucky!</p>
</div>
<div id="create-your-own-maps" class="section level3" number="1.5.5">
<h3><span class="header-section-number">1.5.5</span> Create Your Own Maps</h3>
<p>Where are the hogs in Indiana? Create a map for “N_PIGS.”</p>
<p>Where are most of the wheat acres? Create a map for “WHEAT_AC.”</p>
<p>Which counties have greater farm ownership by minorities? Create a map
for “MINORTY_OP” (note the mispelling).</p>
</div>
</div>
<div id="exercise-histograms" class="section level2" number="1.6">
<h2><span class="header-section-number">1.6</span> Exercise: Histograms</h2>
<p>One of the most critical – and I will admit, often overlooked at first
by me in my rush to look at treatment differences – steps in data
science is to inspect the data for the shape of its distribution and
extreme values. There are a multiple ways to do this. This week, we will
focus on the histogram.</p>
<div id="case-study" class="section level3" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Case Study</h3>
<p>The first example we will use is a cotton uniformity trial conducted in
Greece in 1938. Yes, I realize it is a bit dated, but the concept is one
we deal with every day in agricultural research – how consistent are
our plots. In other words, what is the variance among plots?</p>
<p>In a uniformity trial, a series of plots are managed identically so that
the distribution of their yields can be measured. These data can be used
to determine whether that field is a good site for a research trial.</p>
<p>Our first step is to load the data, which is in a .csv file.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="population-statistics.html#cb38-1" aria-hidden="true" tabindex="-1"></a>cotton <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-1/exercise_data/cotton_uniformity.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="basic-histogram" class="section level3" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Basic Histogram</h3>
<p>Drawing a simple histogram in R requires two steps. First, we need to
define the column in which we are interested. Then we create the
histogram. Since we are using a data frame, we need to tell R which
column to plot. We will, unimaginedly, call this column “yield.” With
our second line of code we will create the histogram. In the third line,
we tell R to plot the histogram</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="population-statistics.html#cb39-1" aria-hidden="true" tabindex="-1"></a>yield <span class="ot">=</span> cotton<span class="sc">$</span>yield</span>
<span id="cb39-2"><a href="population-statistics.html#cb39-2" aria-hidden="true" tabindex="-1"></a>histogram <span class="ot">=</span> <span class="fu">hist</span>(yield)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="population-statistics.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(histogram)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-31-2.png" width="672" /></p>
<p>And, voila, we have a plot of our histogram. Each bar represents a range
in values, or a “bin.” We can see the upper and lower yield limits of
each bins using the “histogram$breaks” command.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="population-statistics.html#cb41-1" aria-hidden="true" tabindex="-1"></a>histogram<span class="sc">$</span>breaks</span></code></pre></div>
<pre><code>##  [1] 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7</code></pre>
<p>Alternatively, we could see the midpoints, or yield values that define
the middle of each bin, using the “histogram$mids” command.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="population-statistics.html#cb43-1" aria-hidden="true" tabindex="-1"></a>histogram<span class="sc">$</span>mids</span></code></pre></div>
<pre><code>##  [1] 0.35 0.45 0.55 0.65 0.75 0.85 0.95 1.05 1.15 1.25 1.35 1.45 1.55 1.65</code></pre>
<p>As we saw in the lesson, varying the number of columns can affect how we
see patterns in the data. In the plot above, we have 14 bars. Each bar
represents a bin width of 0.1. What if we tell R to use 28 bins to draw
the histogram? We can do that by telling R to use about 28 breaks
(divisions between bins).</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="population-statistics.html#cb45-1" aria-hidden="true" tabindex="-1"></a>histogram <span class="ot">=</span> <span class="fu">hist</span>(yield, <span class="at">breaks =</span> <span class="dv">28</span>)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Note that we ended up with 27, not 28 bins, but that each now has a bin
width that is 0.05 kg. We can verify this by again inspecting the data
with “histogram$breaks.”</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="population-statistics.html#cb46-1" aria-hidden="true" tabindex="-1"></a>histogram<span class="sc">$</span>breaks</span></code></pre></div>
<pre><code>##  [1] 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05
## [16] 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70</code></pre>
</div>
<div id="histograms-with-ggplot" class="section level3" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Histograms with ggplot</h3>
<p>“ggplot2” is a very powerful and population package in R for creating
plots. I spend A LOT of time using ggplot2, essentially any time I am
creating plots. With ggplot, if you can imagine it, you almost certainly
can draw it. There are entire books written on ggplot; rather than focus
on it, I will try to weave tidbits throughout this course.</p>
<p>Since ggplot is a package, we need to install and load it before we can
use it. Note: if you are running R on your desktop, you only need to
install a package the very first time you use it. Afterwards, you only
need to run library() to load it into the local memory when you need it.</p>
<p>The first line of code calls ggplot(). We use “data=cotton” to tell R we
are drawing data from the “cotton” data frame.</p>
<p>We then need to specify an “aesthetic.” An aesthetic is any property of
the plot that relates to a variable, that is, a column in our data
frame. In this case, we use aes(x=yield) to tell R that our aesthetic is
positioned horizontally according to the value of yield.</p>
<p>In the second line, we use geom_histogram to tell R we are drawing a
histogram. Knowing this, R will automatically assign bins and count the
number of observations in each bin.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="population-statistics.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;ggplot2&quot;)</span></span>
<span id="cb48-2"><a href="population-statistics.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb48-3"><a href="population-statistics.html#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="population-statistics.html#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>cotton, <span class="fu">aes</span>(<span class="at">x=</span>yield)) <span class="sc">+</span></span>
<span id="cb48-5"><a href="population-statistics.html#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>By default, R chooses to create 30 bins. We can easily specify a
different number of bins using the “bins=” argument.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="population-statistics.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>cotton, <span class="fu">aes</span>(<span class="at">x=</span>yield)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="population-statistics.html#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">15</span>)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Alternatively, we can set a particular binwidth using the “binwidth =”
argument.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="population-statistics.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>cotton, <span class="fu">aes</span>(<span class="at">x=</span>yield)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="population-statistics.html#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>If we want to make our plot a little less bland, we can tell ggplot to
use a different color to fill the bars using the “fill =” argument</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="population-statistics.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>cotton, <span class="fu">aes</span>(<span class="at">x=</span>yield)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="population-statistics.html#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.05</span>, <span class="at">fill=</span><span class="st">&quot;darkolivegreen&quot;</span>)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>Finally, we can outline the bars using the “color =” argument.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="population-statistics.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>cotton, <span class="fu">aes</span>(<span class="at">x=</span>yield)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="population-statistics.html#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.05</span>, <span class="at">fill=</span><span class="st">&quot;darkolivegreen&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="01-Introduction-and-Population-Statistics_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>We will introduce more ways to fine tune our plots as the course goes
on.</p>
</div>
<div id="practice-1" class="section level3" number="1.6.4">
<h3><span class="header-section-number">1.6.4</span> Practice</h3>
<p>In the data folder there are three practice files:
barley_uniformity.csv, peanut_uniformity.csv, and tomato_uniformity.csv.
Practice creating histograms using both the basic and ggplot methods. To
start you off, here is the command to load the barley file.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="population-statistics.html#cb54-1" aria-hidden="true" tabindex="-1"></a>barley <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-1/exercise_data/barley_uniformity.csv&quot;</span>)</span></code></pre></div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="distributions-and-probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-start.pdf", "bookdown-start.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
