<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Two-Treatment Comparisons | Data Science for Agricultural Professionals</title>
  <meta name="description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Two-Treatment Comparisons | Data Science for Agricultural Professionals" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://mharbur.github.io/data-science-for-agricultural-professionals/" />
  
  <meta property="og:description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  <meta name="github-repo" content="https://github.com/mharbur/data-science-for-agricultural-professionals" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Two-Treatment Comparisons | Data Science for Agricultural Professionals" />
  
  <meta name="twitter:description" content="Practical statistics for those involved in agronomy and related agricultural sciences." />
  

<meta name="author" content="Marin L. Harbur" />


<meta name="date" content="2021-08-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sample-statistics.html"/>
<link rel="next" href="understanding-statistical-tests.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.4.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.0.4.1/leaflet-providers-plugin.js"></script>
<script src="libs/stars-1/data_stars_starsf0cb2a.txt"></script>
<script src="libs/joda-0.0.1/joda.js"></script>
<script src="libs/joda-0.0.1/addImageQuery-bindings.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science for Agricultural Professionals</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#welcome"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-language"><i class="fa fa-check"></i>R-language</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="population-statistics.html"><a href="population-statistics.html"><i class="fa fa-check"></i><b>1</b> Population Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="population-statistics.html"><a href="population-statistics.html#populations"><i class="fa fa-check"></i><b>1.1</b> Populations</a></li>
<li class="chapter" data-level="1.2" data-path="population-statistics.html"><a href="population-statistics.html#case-study-yield-map"><i class="fa fa-check"></i><b>1.2</b> Case Study: Yield Map</a></li>
<li class="chapter" data-level="1.3" data-path="population-statistics.html"><a href="population-statistics.html#distributions"><i class="fa fa-check"></i><b>1.3</b> Distributions</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="population-statistics.html"><a href="population-statistics.html#histograms"><i class="fa fa-check"></i><b>1.3.1</b> Histograms</a></li>
<li class="chapter" data-level="1.3.2" data-path="population-statistics.html"><a href="population-statistics.html#percentiles"><i class="fa fa-check"></i><b>1.3.2</b> Percentiles</a></li>
<li class="chapter" data-level="1.3.3" data-path="population-statistics.html"><a href="population-statistics.html#normal-distribution-model"><i class="fa fa-check"></i><b>1.3.3</b> Normal Distribution Model</a></li>
<li class="chapter" data-level="1.3.4" data-path="population-statistics.html"><a href="population-statistics.html#measures-of-center"><i class="fa fa-check"></i><b>1.3.4</b> Measures of Center</a></li>
<li class="chapter" data-level="1.3.5" data-path="population-statistics.html"><a href="population-statistics.html#measures-of-dispersion"><i class="fa fa-check"></i><b>1.3.5</b> Measures of Dispersion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html"><i class="fa fa-check"></i><b>2</b> Distributions and Probability</a>
<ul>
<li class="chapter" data-level="2.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#case-study"><i class="fa fa-check"></i><b>2.1</b> Case Study</a></li>
<li class="chapter" data-level="2.2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-normal-distribution-model"><i class="fa fa-check"></i><b>2.2</b> The Normal Distribution Model</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-bell-curve"><i class="fa fa-check"></i><b>2.2.1</b> The Bell Curve</a></li>
<li class="chapter" data-level="2.2.2" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#distribution-and-probability"><i class="fa fa-check"></i><b>2.2.2</b> Distribution and Probability</a></li>
<li class="chapter" data-level="2.2.3" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#probability-and-the-normal-distribution-curve"><i class="fa fa-check"></i><b>2.2.3</b> Probability and the Normal Distribution Curve</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#the-z-distribution"><i class="fa fa-check"></i><b>2.3</b> The Z-Distribution</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="distributions-and-probability.html"><a href="distributions-and-probability.html#important-numbers-95-and-5"><i class="fa fa-check"></i><b>2.3.1</b> Important Numbers: 95% and 5%</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-statistics.html"><a href="sample-statistics.html"><i class="fa fa-check"></i><b>3</b> Sample Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-statistics.html"><a href="sample-statistics.html#samples"><i class="fa fa-check"></i><b>3.1</b> Samples</a></li>
<li class="chapter" data-level="3.2" data-path="sample-statistics.html"><a href="sample-statistics.html#case-study-1"><i class="fa fa-check"></i><b>3.2</b> Case Study</a></li>
<li class="chapter" data-level="3.3" data-path="sample-statistics.html"><a href="sample-statistics.html#distribution-of-sample-means"><i class="fa fa-check"></i><b>3.3</b> Distribution of Sample Means</a></li>
<li class="chapter" data-level="3.4" data-path="sample-statistics.html"><a href="sample-statistics.html#central-limit-theorem"><i class="fa fa-check"></i><b>3.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="3.5" data-path="sample-statistics.html"><a href="sample-statistics.html#standard-error"><i class="fa fa-check"></i><b>3.5</b> Standard Error</a></li>
<li class="chapter" data-level="3.6" data-path="sample-statistics.html"><a href="sample-statistics.html#degrees-of-freedom"><i class="fa fa-check"></i><b>3.6</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="3.7" data-path="sample-statistics.html"><a href="sample-statistics.html#the-t-distribution"><i class="fa fa-check"></i><b>3.7</b> The t-Distribution</a></li>
<li class="chapter" data-level="3.8" data-path="sample-statistics.html"><a href="sample-statistics.html#confidence-interval"><i class="fa fa-check"></i><b>3.8</b> Confidence Interval</a></li>
<li class="chapter" data-level="3.9" data-path="sample-statistics.html"><a href="sample-statistics.html#confidence-interval-and-probability"><i class="fa fa-check"></i><b>3.9</b> Confidence Interval and Probability</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two-Treatment Comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#side-by-side-trials"><i class="fa fa-check"></i><b>4.1</b> Side-by-Side Trials</a></li>
<li class="chapter" data-level="4.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#blocked-design"><i class="fa fa-check"></i><b>4.2</b> Blocked Design</a></li>
<li class="chapter" data-level="4.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-2"><i class="fa fa-check"></i><b>4.3</b> Case Study</a></li>
<li class="chapter" data-level="4.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#confidence-interval-1"><i class="fa fa-check"></i><b>4.4</b> Confidence Interval</a></li>
<li class="chapter" data-level="4.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#t-test"><i class="fa fa-check"></i><b>4.5</b> T-Test</a></li>
<li class="chapter" data-level="4.6" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-randomizing-plots"><i class="fa fa-check"></i><b>4.6</b> Exercise: Randomizing Plots</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-1"><i class="fa fa-check"></i><b>4.6.1</b> Example 1</a></li>
<li class="chapter" data-level="4.6.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#the-agricolae-package"><i class="fa fa-check"></i><b>4.6.2</b> The Agricolae Package</a></li>
<li class="chapter" data-level="4.6.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#randomizing-the-plot"><i class="fa fa-check"></i><b>4.6.3</b> Randomizing the Plot</a></li>
<li class="chapter" data-level="4.6.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#working-with-lists"><i class="fa fa-check"></i><b>4.6.4</b> Working with Lists</a></li>
<li class="chapter" data-level="4.6.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-2"><i class="fa fa-check"></i><b>4.6.5</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-restructuring-columns-and-rows"><i class="fa fa-check"></i><b>4.7</b> Exercise: Restructuring Columns and Rows</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#operations-on-data"><i class="fa fa-check"></i><b>4.7.1</b> Operations on Data</a></li>
<li class="chapter" data-level="4.7.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-soybean-fungicide"><i class="fa fa-check"></i><b>4.7.2</b> Case Study: Soybean Fungicide</a></li>
<li class="chapter" data-level="4.7.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-1"><i class="fa fa-check"></i><b>4.7.3</b> Practice 1</a></li>
<li class="chapter" data-level="4.7.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-2"><i class="fa fa-check"></i><b>4.7.4</b> Practice 2</a></li>
<li class="chapter" data-level="4.7.5" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-3"><i class="fa fa-check"></i><b>4.7.5</b> Practice 3</a></li>
<li class="chapter" data-level="4.7.6" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice-4"><i class="fa fa-check"></i><b>4.7.6</b> Practice 4</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-confidence-interval-of-difference"><i class="fa fa-check"></i><b>4.8</b> Exercise: Confidence Interval of Difference"</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-1-1"><i class="fa fa-check"></i><b>4.8.1</b> Example 1</a></li>
<li class="chapter" data-level="4.8.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#example-2-1"><i class="fa fa-check"></i><b>4.8.2</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#exercise-t-test"><i class="fa fa-check"></i><b>4.9</b> Exercise: T-Test</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-1-wheat-fungicide"><i class="fa fa-check"></i><b>4.9.1</b> Case Study 1: Wheat Fungicide</a></li>
<li class="chapter" data-level="4.9.2" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#t-test-1"><i class="fa fa-check"></i><b>4.9.2</b> T-Test</a></li>
<li class="chapter" data-level="4.9.3" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#case-study-2-apple-variety"><i class="fa fa-check"></i><b>4.9.3</b> Case Study 2: Apple Variety</a></li>
<li class="chapter" data-level="4.9.4" data-path="two-treatment-comparisons.html"><a href="two-treatment-comparisons.html#practice"><i class="fa fa-check"></i><b>4.9.4</b> Practice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html"><i class="fa fa-check"></i><b>5</b> Understanding Statistical Tests</a>
<ul>
<li class="chapter" data-level="5.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#research-question"><i class="fa fa-check"></i><b>5.1</b> Research Question</a></li>
<li class="chapter" data-level="5.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#the-model"><i class="fa fa-check"></i><b>5.2</b> The Model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#treatment-effect"><i class="fa fa-check"></i><b>5.2.1</b> Treatment Effect</a></li>
<li class="chapter" data-level="5.2.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#error-effect"><i class="fa fa-check"></i><b>5.2.2</b> Error Effect</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#hypotheses"><i class="fa fa-check"></i><b>5.3</b> Hypotheses</a></li>
<li class="chapter" data-level="5.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#p-value"><i class="fa fa-check"></i><b>5.4</b> P-Value</a></li>
<li class="chapter" data-level="5.5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#the-p-value-and-errors"><i class="fa fa-check"></i><b>5.5</b> The P-Value and Errors</a></li>
<li class="chapter" data-level="5.6" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#one-sided-vs-two-sided-hypotheses"><i class="fa fa-check"></i><b>5.6</b> One-Sided vs Two-Sided Hypotheses</a></li>
<li class="chapter" data-level="5.7" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#exercise-linear-additive-model"><i class="fa fa-check"></i><b>5.7</b> Exercise: Linear Additive Model</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#case-study-barley-effects"><i class="fa fa-check"></i><b>5.7.1</b> Case Study: Barley Effects</a></li>
<li class="chapter" data-level="5.7.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#plotting-the-effects"><i class="fa fa-check"></i><b>5.7.2</b> Plotting the Effects</a></li>
<li class="chapter" data-level="5.7.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#examining-individual-plots"><i class="fa fa-check"></i><b>5.7.3</b> Examining Individual Plots</a></li>
<li class="chapter" data-level="5.7.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#practice-groudnut"><i class="fa fa-check"></i><b>5.7.4</b> Practice: Groudnut</a></li>
<li class="chapter" data-level="5.7.5" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#plotting-the-effects-1"><i class="fa fa-check"></i><b>5.7.5</b> Plotting the Effects</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#exercise-one-sided-hypotheses"><i class="fa fa-check"></i><b>5.8</b> Exercise: One-Sided Hypotheses</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#case-study-groundnut"><i class="fa fa-check"></i><b>5.8.1</b> Case Study: Groundnut</a></li>
<li class="chapter" data-level="5.8.2" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#one-sided-t-test"><i class="fa fa-check"></i><b>5.8.2</b> One-Sided T-Test</a></li>
<li class="chapter" data-level="5.8.3" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#practice-barley"><i class="fa fa-check"></i><b>5.8.3</b> Practice: Barley</a></li>
<li class="chapter" data-level="5.8.4" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#practice-strawberry"><i class="fa fa-check"></i><b>5.8.4</b> Practice: Strawberry</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="understanding-statistical-tests.html"><a href="understanding-statistical-tests.html#exercise-type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>5.9</b> Exercise: Type I and Type II Errors</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html"><i class="fa fa-check"></i><b>6</b> Multiple Treatment Trials</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-3"><i class="fa fa-check"></i><b>6.1</b> Case Study</a></li>
<li class="chapter" data-level="6.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-linear-additive-model"><i class="fa fa-check"></i><b>6.2</b> The Linear Additive Model</a></li>
<li class="chapter" data-level="6.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#analysis-of-variance"><i class="fa fa-check"></i><b>6.3</b> Analysis of Variance</a></li>
<li class="chapter" data-level="6.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-f-statistic"><i class="fa fa-check"></i><b>6.4</b> The F statistic</a></li>
<li class="chapter" data-level="6.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#the-anova-table"><i class="fa fa-check"></i><b>6.5</b> The ANOVA Table</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#source-of-variation"><i class="fa fa-check"></i><b>6.5.1</b> Source of Variation</a></li>
<li class="chapter" data-level="6.5.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#sum-of-squares-1"><i class="fa fa-check"></i><b>6.5.2</b> Sum of Squares</a></li>
<li class="chapter" data-level="6.5.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#degrees-of-freedom-1"><i class="fa fa-check"></i><b>6.5.3</b> Degrees of Freedom</a></li>
<li class="chapter" data-level="6.5.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#mean-square"><i class="fa fa-check"></i><b>6.5.4</b> Mean Square</a></li>
<li class="chapter" data-level="6.5.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#f-value"><i class="fa fa-check"></i><b>6.5.5</b> F-Value</a></li>
<li class="chapter" data-level="6.5.6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#p-value-1"><i class="fa fa-check"></i><b>6.5.6</b> P-value</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#visualizing-how-the-anova-table-relates-to-variance"><i class="fa fa-check"></i><b>6.6</b> Visualizing How the Anova Table Relates to Variance</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-barley"><i class="fa fa-check"></i><b>6.6.1</b> Case Study: Barley</a></li>
<li class="chapter" data-level="6.6.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#anova"><i class="fa fa-check"></i><b>6.6.2</b> ANOVA</a></li>
<li class="chapter" data-level="6.6.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#calculating-the-coefficient-of-variation"><i class="fa fa-check"></i><b>6.6.3</b> Calculating the Coefficient of Variation</a></li>
<li class="chapter" data-level="6.6.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-beet-data"><i class="fa fa-check"></i><b>6.6.4</b> Practice: Beet Data</a></li>
<li class="chapter" data-level="6.6.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-potato-data"><i class="fa fa-check"></i><b>6.6.5</b> Practice: Potato Data</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#exercise-treatment-means"><i class="fa fa-check"></i><b>6.7</b> Exercise: “Treatment Means”</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#case-study-barley-1"><i class="fa fa-check"></i><b>6.7.1</b> Case Study: Barley</a></li>
<li class="chapter" data-level="6.7.2" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#calculating-treatment-means"><i class="fa fa-check"></i><b>6.7.2</b> Calculating Treatment Means</a></li>
<li class="chapter" data-level="6.7.3" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#plotting-the-means"><i class="fa fa-check"></i><b>6.7.3</b> Plotting the Means</a></li>
<li class="chapter" data-level="6.7.4" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-beet-data-1"><i class="fa fa-check"></i><b>6.7.4</b> Practice: Beet Data</a></li>
<li class="chapter" data-level="6.7.5" data-path="multiple-treatment-trials.html"><a href="multiple-treatment-trials.html#practice-potato-data-1"><i class="fa fa-check"></i><b>6.7.5</b> Practice: Potato Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html"><i class="fa fa-check"></i><b>7</b> Multiple Treatment Designs</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#randomized-complete-block-design"><i class="fa fa-check"></i><b>7.1</b> Randomized Complete Block Design</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-randomized-complete-block-design"><i class="fa fa-check"></i><b>7.1.1</b> Case Study: Randomized Complete Block Design</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#factorial-design"><i class="fa fa-check"></i><b>7.2</b> Factorial Design</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-1-1"><i class="fa fa-check"></i><b>7.2.1</b> Case Study 1</a></li>
<li class="chapter" data-level="7.2.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-2-1"><i class="fa fa-check"></i><b>7.2.2</b> Case Study 2</a></li>
<li class="chapter" data-level="7.2.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#discussing-interactions"><i class="fa fa-check"></i><b>7.2.3</b> Discussing Interactions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#split-plot-design"><i class="fa fa-check"></i><b>7.3</b> Split-Plot Design</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#linear-additive-model-3"><i class="fa fa-check"></i><b>7.4</b> Linear Additive Model</a></li>
<li class="chapter" data-level="7.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#conclusion"><i class="fa fa-check"></i><b>7.5</b> Conclusion</a></li>
<li class="chapter" data-level="7.6" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-randomized-complete-block-design"><i class="fa fa-check"></i><b>7.6</b> Exercise: Randomized Complete Block Design</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-4"><i class="fa fa-check"></i><b>7.6.1</b> Case Study</a></li>
<li class="chapter" data-level="7.6.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#anova-1"><i class="fa fa-check"></i><b>7.6.2</b> ANOVA</a></li>
<li class="chapter" data-level="7.6.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#plotting-the-results"><i class="fa fa-check"></i><b>7.6.3</b> Plotting the Results</a></li>
<li class="chapter" data-level="7.6.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-5"><i class="fa fa-check"></i><b>7.6.4</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-factorial-anova"><i class="fa fa-check"></i><b>7.7</b> Exercise: Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-biochar"><i class="fa fa-check"></i><b>7.7.1</b> Case Study: Biochar</a></li>
<li class="chapter" data-level="7.7.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#anova-2"><i class="fa fa-check"></i><b>7.7.2</b> ANOVA</a></li>
<li class="chapter" data-level="7.7.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#interaction-plots"><i class="fa fa-check"></i><b>7.7.3</b> Interaction Plots</a></li>
<li class="chapter" data-level="7.7.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#testing-factors-individually"><i class="fa fa-check"></i><b>7.7.4</b> Testing Factors Individually</a></li>
<li class="chapter" data-level="7.7.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#bar-plots"><i class="fa fa-check"></i><b>7.7.5</b> Bar Plots</a></li>
<li class="chapter" data-level="7.7.6" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-6"><i class="fa fa-check"></i><b>7.7.6</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-split-plot-design"><i class="fa fa-check"></i><b>7.8</b> Exercise: Split-Plot Design</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#case-study-corn-soybean-systems-trial"><i class="fa fa-check"></i><b>7.8.1</b> Case Study: Corn-Soybean Systems Trial</a></li>
<li class="chapter" data-level="7.8.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#anova-4"><i class="fa fa-check"></i><b>7.8.2</b> ANOVA</a></li>
<li class="chapter" data-level="7.8.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#interaction-plot"><i class="fa fa-check"></i><b>7.8.3</b> Interaction Plot</a></li>
<li class="chapter" data-level="7.8.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#bar-plot"><i class="fa fa-check"></i><b>7.8.4</b> Bar plot</a></li>
<li class="chapter" data-level="7.8.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-7"><i class="fa fa-check"></i><b>7.8.5</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#exercise-experimental-design"><i class="fa fa-check"></i><b>7.9</b> Exercise: Experimental Design</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#completely-randomized-design"><i class="fa fa-check"></i><b>7.9.1</b> Completely Randomized Design</a></li>
<li class="chapter" data-level="7.9.2" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#randomized-complete-block-design-1"><i class="fa fa-check"></i><b>7.9.2</b> Randomized Complete Block Design</a></li>
<li class="chapter" data-level="7.9.3" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#factorial-design-1"><i class="fa fa-check"></i><b>7.9.3</b> Factorial Design</a></li>
<li class="chapter" data-level="7.9.4" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#split-plot-design-1"><i class="fa fa-check"></i><b>7.9.4</b> Split-Plot Design</a></li>
<li class="chapter" data-level="7.9.5" data-path="multiple-treatment-designs.html"><a href="multiple-treatment-designs.html#practice-8"><i class="fa fa-check"></i><b>7.9.5</b> Practice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html"><i class="fa fa-check"></i><b>8</b> Means Separation and Data Presentation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-5"><i class="fa fa-check"></i><b>8.1</b> Case Study</a></li>
<li class="chapter" data-level="8.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#least-significant-difference"><i class="fa fa-check"></i><b>8.2</b> Least Significant Difference</a></li>
<li class="chapter" data-level="8.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#lsd-output-in-r"><i class="fa fa-check"></i><b>8.3</b> LSD Output in R</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#statistics-table"><i class="fa fa-check"></i><b>8.3.1</b> Statistics Table</a></li>
<li class="chapter" data-level="8.3.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-table"><i class="fa fa-check"></i><b>8.3.2</b> Means Table</a></li>
<li class="chapter" data-level="8.3.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#groups-table"><i class="fa fa-check"></i><b>8.3.3</b> Groups Table</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#comparisonwise-versus-experimentwise-error"><i class="fa fa-check"></i><b>8.4</b> Comparisonwise versus Experimentwise Error</a></li>
<li class="chapter" data-level="8.5" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#tukeys-honest-significant-difference"><i class="fa fa-check"></i><b>8.5</b> Tukey’s Honest Significant Difference</a></li>
<li class="chapter" data-level="8.6" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#linear-contrast"><i class="fa fa-check"></i><b>8.6</b> Linear Contrast</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#coefficients"><i class="fa fa-check"></i><b>8.6.1</b> Coefficients</a></li>
<li class="chapter" data-level="8.6.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#linear-contrasts-with-r"><i class="fa fa-check"></i><b>8.6.2</b> Linear Contrasts with R</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-presentation"><i class="fa fa-check"></i><b>8.7</b> Means Presentation</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#means-tables"><i class="fa fa-check"></i><b>8.7.1</b> Means Tables</a></li>
<li class="chapter" data-level="8.7.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#plotting-means"><i class="fa fa-check"></i><b>8.7.2</b> Plotting Means</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#exercise-lsd-and-tukeys-hsd"><i class="fa fa-check"></i><b>8.8</b> Exercise: LSD and Tukey’s HSD</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-common-bean"><i class="fa fa-check"></i><b>8.8.1</b> Case Study: Common Bean</a></li>
<li class="chapter" data-level="8.8.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#least-significant-difference-1"><i class="fa fa-check"></i><b>8.8.2</b> Least Significant Difference</a></li>
<li class="chapter" data-level="8.8.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#tukey-hsd"><i class="fa fa-check"></i><b>8.8.3</b> Tukey HSD</a></li>
<li class="chapter" data-level="8.8.4" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-apple"><i class="fa fa-check"></i><b>8.8.4</b> Practice: Apple</a></li>
<li class="chapter" data-level="8.8.5" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-wheat-treatment-with-mildew"><i class="fa fa-check"></i><b>8.8.5</b> Practice: Wheat Treatment with Mildew</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#exercise-linear-contrasts"><i class="fa fa-check"></i><b>8.9</b> Exercise: Linear Contrasts</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-winter-canola-cultivar-trial."><i class="fa fa-check"></i><b>8.9.1</b> Case Study: Winter Canola Cultivar Trial.</a></li>
<li class="chapter" data-level="8.9.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#running-the-contrast"><i class="fa fa-check"></i><b>8.9.2</b> Running the Contrast</a></li>
<li class="chapter" data-level="8.9.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-corn-nitrogen-source-and-timing"><i class="fa fa-check"></i><b>8.9.3</b> Practice: Corn Nitrogen Source and Timing</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#exercise-means-tables"><i class="fa fa-check"></i><b>8.10</b> Exercise: Means Tables</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#case-study-corn-nitrogen-source-and-timing"><i class="fa fa-check"></i><b>8.10.1</b> Case Study: Corn Nitrogen Source and Timing</a></li>
<li class="chapter" data-level="8.10.2" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-canola"><i class="fa fa-check"></i><b>8.10.2</b> Practice: Canola</a></li>
<li class="chapter" data-level="8.10.3" data-path="means-separation-and-data-presentation.html"><a href="means-separation-and-data-presentation.html#practice-broccoli-lsd"><i class="fa fa-check"></i><b>8.10.3</b> Practice: Broccoli LSD</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html"><i class="fa fa-check"></i><b>9</b> Messy and Missing Data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#inspecting-data-for-normal-distributions"><i class="fa fa-check"></i><b>9.1</b> Inspecting data for Normal Distributions</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#histograms-1"><i class="fa fa-check"></i><b>9.1.1</b> Histograms</a></li>
<li class="chapter" data-level="9.1.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#rank-percentile-plots"><i class="fa fa-check"></i><b>9.1.2</b> Rank Percentile Plots</a></li>
<li class="chapter" data-level="9.1.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#box-plots"><i class="fa fa-check"></i><b>9.1.3</b> Box Plots</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#inspecting-data-for-equal-variances"><i class="fa fa-check"></i><b>9.2</b> Inspecting Data for Equal Variances</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#mean-variance-plot"><i class="fa fa-check"></i><b>9.2.1</b> Mean-Variance Plot</a></li>
<li class="chapter" data-level="9.2.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#homogeneity-of-variance-tests"><i class="fa fa-check"></i><b>9.2.2</b> Homogeneity of Variance Tests</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#dealing-with-messy-data"><i class="fa fa-check"></i><b>9.3</b> Dealing with Messy Data</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#outliers"><i class="fa fa-check"></i><b>9.3.1</b> Outliers</a></li>
<li class="chapter" data-level="9.3.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#non-normal-data-and-unequal-variances"><i class="fa fa-check"></i><b>9.3.2</b> Non-normal Data and Unequal Variances</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>9.4</b> Dealing with Missing Data</a></li>
<li class="chapter" data-level="9.5" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#summary"><i class="fa fa-check"></i><b>9.5</b> Summary</a></li>
<li class="chapter" data-level="9.6" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-visual-data-inspection"><i class="fa fa-check"></i><b>9.6</b> Exercise: Visual Data Inspection</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-1-2"><i class="fa fa-check"></i><b>9.6.1</b> Case Study 1</a></li>
<li class="chapter" data-level="9.6.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#histogram"><i class="fa fa-check"></i><b>9.6.2</b> Histogram</a></li>
<li class="chapter" data-level="9.6.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#rank-percentile"><i class="fa fa-check"></i><b>9.6.3</b> Rank-Percentile</a></li>
<li class="chapter" data-level="9.6.4" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-2-2"><i class="fa fa-check"></i><b>9.6.4</b> Case Study 2</a></li>
<li class="chapter" data-level="9.6.5" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#box-plot"><i class="fa fa-check"></i><b>9.6.5</b> Box Plot</a></li>
<li class="chapter" data-level="9.6.6" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-9"><i class="fa fa-check"></i><b>9.6.6</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-identifying-unequal-variances"><i class="fa fa-check"></i><b>9.7</b> Exercise: Identifying Unequal Variances"</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-grape-colapsis-in-seed-corn"><i class="fa fa-check"></i><b>9.7.1</b> Case Study: Grape Colapsis in Seed Corn</a></li>
<li class="chapter" data-level="9.7.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-pigweed-height"><i class="fa fa-check"></i><b>9.7.2</b> Practice: Pigweed Height</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-transforming-and-analyzing-data"><i class="fa fa-check"></i><b>9.8</b> Exercise: Transforming and Analyzing Data</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-grape-colapsis-in-seed-corn-1"><i class="fa fa-check"></i><b>9.8.1</b> Case Study: Grape Colapsis in Seed Corn</a></li>
<li class="chapter" data-level="9.8.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-pigweed-height-1"><i class="fa fa-check"></i><b>9.8.2</b> Practice: Pigweed Height</a></li>
<li class="chapter" data-level="9.8.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-pigweed-biomass"><i class="fa fa-check"></i><b>9.8.3</b> Practice: Pigweed Biomass</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#exercise-imputing-missing-data"><i class="fa fa-check"></i><b>9.9</b> Exercise: Imputing Missing Data</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#case-study-wheat-genotype-trial"><i class="fa fa-check"></i><b>9.9.1</b> Case Study: Wheat Genotype Trial</a></li>
<li class="chapter" data-level="9.9.2" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-1-1"><i class="fa fa-check"></i><b>9.9.2</b> Practice 1</a></li>
<li class="chapter" data-level="9.9.3" data-path="messy-and-missing-data.html"><a href="messy-and-missing-data.html#practice-2-1"><i class="fa fa-check"></i><b>9.9.3</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html"><i class="fa fa-check"></i><b>10</b> Correlation and Simple Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#correlation"><i class="fa fa-check"></i><b>10.1</b> Correlation</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-cucumber"><i class="fa fa-check"></i><b>10.1.1</b> Case Study: Cucumber</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#correlation-1"><i class="fa fa-check"></i><b>10.2</b> Correlation</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#how-is-r-calcuated-optional-reading"><i class="fa fa-check"></i><b>10.2.1</b> How Is r Calcuated (optional reading)</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#regression"><i class="fa fa-check"></i><b>10.3</b> Regression</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-6"><i class="fa fa-check"></i><b>10.3.1</b> Case Study</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#linear-equation"><i class="fa fa-check"></i><b>10.3.2</b> Linear Equation</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#calculating-the-regression-equation"><i class="fa fa-check"></i><b>10.3.3</b> Calculating the Regression Equation</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#least-squares-estimate"><i class="fa fa-check"></i><b>10.3.4</b> Least-Squares Estimate</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#significance-of-coefficients"><i class="fa fa-check"></i><b>10.3.5</b> Significance of Coefficients</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#analysis-of-variance-6"><i class="fa fa-check"></i><b>10.3.6</b> Analysis of Variance</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#measuring-model-fit-with-r-square"><i class="fa fa-check"></i><b>10.3.7</b> Measuring Model Fit with R-Square</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#checking-whether-the-linear-model-is-appropriate"><i class="fa fa-check"></i><b>10.3.8</b> Checking whether the Linear Model is Appropriate</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#extrapolation"><i class="fa fa-check"></i><b>10.4</b> Extrapolation</a></li>
<li class="chapter" data-level="10.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#exercise-sccatterplots-and-regression"><i class="fa fa-check"></i><b>10.5</b> Exercise: Sccatterplots and Regression</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-corn-data"><i class="fa fa-check"></i><b>10.5.1</b> Case Study: Corn Data</a></li>
<li class="chapter" data-level="10.5.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-1-2"><i class="fa fa-check"></i><b>10.5.2</b> Practice 1</a></li>
<li class="chapter" data-level="10.5.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-2-2"><i class="fa fa-check"></i><b>10.5.3</b> Practice 2</a></li>
<li class="chapter" data-level="10.5.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-3-1"><i class="fa fa-check"></i><b>10.5.4</b> Practice 3</a></li>
<li class="chapter" data-level="10.5.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-4-1"><i class="fa fa-check"></i><b>10.5.5</b> Practice 4</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#exercise-simple-linear-regression"><i class="fa fa-check"></i><b>10.6</b> Exercise: Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-corn-allometry"><i class="fa fa-check"></i><b>10.6.1</b> Case Study: Corn Allometry</a></li>
<li class="chapter" data-level="10.6.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#fitting-the-regression-model"><i class="fa fa-check"></i><b>10.6.2</b> Fitting the regression model</a></li>
<li class="chapter" data-level="10.6.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#examining-the-residuals"><i class="fa fa-check"></i><b>10.6.3</b> Examining the residuals</a></li>
<li class="chapter" data-level="10.6.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#viewing-the-model-coefficients"><i class="fa fa-check"></i><b>10.6.4</b> Viewing the Model Coefficients</a></li>
<li class="chapter" data-level="10.6.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#more-measures-of-model-fit"><i class="fa fa-check"></i><b>10.6.5</b> More measures of model fit</a></li>
<li class="chapter" data-level="10.6.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-1-3"><i class="fa fa-check"></i><b>10.6.6</b> Practice 1</a></li>
<li class="chapter" data-level="10.6.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-2-3"><i class="fa fa-check"></i><b>10.6.7</b> Practice 2</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#exercise-making-predictions-from-regression-models."><i class="fa fa-check"></i><b>10.7</b> Exercise: Making Predictions from Regression Models.</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#case-study-7"><i class="fa fa-check"></i><b>10.7.1</b> Case Study</a></li>
<li class="chapter" data-level="10.7.2" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#creating-and-testing-our-model"><i class="fa fa-check"></i><b>10.7.2</b> Creating and Testing our Model</a></li>
<li class="chapter" data-level="10.7.3" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#visualizing-the-regression-model"><i class="fa fa-check"></i><b>10.7.3</b> Visualizing the Regression Model</a></li>
<li class="chapter" data-level="10.7.4" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#making-predictions-with-the-regression-model"><i class="fa fa-check"></i><b>10.7.4</b> Making Predictions with the Regression Model</a></li>
<li class="chapter" data-level="10.7.5" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-1-4"><i class="fa fa-check"></i><b>10.7.5</b> Practice 1</a></li>
<li class="chapter" data-level="10.7.6" data-path="correlation-and-simple-regression.html"><a href="correlation-and-simple-regression.html#practice-2-4"><i class="fa fa-check"></i><b>10.7.6</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html"><i class="fa fa-check"></i><b>11</b> Nonlinear Relationships and Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#multiplie-linear-regression"><i class="fa fa-check"></i><b>11.1</b> Multiplie Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-modelling-yield-by-county"><i class="fa fa-check"></i><b>11.1.1</b> Case Study: Modelling Yield by County</a></li>
<li class="chapter" data-level="11.1.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#beware-of-bloated-models"><i class="fa fa-check"></i><b>11.1.2</b> Beware of Bloated Models</a></li>
<li class="chapter" data-level="11.1.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#methods-for-avoiding-bloated-models"><i class="fa fa-check"></i><b>11.1.3</b> Methods for Avoiding Bloated Models</a></li>
<li class="chapter" data-level="11.1.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#tunning-and-comparing-models"><i class="fa fa-check"></i><b>11.1.4</b> Tunning and Comparing Models</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#nonlinear-relationships"><i class="fa fa-check"></i><b>11.2</b> Nonlinear Relationships</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-nonlinear-responses-with-linear-regression"><i class="fa fa-check"></i><b>11.2.1</b> Fitting Nonlinear Responses with Linear Regression</a></li>
<li class="chapter" data-level="11.2.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-nonlinear-responses-with-nonlinear-regression"><i class="fa fa-check"></i><b>11.2.2</b> Fitting Nonlinear Responses with Nonlinear Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#summary-1"><i class="fa fa-check"></i><b>11.3</b> Summary</a></li>
<li class="chapter" data-level="11.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-multiple-linear-regression"><i class="fa fa-check"></i><b>11.4</b> Exercise: Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-country-corn-yields"><i class="fa fa-check"></i><b>11.4.1</b> Case Study: Country Corn Yields</a></li>
<li class="chapter" data-level="11.4.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#fitting-the-model"><i class="fa fa-check"></i><b>11.4.2</b> Fitting the Model</a></li>
<li class="chapter" data-level="11.4.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#inspecting-the-model"><i class="fa fa-check"></i><b>11.4.3</b> Inspecting the Model</a></li>
<li class="chapter" data-level="11.4.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-thompson-corn-data"><i class="fa fa-check"></i><b>11.4.4</b> Practice: Thompson Corn Data</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-avoiding-bloated-models"><i class="fa fa-check"></i><b>11.5</b> Exercise: Avoiding Bloated Models</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-8"><i class="fa fa-check"></i><b>11.5.1</b> Case Study</a></li>
<li class="chapter" data-level="11.5.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#covariance-matrix"><i class="fa fa-check"></i><b>11.5.2</b> Covariance Matrix</a></li>
<li class="chapter" data-level="11.5.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#partial-correlation-1"><i class="fa fa-check"></i><b>11.5.3</b> Partial Correlation</a></li>
<li class="chapter" data-level="11.5.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#cross-validation-1"><i class="fa fa-check"></i><b>11.5.4</b> Cross-Validation</a></li>
<li class="chapter" data-level="11.5.5" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-thompson-corn-data-1"><i class="fa fa-check"></i><b>11.5.5</b> Practice: Thompson Corn Data</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-tuning-the-model"><i class="fa fa-check"></i><b>11.6</b> Exercise: Tuning the Model</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-9"><i class="fa fa-check"></i><b>11.6.1</b> Case Study</a></li>
<li class="chapter" data-level="11.6.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#tuning-the-model"><i class="fa fa-check"></i><b>11.6.2</b> Tuning the Model</a></li>
<li class="chapter" data-level="11.6.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-10"><i class="fa fa-check"></i><b>11.6.3</b> Practice</a></li>
<li class="chapter" data-level="11.6.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-11"><i class="fa fa-check"></i><b>11.6.4</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#exercise-nonlinear-regression"><i class="fa fa-check"></i><b>11.7</b> Exercise: Nonlinear Regression</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-1-monomolecular-data"><i class="fa fa-check"></i><b>11.7.1</b> Case Study 1: Monomolecular Data</a></li>
<li class="chapter" data-level="11.7.2" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#case-study-2-logistic-data"><i class="fa fa-check"></i><b>11.7.2</b> Case Study 2: Logistic Data</a></li>
<li class="chapter" data-level="11.7.3" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-1-5"><i class="fa fa-check"></i><b>11.7.3</b> Practice 1</a></li>
<li class="chapter" data-level="11.7.4" data-path="nonlinear-relationships-and-multiple-linear-regression.html"><a href="nonlinear-relationships-and-multiple-linear-regression.html#practice-2-5"><i class="fa fa-check"></i><b>11.7.4</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="spatial-statistics.html"><a href="spatial-statistics.html"><i class="fa fa-check"></i><b>12</b> Spatial Statistics</a>
<ul>
<li class="chapter" data-level="12.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#projection-general"><i class="fa fa-check"></i><b>12.1</b> Projection (General)</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#wgs-84-epsg-4236"><i class="fa fa-check"></i><b>12.1.1</b> WGS 84 (EPSG: 4236)</a></li>
<li class="chapter" data-level="12.1.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#mercator-epsg-3857"><i class="fa fa-check"></i><b>12.1.2</b> Mercator (EPSG: 3857)</a></li>
<li class="chapter" data-level="12.1.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#us-national-atlas-equal-area-epsg-2163"><i class="fa fa-check"></i><b>12.1.3</b> US National Atlas Equal Area (EPSG: 2163)</a></li>
<li class="chapter" data-level="12.1.4" data-path="spatial-statistics.html"><a href="spatial-statistics.html#utm-zone-11n-epsg-2955"><i class="fa fa-check"></i><b>12.1.4</b> UTM Zone 11N (EPSG: 2955)</a></li>
<li class="chapter" data-level="12.1.5" data-path="spatial-statistics.html"><a href="spatial-statistics.html#projection-summary"><i class="fa fa-check"></i><b>12.1.5</b> Projection Summary</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#shape-files"><i class="fa fa-check"></i><b>12.2</b> Shape Files</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-soybean-yield-in-iowa"><i class="fa fa-check"></i><b>12.2.1</b> Case Study: Soybean Yield in Iowa</a></li>
<li class="chapter" data-level="12.2.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#ssurgo"><i class="fa fa-check"></i><b>12.2.2</b> SSURGO</a></li>
<li class="chapter" data-level="12.2.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#operations-with-shapes"><i class="fa fa-check"></i><b>12.2.3</b> Operations with Shapes</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#rasters"><i class="fa fa-check"></i><b>12.3</b> Rasters</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#interpolation"><i class="fa fa-check"></i><b>12.3.1</b> Interpolation</a></li>
<li class="chapter" data-level="12.3.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#kriging"><i class="fa fa-check"></i><b>12.3.2</b> Kriging</a></li>
<li class="chapter" data-level="12.3.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#operations-on-kriged-data"><i class="fa fa-check"></i><b>12.3.3</b> Operations on Kriged Data</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="spatial-statistics.html"><a href="spatial-statistics.html#exercise-shape-files"><i class="fa fa-check"></i><b>12.4</b> Exercise: Shape Files</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-10"><i class="fa fa-check"></i><b>12.4.1</b> Case Study</a></li>
<li class="chapter" data-level="12.4.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#practice-12"><i class="fa fa-check"></i><b>12.4.2</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="spatial-statistics.html"><a href="spatial-statistics.html#exercise-ssurgo"><i class="fa fa-check"></i><b>12.5</b> Exercise: SSURGO</a></li>
<li class="chapter" data-level="12.6" data-path="spatial-statistics.html"><a href="spatial-statistics.html#exercise-rasters"><i class="fa fa-check"></i><b>12.6</b> Exercise: Rasters</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="spatial-statistics.html"><a href="spatial-statistics.html#case-study-soil-test-data"><i class="fa fa-check"></i><b>12.6.1</b> Case Study: Soil Test Data</a></li>
<li class="chapter" data-level="12.6.2" data-path="spatial-statistics.html"><a href="spatial-statistics.html#practice-1-6"><i class="fa fa-check"></i><b>12.6.2</b> Practice 1</a></li>
<li class="chapter" data-level="12.6.3" data-path="spatial-statistics.html"><a href="spatial-statistics.html#practice-2-6"><i class="fa fa-check"></i><b>12.6.3</b> Practice 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>13</b> Machine Learning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="machine-learning.html"><a href="machine-learning.html#machine-learning-1"><i class="fa fa-check"></i><b>13.1</b> Machine Learning</a></li>
<li class="chapter" data-level="13.2" data-path="machine-learning.html"><a href="machine-learning.html#cluster-analyses"><i class="fa fa-check"></i><b>13.2</b> Cluster Analyses</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="machine-learning.html"><a href="machine-learning.html#case-study-grouping-midwestern-environments"><i class="fa fa-check"></i><b>13.2.1</b> Case Study: Grouping Midwestern Environments</a></li>
<li class="chapter" data-level="13.2.2" data-path="machine-learning.html"><a href="machine-learning.html#scaling"><i class="fa fa-check"></i><b>13.2.2</b> Scaling</a></li>
<li class="chapter" data-level="13.2.3" data-path="machine-learning.html"><a href="machine-learning.html#clustering-animation"><i class="fa fa-check"></i><b>13.2.3</b> Clustering Animation</a></li>
<li class="chapter" data-level="13.2.4" data-path="machine-learning.html"><a href="machine-learning.html#county-cluster-analysis"><i class="fa fa-check"></i><b>13.2.4</b> County Cluster Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="machine-learning.html"><a href="machine-learning.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>13.3</b> k-Nearest-Neighbors</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="machine-learning.html"><a href="machine-learning.html#case-study-guessing-county-yields-based-on-environmental-similarity"><i class="fa fa-check"></i><b>13.3.1</b> Case Study: Guessing County Yields based on Environmental Similarity</a></li>
<li class="chapter" data-level="13.3.2" data-path="machine-learning.html"><a href="machine-learning.html#scaling-1"><i class="fa fa-check"></i><b>13.3.2</b> Scaling</a></li>
<li class="chapter" data-level="13.3.3" data-path="machine-learning.html"><a href="machine-learning.html#k-nearest-neighbor-animation"><i class="fa fa-check"></i><b>13.3.3</b> k-Nearest-Neighbor Animation</a></li>
<li class="chapter" data-level="13.3.4" data-path="machine-learning.html"><a href="machine-learning.html#choosing-k"><i class="fa fa-check"></i><b>13.3.4</b> Choosing <span class="math inline">\(k\)</span></a></li>
<li class="chapter" data-level="13.3.5" data-path="machine-learning.html"><a href="machine-learning.html#model-cross-validation"><i class="fa fa-check"></i><b>13.3.5</b> Model Cross-Validation</a></li>
<li class="chapter" data-level="13.3.6" data-path="machine-learning.html"><a href="machine-learning.html#yield-prediction-with-nearest-neighbor-analysis"><i class="fa fa-check"></i><b>13.3.6</b> Yield Prediction with Nearest Neighbor Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="machine-learning.html"><a href="machine-learning.html#classification-trees"><i class="fa fa-check"></i><b>13.4</b> Classification Trees</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="machine-learning.html"><a href="machine-learning.html#features"><i class="fa fa-check"></i><b>13.4.1</b> Features</a></li>
<li class="chapter" data-level="13.4.2" data-path="machine-learning.html"><a href="machine-learning.html#quantitative-categorical-data"><i class="fa fa-check"></i><b>13.4.2</b> Quantitative (Categorical) Data</a></li>
<li class="chapter" data-level="13.4.3" data-path="machine-learning.html"><a href="machine-learning.html#quanatitiative-continuous-data"><i class="fa fa-check"></i><b>13.4.3</b> Quanatitiative (Continuous) Data</a></li>
<li class="chapter" data-level="13.4.4" data-path="machine-learning.html"><a href="machine-learning.html#overfitting-1"><i class="fa fa-check"></i><b>13.4.4</b> Overfitting</a></li>
<li class="chapter" data-level="13.4.5" data-path="machine-learning.html"><a href="machine-learning.html#cross-validation-2"><i class="fa fa-check"></i><b>13.4.5</b> Cross Validation</a></li>
<li class="chapter" data-level="13.4.6" data-path="machine-learning.html"><a href="machine-learning.html#random-forest"><i class="fa fa-check"></i><b>13.4.6</b> Random Forest</a></li>
<li class="chapter" data-level="13.4.7" data-path="machine-learning.html"><a href="machine-learning.html#feature-importance"><i class="fa fa-check"></i><b>13.4.7</b> Feature Importance</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="machine-learning.html"><a href="machine-learning.html#summary-2"><i class="fa fa-check"></i><b>13.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html"><i class="fa fa-check"></i><b>14</b> Putting it all Together</a>
<ul>
<li class="chapter" data-level="14.1" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-1-yield-map-population-summary-and-z-distribution"><i class="fa fa-check"></i><b>14.1</b> Scenario 1: Yield Map (Population Summary and Z-Distribution)</a></li>
<li class="chapter" data-level="14.2" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-2-yield-estimate-sampling-t-distribution"><i class="fa fa-check"></i><b>14.2</b> Scenario 2: Yield Estimate (Sampling t-Distribution)</a></li>
<li class="chapter" data-level="14.3" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-3-side-by-side-t-test"><i class="fa fa-check"></i><b>14.3</b> Scenario 3: Side-By-Side (t-Test)</a></li>
<li class="chapter" data-level="14.4" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-4-fungicide-trial-anova-crd-or-rcbd"><i class="fa fa-check"></i><b>14.4</b> Scenario 4: Fungicide Trial (ANOVA CRD or RCBD)</a></li>
<li class="chapter" data-level="14.5" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-5-hybrid-response-to-fungicide-trial-anova-factorial-or-split-plot"><i class="fa fa-check"></i><b>14.5</b> Scenario 5: Hybrid Response to Fungicide Trial (ANOVA Factorial or Split Plot)</a></li>
<li class="chapter" data-level="14.6" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-6-foliar-rate-response-trial-linear-or-non-linear-regression"><i class="fa fa-check"></i><b>14.6</b> Scenario 6: Foliar Rate-Response Trial (Linear or Non-Linear Regression)</a></li>
<li class="chapter" data-level="14.7" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-7-application-map-shapefiles-and-rasters"><i class="fa fa-check"></i><b>14.7</b> Scenario 7: Application Map (Shapefiles and Rasters)</a></li>
<li class="chapter" data-level="14.8" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#scenario-8-yield-prediction-multiple-linear-regression-and-other-predictive-models"><i class="fa fa-check"></i><b>14.8</b> Scenario 8: Yield Prediction (Multiple Linear Regression and other Predictive Models)</a></li>
<li class="chapter" data-level="14.9" data-path="putting-it-all-together.html"><a href="putting-it-all-together.html#summary-3"><i class="fa fa-check"></i><b>14.9</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for Agricultural Professionals</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="two-treatment-comparisons" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Two-Treatment Comparisons</h1>
<p>Until now, we have worked with a single population. To recap our progress:
- In Unit 1, we defined a population. We learned it was the complete group of individuals which we wanted to describe or for which we wanted to make a prediction. We learned how to describe the center of this population with the population mean, and how to describe its spread using the sum of squares, variance, and standard deviation.
- In Unit 2, used the normal distributionto describe the pattern with which individuals are spread in many populations: individuals with values closer to the population mean were expected to be observed much more frequently that individuals with values that were more extreme. We learned to use probability toe quantify the likelihood of encountering an invididual within a particular range of values.
- In Unit 3, we used samples, subsets from a population, in place of measuring each individual in that population. We saw how sample means were distributed normally, from both normally- and non-normally distributed populations. The standard error was used to describe the spread of individual samples around the sample mean. The distribution of sample means was described by the t-distribution, which was shorter and wider when the number of samples was low, and taller and narrower when the number of samples was greater.</p>
<div id="side-by-side-trials" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Side-by-Side Trials</h2>
<p>In this unit, we will finally put our statistical knowledge to work to test treatment differences. We will work with a simple but important experimental design – the two-treatment comparison. Here in Ohio, this is referred to as a “side-by-side” trial, but you may have a different term for it where you work. If you work for or in support of an agronomy retailer, you have probably conducted these trials. Typically, you would split one or more fields into treated and untreated fields. For example, you might “stripe” and individual field with treated and untreated areas:</p>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Or, you might divide multiple fields in half like this:</p>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>In either case, however, a side-by-side deals with two treatments and can be easily analyzed using a t-test. In these next two units we will compare different designs for side-by-side (or paired) trials, use Excel and R to randomly assign treatments, understand how the t-distribution allows us to test for significance, and run these tests in R.</p>
</div>
<div id="blocked-design" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Blocked Design</h2>
<p>In Unit 1 we learned the hallmarks of a designed trial are the randomzation and replication of treatments. Each treatment should be observed several times in different experimental units. Often in our work “experimental unit” is a fancy word for a plot, half a field, or a pot.</p>
<p>Observing the treatment several times has two benefits. First, the average of those observations – the sample average – wil likely be closer to the true population average for that treatment than the individual observations. Second, variation among the observations can be used to give us a sense how much environmental factors outside, in contrast with our treatment, cause our observations to vary.</p>
<p>It is also important to randomize treatments in order to avoid intentional or unintentional biases that might skew our interpretation of results. For example, one treatment might be biased by always putting it to the north of another treatment or, more insiduously, always putting it in the better half of a field. Deliberate randomization reduces the probability of either scenario.</p>
<p>That said, reality often intervenes intervenes. Soil types change across a field, as do microclimates around field edges, management histories, etc. Though randomization will reduce the likelihood that treatments are concentrated in one of these areas, it may not result in as even a distribution of treatments across the experimental area as we would like. Even with randomization, we could conceivably with all the treatments in one half of the field:</p>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Or, if we are using multiple fields, both halves of a field could receive the same treatment in a randomized design</p>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Blocked experimental designs, place a restriction on the random assignment of treatments to plots. Instead of assigning treatments randomly within a field or across a state. We instead force both treatments to occur within a field section or in the same field, so that our treatment maps look more those we showed in the first two figures of this unit.</p>
<p>Here is another way to think about this. Our statistical test this week is based on comparing two populations. Each population will receive a different treatment. We want to design our experiment so that aside from the treatment, the two populations are as identical as possible. The blocked approach, in general, helps create two populations that are similar.</p>
</div>
<div id="case-study-2" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Case Study</h2>
<p>An in-furrow corn starter (6-24-6 plus proprietary micronutrients) was tested against a control (no -starter) in a trial in western Ohio. Treatments were blocked (paired) so that each treatment occurred once per block. Plot numbers are given on the x-axis of the map below. There were 10 blocks. The data are in a data.frame named “corn_starter.”</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="two-treatment-comparisons.html#cb45-1" aria-hidden="true" tabindex="-1"></a>corn_starter <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/corn_starter.csv&quot;</span>)</span></code></pre></div>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Examine the corn_starter data.frame using the “head” function.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="two-treatment-comparisons.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(corn_starter)</span></code></pre></div>
<pre><code>##   block plot treatment yield
## 1     1   11   Starter 193.4
## 2     1   12   Control 194.2
## 3     2   21   Starter 192.2
## 4     2   22   Control 189.0
## 5     3   31   Control 193.8
## 6     3   32   Starter 194.2</code></pre>
<p>Note the column headings: “trt” refers to the treatment level (Control or Starter) and “value” refers to the measured yield.</p>
<p>Let’s make a quick histogram plot of the data using ggplot. For the first time, in this unit, we are working with two populations: one which received no starter (the control), and another which received starter. So we will have separate histograms for both populations.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="two-treatment-comparisons.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> corn_starter, <span class="fu">aes</span>(<span class="at">x=</span>yield)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="two-treatment-comparisons.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb48-3"><a href="two-treatment-comparisons.html#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>treatment)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/corn_starter_bar_plot-1.png" width="672" /></p>
<p>In the above code, ggplot launches the function to plot our data. Also on the first line, “aes” specifies the “aesthetics” to be plotted – these are the variable(s) that define where objects are positioned in the plot. In this case, yield determines which bin an observation is placed into, so x=value.</p>
<p>The next line tells R to draw a histogram.</p>
<p>The last line tells R to construct a series of plots, one for each level of treatment. This way, we can compare the distribution of the Control population with that of the Starter population.</p>
<p>The mean yield of the population that population that received starter is greater than the center of the population that received the control (no starter).</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="two-treatment-comparisons.html#cb50-1" aria-hidden="true" tabindex="-1"></a>corn_starter <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="two-treatment-comparisons.html#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treatment) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="two-treatment-comparisons.html#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">yield =</span> <span class="fu">mean</span>(yield))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   treatment yield
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Control    190.
## 2 Starter    196.</code></pre>
<p>Another way to look at this would be to create a new population from the differences between starter and control within each pair.</p>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>This can be confusing, so let’s slow it down. We created a new population by subtracting the yield of the control plot from the yield of the starter plot in each pair. In this new population, individuals with a positive value indicate a block where the starter outyielded the control. Individuals with a negative value indicate a block where the control outyielded the starter. We will now work with this new population of differences.</p>
<p>We see most of the individuals in this new population are greater than 0. The population mean is 5.6 bushels/acre. What we want to know is: given the mean we observed (5.59 bushels/acre) and the distribution of this population, what is the probability, were we to repeat the trial, that the population mean would be zero.</p>
<p>A population mean of zero would mean the starter yield and control yield were the same, i.e. there is no difference between the starter and control.</p>
</div>
<div id="confidence-interval-1" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Confidence Interval</h2>
<p>We can use a confidence interval to determine whether the range of values we are likely to observe includes zero. Recall, to calculate the confidence interval we need two values: the minimal t-value that is associated with our degrees of freedom and encompases 95% of our population, and the standard error of the difference.</p>
<p>We calculate the minimal t-value using the qt function in R.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="two-treatment-comparisons.html#cb52-1" aria-hidden="true" tabindex="-1"></a>min_t <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df=</span><span class="dv">9</span>)</span></code></pre></div>
<p>Remember, degrees of freedom is equal to n-1. Our new population has 10 degrees of freedom, thereofre, df equals 9 above.</p>
<p>We also need to know the standard error of the population. Given our population is composed of treatment differences, we will call this statistic the <em>standard error of the difference</em>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="two-treatment-comparisons.html#cb53-1" aria-hidden="true" tabindex="-1"></a>sd <span class="ot">=</span> <span class="fu">sd</span>(corn_differences<span class="sc">$</span>difference)</span>
<span id="cb53-2"><a href="two-treatment-comparisons.html#cb53-2" aria-hidden="true" tabindex="-1"></a>sed <span class="ot">=</span> sd<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">10</span>)</span>
<span id="cb53-3"><a href="two-treatment-comparisons.html#cb53-3" aria-hidden="true" tabindex="-1"></a>pop_mean <span class="ot">=</span> <span class="fu">mean</span>(corn_differences<span class="sc">$</span>difference)</span></code></pre></div>
<p>In the code above, we first calculated the standard deviation, sd, of of our differences. We divided the standard deviation by the square root of the number of observations to get the standard error of the difference. Our population mean is 5.59 and the standard error of the difference is about 1.71 We additionally calculated pop_mean, the mean of our population.</p>
<p>We can now calculate the confidence interval, using min_t and sed:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="two-treatment-comparisons.html#cb54-1" aria-hidden="true" tabindex="-1"></a>upper_limit <span class="ot">=</span> pop_mean <span class="sc">+</span> (min_t <span class="sc">*</span> sed)</span>
<span id="cb54-2"><a href="two-treatment-comparisons.html#cb54-2" aria-hidden="true" tabindex="-1"></a>lower_limit <span class="ot">=</span> pop_mean <span class="sc">-</span> (min_t <span class="sc">*</span> sed)</span>
<span id="cb54-3"><a href="two-treatment-comparisons.html#cb54-3" aria-hidden="true" tabindex="-1"></a>CI <span class="ot">=</span> <span class="fu">paste</span>(lower_limit, upper_limit, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb54-4"><a href="two-treatment-comparisons.html#cb54-4" aria-hidden="true" tabindex="-1"></a>CI</span></code></pre></div>
<pre><code>## [1] &quot;1.72421086829983,9.45578913170016&quot;</code></pre>
<p>The 95% confidence interval ranges from 1.72 to 9.46 bushels per acre and, notably, does not include zero. Since zero is outside the 95% confidence interval, there is greater than a 95% probability the population mean is not equal to zero. Another way of saying this is there is less than a 5% probability that the population mean is equal to zero. Or, finally, the population mean is significantly different from zero at the 5% (or 0.05) level.</p>
<p>Going our population was composed of the difference of starter and control, we can say the starter effect is significantly different from the control at the 5% level.</p>
</div>
<div id="t-test" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> T-Test</h2>
<p>An alternative to the confidence interval is the t-test. The first step of the t-test is to calculate our observed t-value:</p>
<p><span class="math display">\[ t = \frac{\bar{x} - \mu}{SED} \]</span>
Where <span class="math inline">\(\bar{x}\)</span> is the observed population mean, <span class="math inline">\(\mu\)</span> is the hypothesized population mean (usually 0, meaning no treatment difference), and <span class="math inline">\(SED\)</span> is the standard error of the difference.</p>
<p>In our example above:</p>
<p><span class="math display">\[ t = \frac{5.59 - 0}{1.71} = 3.27\]</span></p>
<p>Our observed t-value is about 3.27. If there were no difference between the starter and the control, of course, t would be equal to zero. So there is a difference between our observed mean and zero of <span class="math inline">\(t=3.27\)</span>. Using R, we can quickly calculate the probability of observing a value <span class="math inline">\(t=3.27\)</span> above – or below our population mean of 5.59.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="two-treatment-comparisons.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastGraph)</span>
<span id="cb56-2"><a href="two-treatment-comparisons.html#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shadeDist</span>(<span class="at">xshade=</span><span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.27</span>, <span class="fl">3.27</span>), <span class="st">&quot;dt&quot;</span>, <span class="at">parm2 =</span> <span class="dv">9</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="04-Two-Treatment-Comparisons_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Note that this time with this function we used the argument “lower.tail=TRUE.” This tells R to calculate the probability of values futher than <span class="math inline">\(t=3.27\)</span> both above and below the mean.</p>
<p>Again there were 10 observed differences in our population, so there were 9 degrees of freedom. The value that is returned is the probability the population mean is actually zero, given the population mean. The probability of this t-value (sometimes abbreviated as <span class="math inline">\(Pr \ge \lvert t \lvert\)</span>) is very low, less tan 0.01, or 1%.</p>
</div>
<div id="exercise-randomizing-plots" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Exercise: Randomizing Plots</h2>
<p>Plot randomzation is a very important – and very easy to do with R. Below we will learn how to randomize plots for side-by-side trials in which plots are paired.</p>
<div id="example-1" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Example 1</h3>
<p>For our first example, we create an experimental design with 4 replications of treatments “A” and “B.” We will use the agricolae package to do this. The agricolae package is</p>
</div>
<div id="the-agricolae-package" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> The Agricolae Package</h3>
<p>To randomize two-treatment trials with paired treatments, we will use the “agricolae” package of R.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="two-treatment-comparisons.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span></code></pre></div>
</div>
<div id="randomizing-the-plot" class="section level3" number="4.6.3">
<h3><span class="header-section-number">4.6.3</span> Randomizing the Plot</h3>
<p>We will use the “design.rcbd” function from the agricolae package. We need to supply the following arguments to this function:
- trt: a vector with treatment names
- r: the number of replications</p>
<p>We will create a vector called “treatment_names,” containing treatments “A” and “B.” We will use the argument r=4 to tell R to generate 4 blocks.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="two-treatment-comparisons.html#cb58-1" aria-hidden="true" tabindex="-1"></a>treatment_name<span class="ot">=</span><span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>)</span>
<span id="cb58-2"><a href="two-treatment-comparisons.html#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="two-treatment-comparisons.html#cb58-3" aria-hidden="true" tabindex="-1"></a>plot_plan <span class="ot">=</span> <span class="fu">design.rcbd</span>(<span class="at">trt =</span> treatment_name, <span class="at">r=</span><span class="dv">4</span>)</span></code></pre></div>
</div>
<div id="working-with-lists" class="section level3" number="4.6.4">
<h3><span class="header-section-number">4.6.4</span> Working with Lists</h3>
<p>The code above created an object called “plot_plan.” So far in R we have dealt with two kinds of objects: a data frame, which is basically a table of values, and a vector, which can be thought of as a single column of numbers. “treatment_names” above is an example of a vector.</p>
<p>“plot_plan” is a third type of R object, called a “list.” A list is a collection of other R objects. It can contain multiple data frames, vectors, single values, etc. A list is a very useful way to bundle up information, but they can be a little tricky to unpack.</p>
<p>If we just run plot_plan below, we will get two windows. One will list all of the objects in the list. The second window will show the plot plan.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="two-treatment-comparisons.html#cb59-1" aria-hidden="true" tabindex="-1"></a>plot_plan</span></code></pre></div>
<pre><code>## $parameters
## $parameters$design
## [1] &quot;rcbd&quot;
## 
## $parameters$trt
## [1] &quot;A&quot; &quot;B&quot;
## 
## $parameters$r
## [1] 4
## 
## $parameters$serie
## [1] 2
## 
## $parameters$seed
## [1] -74522394
## 
## $parameters$kinds
## [1] &quot;Super-Duper&quot;
## 
## $parameters[[7]]
## [1] TRUE
## 
## 
## $sketch
##      [,1] [,2]
## [1,] &quot;A&quot;  &quot;B&quot; 
## [2,] &quot;B&quot;  &quot;A&quot; 
## [3,] &quot;A&quot;  &quot;B&quot; 
## [4,] &quot;B&quot;  &quot;A&quot; 
## 
## $book
##   plots block treatment_name
## 1   101     1              A
## 2   102     1              B
## 3   201     2              B
## 4   202     2              A
## 5   301     3              A
## 6   302     3              B
## 7   401     4              B
## 8   402     4              A</code></pre>
<p>We can access this information more directly. If we type “plot_plan$sketch,” we get a plot map of sorts.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="two-treatment-comparisons.html#cb61-1" aria-hidden="true" tabindex="-1"></a>plot_plan<span class="sc">$</span>sketch</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,] &quot;A&quot;  &quot;B&quot; 
## [2,] &quot;B&quot;  &quot;A&quot; 
## [3,] &quot;A&quot;  &quot;B&quot; 
## [4,] &quot;B&quot;  &quot;A&quot;</code></pre>
<p>If we type “plot_plan$book,” we get a data frame with the plots, block, and treatment_names.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="two-treatment-comparisons.html#cb63-1" aria-hidden="true" tabindex="-1"></a>plot_plan<span class="sc">$</span>book</span></code></pre></div>
<pre><code>##   plots block treatment_name
## 1   101     1              A
## 2   102     1              B
## 3   201     2              B
## 4   202     2              A
## 5   301     3              A
## 6   302     3              B
## 7   401     4              B
## 8   402     4              A</code></pre>
</div>
<div id="example-2" class="section level3" number="4.6.5">
<h3><span class="header-section-number">4.6.5</span> Example 2</h3>
<p>In a field trial, we wish to compare the biomass of two fiber hemp varieties, “Jerry” and “Bob.” We wish to design a paired experimental design with 10 replications.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="two-treatment-comparisons.html#cb65-1" aria-hidden="true" tabindex="-1"></a>hemp_variety <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Jerry&quot;</span>, <span class="st">&quot;Bob&quot;</span>)</span>
<span id="cb65-2"><a href="two-treatment-comparisons.html#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="two-treatment-comparisons.html#cb65-3" aria-hidden="true" tabindex="-1"></a>hemp_plot_plan <span class="ot">=</span> <span class="fu">design.rcbd</span>(<span class="at">trt =</span> hemp_variety, <span class="at">r=</span><span class="dv">10</span>)</span></code></pre></div>
<p>Here is the plot layout:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="two-treatment-comparisons.html#cb66-1" aria-hidden="true" tabindex="-1"></a>hemp_plot_plan<span class="sc">$</span>sketch</span></code></pre></div>
<pre><code>##       [,1]    [,2]   
##  [1,] &quot;Jerry&quot; &quot;Bob&quot;  
##  [2,] &quot;Jerry&quot; &quot;Bob&quot;  
##  [3,] &quot;Bob&quot;   &quot;Jerry&quot;
##  [4,] &quot;Bob&quot;   &quot;Jerry&quot;
##  [5,] &quot;Bob&quot;   &quot;Jerry&quot;
##  [6,] &quot;Bob&quot;   &quot;Jerry&quot;
##  [7,] &quot;Jerry&quot; &quot;Bob&quot;  
##  [8,] &quot;Bob&quot;   &quot;Jerry&quot;
##  [9,] &quot;Jerry&quot; &quot;Bob&quot;  
## [10,] &quot;Bob&quot;   &quot;Jerry&quot;</code></pre>
<p>And here is the table we can cut and paste into our spreadsheet:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="two-treatment-comparisons.html#cb68-1" aria-hidden="true" tabindex="-1"></a>hemp_plot_plan<span class="sc">$</span>book</span></code></pre></div>
<pre><code>##    plots block hemp_variety
## 1    101     1        Jerry
## 2    102     1          Bob
## 3    201     2        Jerry
## 4    202     2          Bob
## 5    301     3          Bob
## 6    302     3        Jerry
## 7    401     4          Bob
## 8    402     4        Jerry
## 9    501     5          Bob
## 10   502     5        Jerry
## 11   601     6          Bob
## 12   602     6        Jerry
## 13   701     7        Jerry
## 14   702     7          Bob
## 15   801     8          Bob
## 16   802     8        Jerry
## 17   901     9        Jerry
## 18   902     9          Bob
## 19  1001    10          Bob
## 20  1002    10        Jerry</code></pre>
</div>
</div>
<div id="exercise-restructuring-columns-and-rows" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Exercise: Restructuring Columns and Rows</h2>
<p>As we move into the treatment comparisons part of our course, it is a good time to talk about how datasets are structured. Datasets can have a "wide structure, in which the values for different treatments are listed side by side:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="two-treatment-comparisons.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb70-2"><a href="two-treatment-comparisons.html#cb70-2" aria-hidden="true" tabindex="-1"></a>Trt_A <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb70-3"><a href="two-treatment-comparisons.html#cb70-3" aria-hidden="true" tabindex="-1"></a>Trt_B <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">8</span>)</span>
<span id="cb70-4"><a href="two-treatment-comparisons.html#cb70-4" aria-hidden="true" tabindex="-1"></a>Rep <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span>
<span id="cb70-5"><a href="two-treatment-comparisons.html#cb70-5" aria-hidden="true" tabindex="-1"></a>wide_df <span class="ot">=</span> <span class="fu">cbind</span>(Rep, Trt_A, Trt_B) <span class="sc">%&gt;%</span></span>
<span id="cb70-6"><a href="two-treatment-comparisons.html#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb70-7"><a href="two-treatment-comparisons.html#cb70-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-8"><a href="two-treatment-comparisons.html#cb70-8" aria-hidden="true" tabindex="-1"></a>wide_df</span></code></pre></div>
<pre><code>##   Rep Trt_A Trt_B
## 1   1     1     5
## 2   2     2     6
## 3   3     3     7
## 4   4     4     8</code></pre>
<p>In general, however, we prefer data be in the long form, so that each observation has its own row in the dataset. In the long form, the data above would be in three columns, the first listing the rep, the second listing the treatment, and the third listing the observed value for that treatment.</p>
<p>To get the data into the correct form, we need to pivot or transpose it: that is, certain columns will become rows, or vice versa. Fortunately, this is easy to do with the “tidyverse” package in R. The “tidyverse” and “tidy” data concept are yet another product from Hadley Wickham, who is an alumnus of Iowa State.</p>
<p>Let’s run the tidyverse package:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="two-treatment-comparisons.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>The tidyverse package introduces us to a new feature in R: pipes. Pipes are connections between lines of code that allow us to work on the same dataset with several lines of code at once. Pipes are signified with the “%&gt;%” string of code.</p>
<p>To make our dataset into the long format, we use the “gather” function to collect the four treatment rows into two rows, one identifying the treatment and the other with the value. “gather” requires three arguments: 1) the name of the column that will identify the data (often called a key), 2) the observed values, and 3) the columns to be reorganized in the key and value columns.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="two-treatment-comparisons.html#cb73-1" aria-hidden="true" tabindex="-1"></a>long_df <span class="ot">=</span> wide_df <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="two-treatment-comparisons.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(Treatment, Value, Trt_A<span class="sc">:</span>Trt_B)</span>
<span id="cb73-3"><a href="two-treatment-comparisons.html#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="two-treatment-comparisons.html#cb73-4" aria-hidden="true" tabindex="-1"></a>long_df</span></code></pre></div>
<pre><code>##   Rep Treatment Value
## 1   1     Trt_A     1
## 2   2     Trt_A     2
## 3   3     Trt_A     3
## 4   4     Trt_A     4
## 5   1     Trt_B     5
## 6   2     Trt_B     6
## 7   3     Trt_B     7
## 8   4     Trt_B     8</code></pre>
<p>In the code above, we created a new data frame, “long_df,” from the “wide_df” data frame. We used the “gather” function to create two new columns, “Treatment” and “Value,” to contain the treatment name and value associated with each observation. The pipe (“%&gt;%”) told the “gather” function to work with the “wide_df” data.</p>
<p>What if we had a long dataset that we wanted to be wide, so that each treatment had its own column? Then we would use the “spread” function. Spread takes two arguments: the column used to identify the values, and the column with the value. Again, the pipe connects the two lines of code.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="two-treatment-comparisons.html#cb75-1" aria-hidden="true" tabindex="-1"></a>wide_again_df <span class="ot">=</span> long_df <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="two-treatment-comparisons.html#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Treatment, Value)</span>
<span id="cb75-3"><a href="two-treatment-comparisons.html#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="two-treatment-comparisons.html#cb75-4" aria-hidden="true" tabindex="-1"></a>wide_again_df</span></code></pre></div>
<pre><code>##   Rep Trt_A Trt_B
## 1   1     1     5
## 2   2     2     6
## 3   3     3     7
## 4   4     4     8</code></pre>
<div id="operations-on-data" class="section level3" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> Operations on Data</h3>
<p>One of the reasons we may want to restructure data in the wide format is so we can conduct a new statistic from the original values. For example, as we learn this week, we may want to model the distribution of the differences between Trt A and Trt B. Once the data is in the wide format above, we calculcate these differences very quickly.</p>
<p>In R, we use the “mutate” function to build new columns. The argument to “mutate” is usually a mathematical formula. Say we want to cacluate the differences, row by row, between Trt A and Trt B. We would use the following mutate command.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="two-treatment-comparisons.html#cb77-1" aria-hidden="true" tabindex="-1"></a>trt_differences <span class="ot">=</span> wide_again_df <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="two-treatment-comparisons.html#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Trt_Diff =</span> Trt_A <span class="sc">-</span> Trt_B)</span>
<span id="cb77-3"><a href="two-treatment-comparisons.html#cb77-3" aria-hidden="true" tabindex="-1"></a>trt_differences</span></code></pre></div>
<pre><code>##   Rep Trt_A Trt_B Trt_Diff
## 1   1     1     5       -4
## 2   2     2     6       -4
## 3   3     3     7       -4
## 4   4     4     8       -4</code></pre>
<p>We now have a new column of the differences between Trt_A and Trt_B.</p>
</div>
<div id="case-study-soybean-fungicide" class="section level3" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> Case Study: Soybean Fungicide</h3>
<p>Soybean treated with fungicide applied at R3 was compared with soybean that was untreated. Data are in the soybean_funcicide.csv</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="two-treatment-comparisons.html#cb79-1" aria-hidden="true" tabindex="-1"></a>soybean <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/soybean_fungicide.csv&quot;</span>)</span>
<span id="cb79-2"><a href="two-treatment-comparisons.html#cb79-2" aria-hidden="true" tabindex="-1"></a>soybean</span></code></pre></div>
<pre><code>##    Block Treatment Yield
## 1      1         A  71.5
## 2      1         B  75.1
## 3      2         A  73.5
## 4      2         B  77.7
## 5      3         B  77.7
## 6      3         A  72.4
## 7      4         B  78.2
## 8      4         A  75.0
## 9      5         A  76.4
## 10     5         B  75.9
## 11     6         A  76.5
## 12     6         B  77.5
## 13     7         B  80.7
## 14     7         A  74.8
## 15     8         A  75.6
## 16     8         B  78.4
## 17     9         B  80.7
## 18     9         A  73.2
## 19    10         B  76.9
## 20    10         A  74.6</code></pre>
<p>This dataset is currently in the long form. To calculate the differenced between Treatments A and B, we need need to convert it to the wide form.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="two-treatment-comparisons.html#cb81-1" aria-hidden="true" tabindex="-1"></a>soybean_wide <span class="ot">=</span> soybean <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="two-treatment-comparisons.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Treatment, Yield)</span>
<span id="cb81-3"><a href="two-treatment-comparisons.html#cb81-3" aria-hidden="true" tabindex="-1"></a>soybean_wide</span></code></pre></div>
<pre><code>##    Block    A    B
## 1      1 71.5 75.1
## 2      2 73.5 77.7
## 3      3 72.4 77.7
## 4      4 75.0 78.2
## 5      5 76.4 75.9
## 6      6 76.5 77.5
## 7      7 74.8 80.7
## 8      8 75.6 78.4
## 9      9 73.2 80.7
## 10    10 74.6 76.9</code></pre>
<p>We now have the two treatments in columns A and B. We can then calculate the difference betwee Treatment A and Treatment B using the mutate function..</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="two-treatment-comparisons.html#cb83-1" aria-hidden="true" tabindex="-1"></a>diffs <span class="ot">=</span> soybean_wide <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="two-treatment-comparisons.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> A<span class="sc">-</span>B)</span>
<span id="cb83-3"><a href="two-treatment-comparisons.html#cb83-3" aria-hidden="true" tabindex="-1"></a>diffs</span></code></pre></div>
<pre><code>##    Block    A    B diff
## 1      1 71.5 75.1 -3.6
## 2      2 73.5 77.7 -4.2
## 3      3 72.4 77.7 -5.3
## 4      4 75.0 78.2 -3.2
## 5      5 76.4 75.9  0.5
## 6      6 76.5 77.5 -1.0
## 7      7 74.8 80.7 -5.9
## 8      8 75.6 78.4 -2.8
## 9      9 73.2 80.7 -7.5
## 10    10 74.6 76.9 -2.3</code></pre>
</div>
<div id="practice-1" class="section level3" number="4.7.3">
<h3><span class="header-section-number">4.7.3</span> Practice 1</h3>
<p>The dataset “darwin.csv” is from a trial by Charles Darwin in which he compared the heights of progeny of corn plants that were self-fertilized and cross-fertilized. Three pairs of plants were grown per pot. Measurements are in inches.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="two-treatment-comparisons.html#cb85-1" aria-hidden="true" tabindex="-1"></a>darwin <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/darwin.csv&quot;</span>)</span>
<span id="cb85-2"><a href="two-treatment-comparisons.html#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="two-treatment-comparisons.html#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(darwin)</span></code></pre></div>
<pre><code>##   pot pair  type height
## 1   I    a cross 23.500
## 2   I    a  self 17.375
## 3   I    b cross 12.000
## 4   I    b  self 20.375
## 5   I    c cross 21.000
## 6   I    c  self 20.000</code></pre>
<p>The data are currently in the long format. We want to convert it to the wide format, where each treatment has its heights in a separate column. Re-structure the type and height columns using the spread_function.</p>
<p>The first few rows of the resulting dataset should look like:</p>
<p>I a 23.500 17.375<br />
I b 12.000 20.375<br />
I c 21.000 20.000<br />
II d 22.000 20.000</p>
</div>
<div id="practice-2" class="section level3" number="4.7.4">
<h3><span class="header-section-number">4.7.4</span> Practice 2</h3>
<p>These data are from a trial that compared apple genotypes.</p>
<p>Calculate the difference between the two apple genotypes (Golden and Redspur) by completing the “mutate” function below.</p>
<p>The first two rows should look like:</p>
<p>R1 121.7750 127.5900 -5.81500<br />
R2 146.7222 126.7625 19.95972</p>
</div>
<div id="practice-3" class="section level3" number="4.7.5">
<h3><span class="header-section-number">4.7.5</span> Practice 3</h3>
<p>Manganese was applied to soybean at the V5 stage near New Baltimore, Ohio.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="two-treatment-comparisons.html#cb87-1" aria-hidden="true" tabindex="-1"></a>manganese <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/soybean_manganese.csv&quot;</span>)</span>
<span id="cb87-2"><a href="two-treatment-comparisons.html#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(manganese)</span></code></pre></div>
<pre><code>##   Block Treatment Yield
## 1     1         A  78.9
## 2     1         B  81.7
## 3     2         A  80.9
## 4     2         B  84.3
## 5     3         B  84.3
## 6     3         A  79.8</code></pre>
<p>Convert the data to wide format so the two treatments are in separate columns</p>
<p>The first two rows of the resulting dataset should look like:</p>
<p>1 78.9 81.7<br />
2 80.9 84.3</p>
<p>Then calculate the difference between treatments A and B by subtracting treatment B from treatment A.</p>
<p>The first couple of rows of the final dataset should look like:</p>
<p>1 78.9 81.7 -2.8<br />
2 80.9 84.3 -3.4</p>
</div>
<div id="practice-4" class="section level3" number="4.7.6">
<h3><span class="header-section-number">4.7.6</span> Practice 4</h3>
<p>Data are from a wheat trial where fungicide was applied during flag leaf stage.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="two-treatment-comparisons.html#cb89-1" aria-hidden="true" tabindex="-1"></a>wheat <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/wheat_fungicide.csv&quot;</span>)</span>
<span id="cb89-2"><a href="two-treatment-comparisons.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wheat)</span></code></pre></div>
<pre><code>##   Block Treatment Yield
## 1     1         B  95.9
## 2     1         A  93.8
## 3     2         A  92.3
## 4     2         B  97.5
## 5     3         A  98.7
## 6     3         B  98.8</code></pre>
<p>Convert the data to wide format. The first few rows should look like:</p>
<p>1 93.8 95.9<br />
2 92.3 97.5<br />
3 98.7 98.8</p>
<p>Calculate the difference between treatments by subtracting Treatment A from Treatment B. The first few rows should look like:</p>
<p>1 93.8 95.9 -2.1<br />
2 92.3 97.5 -5.2<br />
3 98.7 98.8 -0.1</p>
</div>
</div>
<div id="exercise-confidence-interval-of-difference" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Exercise: Confidence Interval of Difference"</h2>
<p>In this unit, we learned that, in the case of two-treatment experiments, we can test whether the populations that receive each treatment are different from each other by testing whether their difference is different from zero. While we will often use the t.test to calculate the probability the two populations are equal, given their measured values, there are times when we may want to report the confidence interval around their difference.</p>
<p>These confidence intervals also be can be gained from the “t.test,” but calculating them manually in these exercises is a good opportunity to sharpen your R skills and hopefully will give you are greater conceptual sense of how the confidence interval works.</p>
<p>To create the confidence interval for the difference between two populations, there are the following steps:
- calculate the differences between the populations in each pair or block
- calculate the overall mean difference between the two populations
- calculate the standard deviation and standard error of the difference
- look up the appropriate t-value based on the desired level of confidence and degrees of freedom
- add and subtract the product of standard error and t-value from the mean difference.</p>
<div id="example-1-1" class="section level3" number="4.8.1">
<h3><span class="header-section-number">4.8.1</span> Example 1</h3>
<p>We will work with the soybean fungicide data from the previous exercise</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="two-treatment-comparisons.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb91-2"><a href="two-treatment-comparisons.html#cb91-2" aria-hidden="true" tabindex="-1"></a>soybean <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/soybean_fungicide.csv&quot;</span>)</span>
<span id="cb91-3"><a href="two-treatment-comparisons.html#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(soybean)</span></code></pre></div>
<pre><code>##   Block Treatment Yield
## 1     1         A  71.5
## 2     1         B  75.1
## 3     2         A  73.5
## 4     2         B  77.7
## 5     3         B  77.7
## 6     3         A  72.4</code></pre>
<div id="calculate-differences" class="section level4" number="4.8.1.1">
<h4><span class="header-section-number">4.8.1.1</span> Calculate Differences</h4>
<p>We will use the “spread” and “mutate” functions from the previous exercises to calculate a the population difference within each block.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="two-treatment-comparisons.html#cb93-1" aria-hidden="true" tabindex="-1"></a>soybean_wide <span class="ot">=</span> soybean <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="two-treatment-comparisons.html#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(Treatment, Yield)</span>
<span id="cb93-3"><a href="two-treatment-comparisons.html#cb93-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-4"><a href="two-treatment-comparisons.html#cb93-4" aria-hidden="true" tabindex="-1"></a>soybean_diff <span class="ot">=</span> soybean_wide <span class="sc">%&gt;%</span></span>
<span id="cb93-5"><a href="two-treatment-comparisons.html#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> A<span class="sc">-</span>B)</span>
<span id="cb93-6"><a href="two-treatment-comparisons.html#cb93-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-7"><a href="two-treatment-comparisons.html#cb93-7" aria-hidden="true" tabindex="-1"></a>soybean_diff</span></code></pre></div>
<pre><code>##    Block    A    B diff
## 1      1 71.5 75.1 -3.6
## 2      2 73.5 77.7 -4.2
## 3      3 72.4 77.7 -5.3
## 4      4 75.0 78.2 -3.2
## 5      5 76.4 75.9  0.5
## 6      6 76.5 77.5 -1.0
## 7      7 74.8 80.7 -5.9
## 8      8 75.6 78.4 -2.8
## 9      9 73.2 80.7 -7.5
## 10    10 74.6 76.9 -2.3</code></pre>
</div>
<div id="calculate-the-mean-difference" class="section level4" number="4.8.1.2">
<h4><span class="header-section-number">4.8.1.2</span> Calculate the Mean Difference</h4>
<p>This is the mean for the new column, diff. As a reminder, soybean_diff$diff tells R to use the diff column of the soybean_diff data frame.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="two-treatment-comparisons.html#cb95-1" aria-hidden="true" tabindex="-1"></a>diff_mean <span class="ot">=</span> <span class="fu">mean</span>(soybean_diff<span class="sc">$</span>diff)</span>
<span id="cb95-2"><a href="two-treatment-comparisons.html#cb95-2" aria-hidden="true" tabindex="-1"></a>diff_mean</span></code></pre></div>
<pre><code>## [1] -3.53</code></pre>
</div>
<div id="calculate-the-standard-deviation-and-standard-error" class="section level4" number="4.8.1.3">
<h4><span class="header-section-number">4.8.1.3</span> Calculate the Standard Deviation and Standard Error</h4>
<p>We can calculte the standard deviation using the “sd” function.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="two-treatment-comparisons.html#cb97-1" aria-hidden="true" tabindex="-1"></a>diff_sd <span class="ot">=</span> <span class="fu">sd</span>(soybean_diff<span class="sc">$</span>diff)</span>
<span id="cb97-2"><a href="two-treatment-comparisons.html#cb97-2" aria-hidden="true" tabindex="-1"></a>diff_sd</span></code></pre></div>
<pre><code>## [1] 2.351383</code></pre>
<p>The standard error is the standard deviation, divided by the square root of the number of observations, n. In this example, n=10. We can verify this using the “length” function of R. We can then calculate the standard error, which we will call “diff_se.”</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="two-treatment-comparisons.html#cb99-1" aria-hidden="true" tabindex="-1"></a>diff_N <span class="ot">=</span> <span class="fu">length</span>(soybean_diff<span class="sc">$</span>diff)</span>
<span id="cb99-2"><a href="two-treatment-comparisons.html#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="two-treatment-comparisons.html#cb99-3" aria-hidden="true" tabindex="-1"></a>diff_se <span class="ot">=</span> diff_sd <span class="sc">/</span> <span class="fu">sqrt</span>(diff_N)</span></code></pre></div>
<p>diff_se is the standard error. The formula we used is equal to 2.35 / sqrt(10). We just used the variables to save retyping.</p>
</div>
<div id="calculate-the-t-value" class="section level4" number="4.8.1.4">
<h4><span class="header-section-number">4.8.1.4</span> Calculate the t-value</h4>
<p>We calcuate the t-value to use in our confidence interval by using the “qt” function of R. Remember, the qt function uses two arguments. The first is the desired level of confidence. We want a 95% confidence interval, so we will use 0.975. That will leave 0.025, or 2.5%, beyond the upper and lower limits of our confidence interval.</p>
<p>The second argument is the degrees of freedom. Since we have observed ten differences, we have nine degrees of freedom.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="two-treatment-comparisons.html#cb100-1" aria-hidden="true" tabindex="-1"></a>t_value <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">9</span>)</span>
<span id="cb100-2"><a href="two-treatment-comparisons.html#cb100-2" aria-hidden="true" tabindex="-1"></a>t_value</span></code></pre></div>
<pre><code>## [1] 2.262157</code></pre>
<p>Our t_value is approximately 2.26.</p>
</div>
<div id="calculate-the-confidence-interval" class="section level4" number="4.8.1.5">
<h4><span class="header-section-number">4.8.1.5</span> Calculate the Confidence Interval</h4>
<p>The confidence interval is bound by upper and lower confidence limits. The lower limit is equal to the mean difference minus the product of the standard error of the difference and t-value. The upper limit is the mean difference plus the product of the standard error of the difference.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="two-treatment-comparisons.html#cb102-1" aria-hidden="true" tabindex="-1"></a>lower_limit <span class="ot">=</span> diff_mean <span class="sc">-</span> (diff_se <span class="sc">*</span> t_value)</span>
<span id="cb102-2"><a href="two-treatment-comparisons.html#cb102-2" aria-hidden="true" tabindex="-1"></a>upper_limit <span class="ot">=</span> diff_mean <span class="sc">+</span> (diff_se <span class="sc">*</span> t_value)</span>
<span id="cb102-3"><a href="two-treatment-comparisons.html#cb102-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-4"><a href="two-treatment-comparisons.html#cb102-4" aria-hidden="true" tabindex="-1"></a>lower_limit</span></code></pre></div>
<pre><code>## [1] -5.212078</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="two-treatment-comparisons.html#cb104-1" aria-hidden="true" tabindex="-1"></a>upper_limit</span></code></pre></div>
<pre><code>## [1] -1.847922</code></pre>
<p>The 95% confidence interval, with 9 df, for the difference is (-5.21, -1.85). Note the confidence interval does not include zero, therefore the two populations (and, thus, the treatments they received) are significantly different at the P&lt;0.05 level.</p>
<p>Which treatment was greater? Since we subtracted B from A, the negative confidence interval indicates B was greater.</p>
</div>
</div>
<div id="example-2-1" class="section level3" number="4.8.2">
<h3><span class="header-section-number">4.8.2</span> Example 2</h3>
<p>We will work with the Darwin corn data.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="two-treatment-comparisons.html#cb106-1" aria-hidden="true" tabindex="-1"></a>darwin <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/darwin.csv&quot;</span>)</span>
<span id="cb106-2"><a href="two-treatment-comparisons.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(darwin)</span></code></pre></div>
<pre><code>##   pot pair  type height
## 1   I    a cross 23.500
## 2   I    a  self 17.375
## 3   I    b cross 12.000
## 4   I    b  self 20.375
## 5   I    c cross 21.000
## 6   I    c  self 20.000</code></pre>
<div id="calcuate-differences" class="section level4" number="4.8.2.1">
<h4><span class="header-section-number">4.8.2.1</span> Calcuate Differences</h4>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="two-treatment-comparisons.html#cb108-1" aria-hidden="true" tabindex="-1"></a>darwin_wide <span class="ot">=</span> darwin <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="two-treatment-comparisons.html#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(type, height)</span>
<span id="cb108-3"><a href="two-treatment-comparisons.html#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(darwin_wide)</span></code></pre></div>
<pre><code>##   pot pair  cross   self
## 1   I    a 23.500 17.375
## 2   I    b 12.000 20.375
## 3   I    c 21.000 20.000
## 4  II    d 22.000 20.000
## 5  II    e 19.125 18.375
## 6  II    f 21.500 18.625</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="two-treatment-comparisons.html#cb110-1" aria-hidden="true" tabindex="-1"></a>darwin_diff <span class="ot">=</span> darwin_wide <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="two-treatment-comparisons.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> cross <span class="sc">-</span> self)</span>
<span id="cb110-3"><a href="two-treatment-comparisons.html#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(darwin_diff)</span></code></pre></div>
<pre><code>##   pot pair  cross   self   diff
## 1   I    a 23.500 17.375  6.125
## 2   I    b 12.000 20.375 -8.375
## 3   I    c 21.000 20.000  1.000
## 4  II    d 22.000 20.000  2.000
## 5  II    e 19.125 18.375  0.750
## 6  II    f 21.500 18.625  2.875</code></pre>
</div>
<div id="calculate-mean-difference" class="section level4" number="4.8.2.2">
<h4><span class="header-section-number">4.8.2.2</span> Calculate Mean Difference</h4>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="two-treatment-comparisons.html#cb112-1" aria-hidden="true" tabindex="-1"></a>darwin_diff_mean <span class="ot">=</span> <span class="fu">mean</span>(darwin_diff<span class="sc">$</span>diff) </span>
<span id="cb112-2"><a href="two-treatment-comparisons.html#cb112-2" aria-hidden="true" tabindex="-1"></a>darwin_diff_mean</span></code></pre></div>
<pre><code>## [1] 2.616667</code></pre>
</div>
<div id="calculate-standard-deviation-and-standard-error" class="section level4" number="4.8.2.3">
<h4><span class="header-section-number">4.8.2.3</span> Calculate Standard Deviation and Standard Error</h4>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="two-treatment-comparisons.html#cb114-1" aria-hidden="true" tabindex="-1"></a>darwin_diff_sd <span class="ot">=</span> <span class="fu">sd</span>(darwin_diff<span class="sc">$</span>diff)</span>
<span id="cb114-2"><a href="two-treatment-comparisons.html#cb114-2" aria-hidden="true" tabindex="-1"></a>darwin_diff_N <span class="ot">=</span> <span class="fu">length</span>(darwin_diff<span class="sc">$</span>diff)</span>
<span id="cb114-3"><a href="two-treatment-comparisons.html#cb114-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-4"><a href="two-treatment-comparisons.html#cb114-4" aria-hidden="true" tabindex="-1"></a>darwin_diff_se <span class="ot">=</span> darwin_diff_sd <span class="sc">/</span> <span class="fu">sqrt</span>(darwin_diff_N)</span>
<span id="cb114-5"><a href="two-treatment-comparisons.html#cb114-5" aria-hidden="true" tabindex="-1"></a>darwin_diff_se</span></code></pre></div>
<pre><code>## [1] 1.218195</code></pre>
</div>
<div id="calculate-the-t-value-1" class="section level4" number="4.8.2.4">
<h4><span class="header-section-number">4.8.2.4</span> Calculate the t-value</h4>
<p>There were 15 pairs, so there are 14 degrees of freedom. We will again calculate the t-value for the 95% confidence interval.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="two-treatment-comparisons.html#cb116-1" aria-hidden="true" tabindex="-1"></a>darwin_t_value <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">14</span>)</span>
<span id="cb116-2"><a href="two-treatment-comparisons.html#cb116-2" aria-hidden="true" tabindex="-1"></a>darwin_t_value</span></code></pre></div>
<pre><code>## [1] 2.144787</code></pre>
</div>
<div id="calculate-the-confidence-interval-1" class="section level4" number="4.8.2.5">
<h4><span class="header-section-number">4.8.2.5</span> Calculate the Confidence Interval</h4>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="two-treatment-comparisons.html#cb118-1" aria-hidden="true" tabindex="-1"></a>darwin_lower_limit <span class="ot">=</span> darwin_diff_mean <span class="sc">-</span> (darwin_diff_se <span class="sc">*</span> darwin_t_value)</span>
<span id="cb118-2"><a href="two-treatment-comparisons.html#cb118-2" aria-hidden="true" tabindex="-1"></a>darwin_upper_limit <span class="ot">=</span> darwin_diff_mean <span class="sc">+</span> (darwin_diff_se <span class="sc">*</span> darwin_t_value)</span>
<span id="cb118-3"><a href="two-treatment-comparisons.html#cb118-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-4"><a href="two-treatment-comparisons.html#cb118-4" aria-hidden="true" tabindex="-1"></a>darwin_lower_limit</span></code></pre></div>
<pre><code>## [1] 0.003899165</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="two-treatment-comparisons.html#cb120-1" aria-hidden="true" tabindex="-1"></a>darwin_upper_limit</span></code></pre></div>
<pre><code>## [1] 5.229434</code></pre>
<p>The confidence interval was (0.004, 5.229). It does not include zero, so the difference is significant. Since we subtracted the self-pollinated values from the cross-pollinated values, the positive difference means the cross-pollinated plants were taller than the self-pollinated plants.</p>
</div>
</div>
</div>
<div id="exercise-t-test" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Exercise: T-Test</h2>
<p>The t-test is used to test the probability that two populations are different. In a two-treatment trial, each population will receive a different treatment (an input or management practice). In R, we can use the “t.test” function to quickly determine the probability that two treatments are different.</p>
<div id="case-study-1-wheat-fungicide" class="section level3" number="4.9.1">
<h3><span class="header-section-number">4.9.1</span> Case Study 1: Wheat Fungicide</h3>
<p>Let’s start by loading the data and using the “head” command to examine its structure. Treatment B was a fungicide applied at flag leaf. Treatment A is the untreated control.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="two-treatment-comparisons.html#cb122-1" aria-hidden="true" tabindex="-1"></a>wheat <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/wheat_fungicide.csv&quot;</span>)</span>
<span id="cb122-2"><a href="two-treatment-comparisons.html#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wheat)</span></code></pre></div>
<pre><code>##   Block Treatment Yield
## 1     1         B  95.9
## 2     1         A  93.8
## 3     2         A  92.3
## 4     2         B  97.5
## 5     3         A  98.7
## 6     3         B  98.8</code></pre>
</div>
<div id="t-test-1" class="section level3" number="4.9.2">
<h3><span class="header-section-number">4.9.2</span> T-Test</h3>
<p>The t.test function in R requires at least three arguments. The first is a model statement. In testing whether populations that receive different treatments have different yields, we are modelling yield as a function of treatment.</p>
<p>We can express this in the following statement:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="two-treatment-comparisons.html#cb124-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> Yield <span class="sc">~</span> Treatment</span></code></pre></div>
<p>We can then plug the model statement into our t.test. The second argument to the t.test, “data=wheat,” tells R which data frame to analyze. The third, “paired=TRUE,” tells R the treatments were paired (blocked) in our experiment.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="two-treatment-comparisons.html#cb125-1" aria-hidden="true" tabindex="-1"></a>wheat_t_test <span class="ot">=</span> <span class="fu">t.test</span>(model, <span class="at">data=</span>wheat, <span class="at">paired=</span><span class="cn">TRUE</span>)</span>
<span id="cb125-2"><a href="two-treatment-comparisons.html#cb125-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-3"><a href="two-treatment-comparisons.html#cb125-3" aria-hidden="true" tabindex="-1"></a>wheat_t_test</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Yield by Treatment
## t = -3.7166, df = 9, p-value = 0.004796
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.871641 -1.428359
## sample estimates:
## mean of the differences 
##                   -3.65</code></pre>
<p>What would happen if we left out the “paired=TRUE” argument?</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="two-treatment-comparisons.html#cb127-1" aria-hidden="true" tabindex="-1"></a>wheat_t_test_independent <span class="ot">=</span> <span class="fu">t.test</span>(model, <span class="at">data=</span>wheat)</span>
<span id="cb127-2"><a href="two-treatment-comparisons.html#cb127-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-3"><a href="two-treatment-comparisons.html#cb127-3" aria-hidden="true" tabindex="-1"></a>wheat_t_test_independent</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Yield by Treatment
## t = -3.9101, df = 17.91, p-value = 0.001034
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.611876 -1.688124
## sample estimates:
## mean in group A mean in group B 
##           94.65           98.30</code></pre>
<p>We notice, that the t-value, degrees of freedom, and p-value are all different. This is because R analyzes the two treatments as independent populations with their own variances – instead of analyzing the differences between each pair of treatments. The df of 17.91 is not a whole number – this also tells us that R is treating the variances differently and using algorithms it would not use with a paired design.</p>
<p>Lets look at the correct analysis again.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="two-treatment-comparisons.html#cb129-1" aria-hidden="true" tabindex="-1"></a>wheat_t_test</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Yield by Treatment
## t = -3.7166, df = 9, p-value = 0.004796
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.871641 -1.428359
## sample estimates:
## mean of the differences 
##                   -3.65</code></pre>
<p>Highlights of the output include the p-value, and the 95% confidence interval. The p-value tells us there is about a 0.005, or 0.5% probability that the difference between the treatments is actually zero, give the actual observed difference. The 95% confidence interval is a range around the measured difference, -3.65, that is likely to include the true difference between the populations. That the confidence interval does not include zero is a reminder that the difference between the two populations is significant.</p>
<p>There are a couple of other arguments we may include in the “t.test” function. Remember that the t-test tests whether the measured difference between populations is different from a hypothetical difference. Usually, this hypothetical difference is zero, as we can see in the output above where it says “true difference in means is not equal to 0.” But it is good to extra-careful and specify this by including the argument “mu=0” in our t.test function.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="two-treatment-comparisons.html#cb131-1" aria-hidden="true" tabindex="-1"></a>wheat_t_test_mu_zero <span class="ot">=</span> <span class="fu">t.test</span>(model, <span class="at">data=</span>wheat, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb131-2"><a href="two-treatment-comparisons.html#cb131-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-3"><a href="two-treatment-comparisons.html#cb131-3" aria-hidden="true" tabindex="-1"></a>wheat_t_test_mu_zero</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Yield by Treatment
## t = -3.7166, df = 9, p-value = 0.004796
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.871641 -1.428359
## sample estimates:
## mean of the differences 
##                   -3.65</code></pre>
<p>Occassionally, we might want to test whether the observed difference between populations is something other than 0. What if in our wheat trial we wanted to test whether the observed difference between populations was different than -1? In that case, we would specify mu=-1 in our code.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="two-treatment-comparisons.html#cb133-1" aria-hidden="true" tabindex="-1"></a>wheat_t_test_mu_1 <span class="ot">=</span> <span class="fu">t.test</span>(model, <span class="at">data=</span>wheat, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">mu=</span><span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb133-2"><a href="two-treatment-comparisons.html#cb133-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-3"><a href="two-treatment-comparisons.html#cb133-3" aria-hidden="true" tabindex="-1"></a>wheat_t_test_mu_1</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Yield by Treatment
## t = -2.6983, df = 9, p-value = 0.02446
## alternative hypothesis: true difference in means is not equal to -1
## 95 percent confidence interval:
##  -5.871641 -1.428359
## sample estimates:
## mean of the differences 
##                   -3.65</code></pre>
<p>We can see that our p-value has changed, as has the “alternative hypothesis” statement.</p>
</div>
<div id="case-study-2-apple-variety" class="section level3" number="4.9.3">
<h3><span class="header-section-number">4.9.3</span> Case Study 2: Apple Variety</h3>
<p>Lets look at our apple data:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="two-treatment-comparisons.html#cb135-1" aria-hidden="true" tabindex="-1"></a>apple <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data-unit-4/exercise_data/apple_genotype.csv&quot;</span>)</span>
<span id="cb135-2"><a href="two-treatment-comparisons.html#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(apple)</span></code></pre></div>
<pre><code>##   rep     gen    yield
## 1  R1  Golden 121.7750
## 2  R1 Redspur 127.5900
## 3  R2  Golden 146.7222
## 4  R2 Redspur 126.7625
## 5  R3  Golden 145.7500
## 6  R3 Redspur 132.9364</code></pre>
<p>Our model is now that yield is a function of gen (genotype). Our model statement is therefore:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="two-treatment-comparisons.html#cb137-1" aria-hidden="true" tabindex="-1"></a>apple_model <span class="ot">=</span> yield <span class="sc">~</span> gen</span></code></pre></div>
<p>And our t-test is as follows:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="two-treatment-comparisons.html#cb138-1" aria-hidden="true" tabindex="-1"></a>apple_t_test <span class="ot">=</span> <span class="fu">t.test</span>(apple_model, <span class="at">data=</span>apple, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb138-2"><a href="two-treatment-comparisons.html#cb138-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-3"><a href="two-treatment-comparisons.html#cb138-3" aria-hidden="true" tabindex="-1"></a>apple_t_test</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  yield by gen
## t = -0.41501, df = 4, p-value = 0.6994
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -28.58021  21.14724
## sample estimates:
## mean of the differences 
##               -3.716484</code></pre>
<p>We can see from above that our p-value is about 0.70. Sometimes it snows in April. And sometimes our treatments aren’t significantly different. If we look at our confidence interval, we can confirm that it includes zero.</p>
</div>
<div id="practice" class="section level3" number="4.9.4">
<h3><span class="header-section-number">4.9.4</span> Practice</h3>
<p>What is the t-test value for the “data-unit-4/exercise_soybean_fungicide.csv” trial? Assume the treatments are paired. Your t-test should reveal a p-value of 0.001048.</p>
<p>What is the t-test value for the “data-unit-4/exercise_soybean_manganese.csv” trial? Assume the treatments are paired. Your t-test should reveal a p-value of 0.005143.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sample-statistics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="understanding-statistical-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-start.pdf", "bookdown-start.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
